// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LoginSubCmd.proto

package LoginSubCmd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 此文件对应主消息为 LOGIN_MAIN_CMD
//
type EnSubCmdID int32

const (
	EnSubCmdID_REQUEST_LOGIN_SUB_CMD                  EnSubCmdID = 2
	EnSubCmdID_RETURN_LOGININFO_SUB_CMD               EnSubCmdID = 3
	EnSubCmdID_LOGIN_ERROR_CODE_SUB_CMD               EnSubCmdID = 4
	EnSubCmdID_VISITOR_REQUEST_LOGIN_SUB_CMD          EnSubCmdID = 5
	EnSubCmdID_REQUEST_CREATE_MOBILE_ACCOUNT_SUB_CMD  EnSubCmdID = 7
	EnSubCmdID_RETURN_CREATE_ACCOUNT_RESULT_SUB_CMD   EnSubCmdID = 8
	EnSubCmdID_RETURN_MOBILE_TOKEN_RESULT_SUB_CMD     EnSubCmdID = 9
	EnSubCmdID_REQUEST_RESET_PASSWD_TOKEN             EnSubCmdID = 10
	EnSubCmdID_RESET_NEW_PASSWD_SUB_CMD               EnSubCmdID = 11
	EnSubCmdID_RETURN_RESET_PASSWD_TOKEN              EnSubCmdID = 12
	EnSubCmdID_RETURN_RESET_NEW_PASSWD_RESULT_SUB_CMD EnSubCmdID = 13
	EnSubCmdID_TECENT_REQUEST_LOGIN_SUB_CMD           EnSubCmdID = 14
	EnSubCmdID_TECENT_LOGIN_RESULT_SUB_CMD            EnSubCmdID = 15
	EnSubCmdID_REQUEST_CHANGE_DEVICE_TOKEN            EnSubCmdID = 16
	EnSubCmdID_RETURN_CHANGE_DEVICE_TOKEN             EnSubCmdID = 17
)

var EnSubCmdID_name = map[int32]string{
	2:  "REQUEST_LOGIN_SUB_CMD",
	3:  "RETURN_LOGININFO_SUB_CMD",
	4:  "LOGIN_ERROR_CODE_SUB_CMD",
	5:  "VISITOR_REQUEST_LOGIN_SUB_CMD",
	7:  "REQUEST_CREATE_MOBILE_ACCOUNT_SUB_CMD",
	8:  "RETURN_CREATE_ACCOUNT_RESULT_SUB_CMD",
	9:  "RETURN_MOBILE_TOKEN_RESULT_SUB_CMD",
	10: "REQUEST_RESET_PASSWD_TOKEN",
	11: "RESET_NEW_PASSWD_SUB_CMD",
	12: "RETURN_RESET_PASSWD_TOKEN",
	13: "RETURN_RESET_NEW_PASSWD_RESULT_SUB_CMD",
	14: "TECENT_REQUEST_LOGIN_SUB_CMD",
	15: "TECENT_LOGIN_RESULT_SUB_CMD",
	16: "REQUEST_CHANGE_DEVICE_TOKEN",
	17: "RETURN_CHANGE_DEVICE_TOKEN",
}
var EnSubCmdID_value = map[string]int32{
	"REQUEST_LOGIN_SUB_CMD":                  2,
	"RETURN_LOGININFO_SUB_CMD":               3,
	"LOGIN_ERROR_CODE_SUB_CMD":               4,
	"VISITOR_REQUEST_LOGIN_SUB_CMD":          5,
	"REQUEST_CREATE_MOBILE_ACCOUNT_SUB_CMD":  7,
	"RETURN_CREATE_ACCOUNT_RESULT_SUB_CMD":   8,
	"RETURN_MOBILE_TOKEN_RESULT_SUB_CMD":     9,
	"REQUEST_RESET_PASSWD_TOKEN":             10,
	"RESET_NEW_PASSWD_SUB_CMD":               11,
	"RETURN_RESET_PASSWD_TOKEN":              12,
	"RETURN_RESET_NEW_PASSWD_RESULT_SUB_CMD": 13,
	"TECENT_REQUEST_LOGIN_SUB_CMD":           14,
	"TECENT_LOGIN_RESULT_SUB_CMD":            15,
	"REQUEST_CHANGE_DEVICE_TOKEN":            16,
	"RETURN_CHANGE_DEVICE_TOKEN":             17,
}

func (x EnSubCmdID) Enum() *EnSubCmdID {
	p := new(EnSubCmdID)
	*p = x
	return p
}
func (x EnSubCmdID) String() string {
	return proto.EnumName(EnSubCmdID_name, int32(x))
}
func (x *EnSubCmdID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EnSubCmdID_value, data, "EnSubCmdID")
	if err != nil {
		return err
	}
	*x = EnSubCmdID(value)
	return nil
}
func (EnSubCmdID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{0}
}

type EnErrorCode int32

const (
	EnErrorCode_ERROR_CODE_UNKNOWN                      EnErrorCode = 0
	EnErrorCode_ERROR_CODE_ACCOUNT                      EnErrorCode = 1
	EnErrorCode_ERROR_CODE_NOSERVICE                    EnErrorCode = 2
	EnErrorCode_ERROR_CODE_FORBIDUSE                    EnErrorCode = 3
	EnErrorCode_ERROR_CODE_NOEXIST                      EnErrorCode = 4
	EnErrorCode_ERROR_CODE_ALREADYEXIST                 EnErrorCode = 5
	EnErrorCode_ERROR_CODE_CREATE_ERR                   EnErrorCode = 6
	EnErrorCode_ERROR_CODE_SPERDID_ERR                  EnErrorCode = 7
	EnErrorCode_ERROR_CODE_ACCOUNT_COUNT_LIMIT          EnErrorCode = 8
	EnErrorCode_ERROR_CODE_TECENT_FAIL                  EnErrorCode = 9
	EnErrorCode_ERROR_CODE_CHANGE_DEVICE                EnErrorCode = 10
	EnErrorCode_ERROR_CODE_CHANGE_DEVICE_TOKEN_TIME_OUT EnErrorCode = 11
	EnErrorCode_ERROR_CODE_CHANGE_DEVICE_TOKEN_ERROR    EnErrorCode = 12
)

var EnErrorCode_name = map[int32]string{
	0:  "ERROR_CODE_UNKNOWN",
	1:  "ERROR_CODE_ACCOUNT",
	2:  "ERROR_CODE_NOSERVICE",
	3:  "ERROR_CODE_FORBIDUSE",
	4:  "ERROR_CODE_NOEXIST",
	5:  "ERROR_CODE_ALREADYEXIST",
	6:  "ERROR_CODE_CREATE_ERR",
	7:  "ERROR_CODE_SPERDID_ERR",
	8:  "ERROR_CODE_ACCOUNT_COUNT_LIMIT",
	9:  "ERROR_CODE_TECENT_FAIL",
	10: "ERROR_CODE_CHANGE_DEVICE",
	11: "ERROR_CODE_CHANGE_DEVICE_TOKEN_TIME_OUT",
	12: "ERROR_CODE_CHANGE_DEVICE_TOKEN_ERROR",
}
var EnErrorCode_value = map[string]int32{
	"ERROR_CODE_UNKNOWN":                      0,
	"ERROR_CODE_ACCOUNT":                      1,
	"ERROR_CODE_NOSERVICE":                    2,
	"ERROR_CODE_FORBIDUSE":                    3,
	"ERROR_CODE_NOEXIST":                      4,
	"ERROR_CODE_ALREADYEXIST":                 5,
	"ERROR_CODE_CREATE_ERR":                   6,
	"ERROR_CODE_SPERDID_ERR":                  7,
	"ERROR_CODE_ACCOUNT_COUNT_LIMIT":          8,
	"ERROR_CODE_TECENT_FAIL":                  9,
	"ERROR_CODE_CHANGE_DEVICE":                10,
	"ERROR_CODE_CHANGE_DEVICE_TOKEN_TIME_OUT": 11,
	"ERROR_CODE_CHANGE_DEVICE_TOKEN_ERROR":    12,
}

func (x EnErrorCode) Enum() *EnErrorCode {
	p := new(EnErrorCode)
	*p = x
	return p
}
func (x EnErrorCode) String() string {
	return proto.EnumName(EnErrorCode_name, int32(x))
}
func (x *EnErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EnErrorCode_value, data, "EnErrorCode")
	if err != nil {
		return err
	}
	*x = EnErrorCode(value)
	return nil
}
func (EnErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{1}
}

// 客服端数据
// 版本号
// subCmd  REQUEST_LOGIN_SUB_CMD
type LoginRequestInfo struct {
	Account              *string  `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Passwd               *string  `protobuf:"bytes,2,req,name=passwd" json:"passwd,omitempty"`
	IDevice              *int32   `protobuf:"varint,3,opt,name=iDevice" json:"iDevice,omitempty"`
	IPlatform            *int32   `protobuf:"varint,4,opt,name=iPlatform" json:"iPlatform,omitempty"`
	IVersion             *string  `protobuf:"bytes,5,opt,name=iVersion" json:"iVersion,omitempty"`
	UiSpread             *uint32  `protobuf:"varint,6,opt,name=uiSpread" json:"uiSpread,omitempty"`
	Packageflag          *string  `protobuf:"bytes,7,opt,name=packageflag" json:"packageflag,omitempty"`
	DeviceString         *string  `protobuf:"bytes,8,opt,name=deviceString" json:"deviceString,omitempty"`
	ClientIp             *string  `protobuf:"bytes,11,opt,name=clientIp" json:"clientIp,omitempty"`
	PhoneNumber          *string  `protobuf:"bytes,12,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	Token                *string  `protobuf:"bytes,13,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequestInfo) Reset()         { *m = LoginRequestInfo{} }
func (m *LoginRequestInfo) String() string { return proto.CompactTextString(m) }
func (*LoginRequestInfo) ProtoMessage()    {}
func (*LoginRequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{0}
}
func (m *LoginRequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequestInfo.Unmarshal(m, b)
}
func (m *LoginRequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequestInfo.Marshal(b, m, deterministic)
}
func (dst *LoginRequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequestInfo.Merge(dst, src)
}
func (m *LoginRequestInfo) XXX_Size() int {
	return xxx_messageInfo_LoginRequestInfo.Size(m)
}
func (m *LoginRequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequestInfo proto.InternalMessageInfo

func (m *LoginRequestInfo) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *LoginRequestInfo) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func (m *LoginRequestInfo) GetIDevice() int32 {
	if m != nil && m.IDevice != nil {
		return *m.IDevice
	}
	return 0
}

func (m *LoginRequestInfo) GetIPlatform() int32 {
	if m != nil && m.IPlatform != nil {
		return *m.IPlatform
	}
	return 0
}

func (m *LoginRequestInfo) GetIVersion() string {
	if m != nil && m.IVersion != nil {
		return *m.IVersion
	}
	return ""
}

func (m *LoginRequestInfo) GetUiSpread() uint32 {
	if m != nil && m.UiSpread != nil {
		return *m.UiSpread
	}
	return 0
}

func (m *LoginRequestInfo) GetPackageflag() string {
	if m != nil && m.Packageflag != nil {
		return *m.Packageflag
	}
	return ""
}

func (m *LoginRequestInfo) GetDeviceString() string {
	if m != nil && m.DeviceString != nil {
		return *m.DeviceString
	}
	return ""
}

func (m *LoginRequestInfo) GetClientIp() string {
	if m != nil && m.ClientIp != nil {
		return *m.ClientIp
	}
	return ""
}

func (m *LoginRequestInfo) GetPhoneNumber() string {
	if m != nil && m.PhoneNumber != nil {
		return *m.PhoneNumber
	}
	return ""
}

func (m *LoginRequestInfo) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// 服务器数据
// subCmd  RETURN_LOGININFO_SUB_CMD
type LoginReturnInfo struct {
	Userid               *int32   `protobuf:"varint,2,req,name=userid" json:"userid,omitempty"`
	LobbyAddress         *string  `protobuf:"bytes,3,req,name=lobbyAddress" json:"lobbyAddress,omitempty"`
	LobbyPort            *int32   `protobuf:"varint,4,req,name=lobbyPort" json:"lobbyPort,omitempty"`
	Token                *string  `protobuf:"bytes,5,req,name=token" json:"token,omitempty"`
	Account              *string  `protobuf:"bytes,6,req,name=account" json:"account,omitempty"`
	AccountType          *int32   `protobuf:"varint,7,req,name=accountType" json:"accountType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReturnInfo) Reset()         { *m = LoginReturnInfo{} }
func (m *LoginReturnInfo) String() string { return proto.CompactTextString(m) }
func (*LoginReturnInfo) ProtoMessage()    {}
func (*LoginReturnInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{1}
}
func (m *LoginReturnInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReturnInfo.Unmarshal(m, b)
}
func (m *LoginReturnInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReturnInfo.Marshal(b, m, deterministic)
}
func (dst *LoginReturnInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReturnInfo.Merge(dst, src)
}
func (m *LoginReturnInfo) XXX_Size() int {
	return xxx_messageInfo_LoginReturnInfo.Size(m)
}
func (m *LoginReturnInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReturnInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReturnInfo proto.InternalMessageInfo

func (m *LoginReturnInfo) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *LoginReturnInfo) GetLobbyAddress() string {
	if m != nil && m.LobbyAddress != nil {
		return *m.LobbyAddress
	}
	return ""
}

func (m *LoginReturnInfo) GetLobbyPort() int32 {
	if m != nil && m.LobbyPort != nil {
		return *m.LobbyPort
	}
	return 0
}

func (m *LoginReturnInfo) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *LoginReturnInfo) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *LoginReturnInfo) GetAccountType() int32 {
	if m != nil && m.AccountType != nil {
		return *m.AccountType
	}
	return 0
}

// LOGIN_ERROR_CODE_SUB_CMD
type LoginErrorCode struct {
	Retcode              *EnErrorCode `protobuf:"varint,1,req,name=retcode,enum=LoginSubCmd.EnErrorCode" json:"retcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginErrorCode) Reset()         { *m = LoginErrorCode{} }
func (m *LoginErrorCode) String() string { return proto.CompactTextString(m) }
func (*LoginErrorCode) ProtoMessage()    {}
func (*LoginErrorCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{2}
}
func (m *LoginErrorCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginErrorCode.Unmarshal(m, b)
}
func (m *LoginErrorCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginErrorCode.Marshal(b, m, deterministic)
}
func (dst *LoginErrorCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginErrorCode.Merge(dst, src)
}
func (m *LoginErrorCode) XXX_Size() int {
	return xxx_messageInfo_LoginErrorCode.Size(m)
}
func (m *LoginErrorCode) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginErrorCode.DiscardUnknown(m)
}

var xxx_messageInfo_LoginErrorCode proto.InternalMessageInfo

func (m *LoginErrorCode) GetRetcode() EnErrorCode {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return EnErrorCode_ERROR_CODE_UNKNOWN
}

// VISITOR_REQUEST_LOGIN_SUB_CMD                        = 5;   // 游客登录
type CS_Visitor_Request_Login struct {
	DeviceString         *string  `protobuf:"bytes,1,req,name=deviceString" json:"deviceString,omitempty"`
	IDevice              *int32   `protobuf:"varint,2,req,name=iDevice" json:"iDevice,omitempty"`
	Packageflag          *string  `protobuf:"bytes,3,req,name=packageflag" json:"packageflag,omitempty"`
	ClientIp             *string  `protobuf:"bytes,4,opt,name=clientIp" json:"clientIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Visitor_Request_Login) Reset()         { *m = CS_Visitor_Request_Login{} }
func (m *CS_Visitor_Request_Login) String() string { return proto.CompactTextString(m) }
func (*CS_Visitor_Request_Login) ProtoMessage()    {}
func (*CS_Visitor_Request_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{3}
}
func (m *CS_Visitor_Request_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Visitor_Request_Login.Unmarshal(m, b)
}
func (m *CS_Visitor_Request_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Visitor_Request_Login.Marshal(b, m, deterministic)
}
func (dst *CS_Visitor_Request_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Visitor_Request_Login.Merge(dst, src)
}
func (m *CS_Visitor_Request_Login) XXX_Size() int {
	return xxx_messageInfo_CS_Visitor_Request_Login.Size(m)
}
func (m *CS_Visitor_Request_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Visitor_Request_Login.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Visitor_Request_Login proto.InternalMessageInfo

func (m *CS_Visitor_Request_Login) GetDeviceString() string {
	if m != nil && m.DeviceString != nil {
		return *m.DeviceString
	}
	return ""
}

func (m *CS_Visitor_Request_Login) GetIDevice() int32 {
	if m != nil && m.IDevice != nil {
		return *m.IDevice
	}
	return 0
}

func (m *CS_Visitor_Request_Login) GetPackageflag() string {
	if m != nil && m.Packageflag != nil {
		return *m.Packageflag
	}
	return ""
}

func (m *CS_Visitor_Request_Login) GetClientIp() string {
	if m != nil && m.ClientIp != nil {
		return *m.ClientIp
	}
	return ""
}

// REQUEST_CREATE_MOBILE_ACCOUNT_SUB_CMD                = 7;   // 手机号注册账号
type CS_Request_Mobile_Account struct {
	PhoneNumber          *string  `protobuf:"bytes,1,req,name=phoneNumber" json:"phoneNumber,omitempty"`
	Passwd               *string  `protobuf:"bytes,2,req,name=passwd" json:"passwd,omitempty"`
	Token                *string  `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	UiSpread             *uint32  `protobuf:"varint,4,opt,name=uiSpread" json:"uiSpread,omitempty"`
	Devicestring         *string  `protobuf:"bytes,5,opt,name=devicestring" json:"devicestring,omitempty"`
	Packageflag          *string  `protobuf:"bytes,6,opt,name=packageflag" json:"packageflag,omitempty"`
	IDevice              *int32   `protobuf:"varint,7,req,name=iDevice" json:"iDevice,omitempty"`
	ClientIp             *string  `protobuf:"bytes,8,opt,name=clientIp" json:"clientIp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Request_Mobile_Account) Reset()         { *m = CS_Request_Mobile_Account{} }
func (m *CS_Request_Mobile_Account) String() string { return proto.CompactTextString(m) }
func (*CS_Request_Mobile_Account) ProtoMessage()    {}
func (*CS_Request_Mobile_Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{4}
}
func (m *CS_Request_Mobile_Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Request_Mobile_Account.Unmarshal(m, b)
}
func (m *CS_Request_Mobile_Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Request_Mobile_Account.Marshal(b, m, deterministic)
}
func (dst *CS_Request_Mobile_Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Request_Mobile_Account.Merge(dst, src)
}
func (m *CS_Request_Mobile_Account) XXX_Size() int {
	return xxx_messageInfo_CS_Request_Mobile_Account.Size(m)
}
func (m *CS_Request_Mobile_Account) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Request_Mobile_Account.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Request_Mobile_Account proto.InternalMessageInfo

func (m *CS_Request_Mobile_Account) GetPhoneNumber() string {
	if m != nil && m.PhoneNumber != nil {
		return *m.PhoneNumber
	}
	return ""
}

func (m *CS_Request_Mobile_Account) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func (m *CS_Request_Mobile_Account) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *CS_Request_Mobile_Account) GetUiSpread() uint32 {
	if m != nil && m.UiSpread != nil {
		return *m.UiSpread
	}
	return 0
}

func (m *CS_Request_Mobile_Account) GetDevicestring() string {
	if m != nil && m.Devicestring != nil {
		return *m.Devicestring
	}
	return ""
}

func (m *CS_Request_Mobile_Account) GetPackageflag() string {
	if m != nil && m.Packageflag != nil {
		return *m.Packageflag
	}
	return ""
}

func (m *CS_Request_Mobile_Account) GetIDevice() int32 {
	if m != nil && m.IDevice != nil {
		return *m.IDevice
	}
	return 0
}

func (m *CS_Request_Mobile_Account) GetClientIp() string {
	if m != nil && m.ClientIp != nil {
		return *m.ClientIp
	}
	return ""
}

// RETURN_CREATE_ACCOUNT_RESULT_SUB_CMD                 = 8;   // 账号注册结果
type SC_Create_Account_Result struct {
	RetCode              *int32   `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Create_Account_Result) Reset()         { *m = SC_Create_Account_Result{} }
func (m *SC_Create_Account_Result) String() string { return proto.CompactTextString(m) }
func (*SC_Create_Account_Result) ProtoMessage()    {}
func (*SC_Create_Account_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{5}
}
func (m *SC_Create_Account_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Create_Account_Result.Unmarshal(m, b)
}
func (m *SC_Create_Account_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Create_Account_Result.Marshal(b, m, deterministic)
}
func (dst *SC_Create_Account_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Create_Account_Result.Merge(dst, src)
}
func (m *SC_Create_Account_Result) XXX_Size() int {
	return xxx_messageInfo_SC_Create_Account_Result.Size(m)
}
func (m *SC_Create_Account_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Create_Account_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Create_Account_Result proto.InternalMessageInfo

func (m *SC_Create_Account_Result) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// RETURN_MOBILE_TOKEN_RESULT_SUB_CMD                   = 9;   // 请求手机验证码发送结果
type SC_Request_Mobile_Token_Result struct {
	RetCode              *int32   `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Request_Mobile_Token_Result) Reset()         { *m = SC_Request_Mobile_Token_Result{} }
func (m *SC_Request_Mobile_Token_Result) String() string { return proto.CompactTextString(m) }
func (*SC_Request_Mobile_Token_Result) ProtoMessage()    {}
func (*SC_Request_Mobile_Token_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{6}
}
func (m *SC_Request_Mobile_Token_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Request_Mobile_Token_Result.Unmarshal(m, b)
}
func (m *SC_Request_Mobile_Token_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Request_Mobile_Token_Result.Marshal(b, m, deterministic)
}
func (dst *SC_Request_Mobile_Token_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Request_Mobile_Token_Result.Merge(dst, src)
}
func (m *SC_Request_Mobile_Token_Result) XXX_Size() int {
	return xxx_messageInfo_SC_Request_Mobile_Token_Result.Size(m)
}
func (m *SC_Request_Mobile_Token_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Request_Mobile_Token_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Request_Mobile_Token_Result proto.InternalMessageInfo

func (m *SC_Request_Mobile_Token_Result) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// REQUEST_RESET_PASSWD_TOKEN                           = 10;  // 请求重置密码的手机验证码
type CS_Request_Reset_Passwd_Token struct {
	Account              *string  `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	PhoneNumber          *string  `protobuf:"bytes,2,req,name=phoneNumber" json:"phoneNumber,omitempty"`
	Packageflag          *string  `protobuf:"bytes,3,opt,name=packageflag" json:"packageflag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Request_Reset_Passwd_Token) Reset()         { *m = CS_Request_Reset_Passwd_Token{} }
func (m *CS_Request_Reset_Passwd_Token) String() string { return proto.CompactTextString(m) }
func (*CS_Request_Reset_Passwd_Token) ProtoMessage()    {}
func (*CS_Request_Reset_Passwd_Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{7}
}
func (m *CS_Request_Reset_Passwd_Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Request_Reset_Passwd_Token.Unmarshal(m, b)
}
func (m *CS_Request_Reset_Passwd_Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Request_Reset_Passwd_Token.Marshal(b, m, deterministic)
}
func (dst *CS_Request_Reset_Passwd_Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Request_Reset_Passwd_Token.Merge(dst, src)
}
func (m *CS_Request_Reset_Passwd_Token) XXX_Size() int {
	return xxx_messageInfo_CS_Request_Reset_Passwd_Token.Size(m)
}
func (m *CS_Request_Reset_Passwd_Token) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Request_Reset_Passwd_Token.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Request_Reset_Passwd_Token proto.InternalMessageInfo

func (m *CS_Request_Reset_Passwd_Token) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *CS_Request_Reset_Passwd_Token) GetPhoneNumber() string {
	if m != nil && m.PhoneNumber != nil {
		return *m.PhoneNumber
	}
	return ""
}

func (m *CS_Request_Reset_Passwd_Token) GetPackageflag() string {
	if m != nil && m.Packageflag != nil {
		return *m.Packageflag
	}
	return ""
}

// RESET_NEW_PASSWD_SUB_CMD                             = 11;  // 请求重置密码
type CS_Request_Reset_Passwd struct {
	Account              *string  `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	PhoneNumber          *string  `protobuf:"bytes,2,req,name=phoneNumber" json:"phoneNumber,omitempty"`
	Passwd               *string  `protobuf:"bytes,3,req,name=passwd" json:"passwd,omitempty"`
	Token                *string  `protobuf:"bytes,4,req,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Request_Reset_Passwd) Reset()         { *m = CS_Request_Reset_Passwd{} }
func (m *CS_Request_Reset_Passwd) String() string { return proto.CompactTextString(m) }
func (*CS_Request_Reset_Passwd) ProtoMessage()    {}
func (*CS_Request_Reset_Passwd) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{8}
}
func (m *CS_Request_Reset_Passwd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Request_Reset_Passwd.Unmarshal(m, b)
}
func (m *CS_Request_Reset_Passwd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Request_Reset_Passwd.Marshal(b, m, deterministic)
}
func (dst *CS_Request_Reset_Passwd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Request_Reset_Passwd.Merge(dst, src)
}
func (m *CS_Request_Reset_Passwd) XXX_Size() int {
	return xxx_messageInfo_CS_Request_Reset_Passwd.Size(m)
}
func (m *CS_Request_Reset_Passwd) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Request_Reset_Passwd.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Request_Reset_Passwd proto.InternalMessageInfo

func (m *CS_Request_Reset_Passwd) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *CS_Request_Reset_Passwd) GetPhoneNumber() string {
	if m != nil && m.PhoneNumber != nil {
		return *m.PhoneNumber
	}
	return ""
}

func (m *CS_Request_Reset_Passwd) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func (m *CS_Request_Reset_Passwd) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// 	RETURN_RESET_PASSWD_TOKEN                            = 12;  // 请求重置密码的手机验证码结果
type SC_Return_Reset_Passwd_Token_Result struct {
	RetCode              *int32   `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Return_Reset_Passwd_Token_Result) Reset()         { *m = SC_Return_Reset_Passwd_Token_Result{} }
func (m *SC_Return_Reset_Passwd_Token_Result) String() string { return proto.CompactTextString(m) }
func (*SC_Return_Reset_Passwd_Token_Result) ProtoMessage()    {}
func (*SC_Return_Reset_Passwd_Token_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{9}
}
func (m *SC_Return_Reset_Passwd_Token_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Return_Reset_Passwd_Token_Result.Unmarshal(m, b)
}
func (m *SC_Return_Reset_Passwd_Token_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Return_Reset_Passwd_Token_Result.Marshal(b, m, deterministic)
}
func (dst *SC_Return_Reset_Passwd_Token_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Return_Reset_Passwd_Token_Result.Merge(dst, src)
}
func (m *SC_Return_Reset_Passwd_Token_Result) XXX_Size() int {
	return xxx_messageInfo_SC_Return_Reset_Passwd_Token_Result.Size(m)
}
func (m *SC_Return_Reset_Passwd_Token_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Return_Reset_Passwd_Token_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Return_Reset_Passwd_Token_Result proto.InternalMessageInfo

func (m *SC_Return_Reset_Passwd_Token_Result) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// 	RETURN_RESET_NEW_PASSWD_RESULT_SUB_CMD               = 13;  // 请求重置密码结果
type SC_Return_Reset_New_Passwd_Result struct {
	RetCode              *int32   `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Return_Reset_New_Passwd_Result) Reset()         { *m = SC_Return_Reset_New_Passwd_Result{} }
func (m *SC_Return_Reset_New_Passwd_Result) String() string { return proto.CompactTextString(m) }
func (*SC_Return_Reset_New_Passwd_Result) ProtoMessage()    {}
func (*SC_Return_Reset_New_Passwd_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{10}
}
func (m *SC_Return_Reset_New_Passwd_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Return_Reset_New_Passwd_Result.Unmarshal(m, b)
}
func (m *SC_Return_Reset_New_Passwd_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Return_Reset_New_Passwd_Result.Marshal(b, m, deterministic)
}
func (dst *SC_Return_Reset_New_Passwd_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Return_Reset_New_Passwd_Result.Merge(dst, src)
}
func (m *SC_Return_Reset_New_Passwd_Result) XXX_Size() int {
	return xxx_messageInfo_SC_Return_Reset_New_Passwd_Result.Size(m)
}
func (m *SC_Return_Reset_New_Passwd_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Return_Reset_New_Passwd_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Return_Reset_New_Passwd_Result proto.InternalMessageInfo

func (m *SC_Return_Reset_New_Passwd_Result) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// TECENT_REQUEST_LOGIN_SUB_CMD                         = 14;   // 腾讯账号登录
type CS_Tecent_Request_Login struct {
	TecentType           *int32   `protobuf:"varint,1,req,name=tecentType" json:"tecentType,omitempty"`
	Openid               *string  `protobuf:"bytes,2,req,name=openid" json:"openid,omitempty"`
	Token                *string  `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	DeviceString         *string  `protobuf:"bytes,4,req,name=deviceString" json:"deviceString,omitempty"`
	IDevice              *int32   `protobuf:"varint,5,req,name=iDevice" json:"iDevice,omitempty"`
	Packageflag          *string  `protobuf:"bytes,6,req,name=packageflag" json:"packageflag,omitempty"`
	ClientIp             *string  `protobuf:"bytes,7,opt,name=clientIp" json:"clientIp,omitempty"`
	LoginType            *int32   `protobuf:"varint,8,opt,name=loginType" json:"loginType,omitempty"`
	StrFace              *string  `protobuf:"bytes,9,opt,name=strFace" json:"strFace,omitempty"`
	StrNick              *string  `protobuf:"bytes,10,opt,name=strNick" json:"strNick,omitempty"`
	ISex                 *int32   `protobuf:"varint,11,opt,name=iSex" json:"iSex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Tecent_Request_Login) Reset()         { *m = CS_Tecent_Request_Login{} }
func (m *CS_Tecent_Request_Login) String() string { return proto.CompactTextString(m) }
func (*CS_Tecent_Request_Login) ProtoMessage()    {}
func (*CS_Tecent_Request_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{11}
}
func (m *CS_Tecent_Request_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Tecent_Request_Login.Unmarshal(m, b)
}
func (m *CS_Tecent_Request_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Tecent_Request_Login.Marshal(b, m, deterministic)
}
func (dst *CS_Tecent_Request_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Tecent_Request_Login.Merge(dst, src)
}
func (m *CS_Tecent_Request_Login) XXX_Size() int {
	return xxx_messageInfo_CS_Tecent_Request_Login.Size(m)
}
func (m *CS_Tecent_Request_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Tecent_Request_Login.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Tecent_Request_Login proto.InternalMessageInfo

func (m *CS_Tecent_Request_Login) GetTecentType() int32 {
	if m != nil && m.TecentType != nil {
		return *m.TecentType
	}
	return 0
}

func (m *CS_Tecent_Request_Login) GetOpenid() string {
	if m != nil && m.Openid != nil {
		return *m.Openid
	}
	return ""
}

func (m *CS_Tecent_Request_Login) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *CS_Tecent_Request_Login) GetDeviceString() string {
	if m != nil && m.DeviceString != nil {
		return *m.DeviceString
	}
	return ""
}

func (m *CS_Tecent_Request_Login) GetIDevice() int32 {
	if m != nil && m.IDevice != nil {
		return *m.IDevice
	}
	return 0
}

func (m *CS_Tecent_Request_Login) GetPackageflag() string {
	if m != nil && m.Packageflag != nil {
		return *m.Packageflag
	}
	return ""
}

func (m *CS_Tecent_Request_Login) GetClientIp() string {
	if m != nil && m.ClientIp != nil {
		return *m.ClientIp
	}
	return ""
}

func (m *CS_Tecent_Request_Login) GetLoginType() int32 {
	if m != nil && m.LoginType != nil {
		return *m.LoginType
	}
	return 0
}

func (m *CS_Tecent_Request_Login) GetStrFace() string {
	if m != nil && m.StrFace != nil {
		return *m.StrFace
	}
	return ""
}

func (m *CS_Tecent_Request_Login) GetStrNick() string {
	if m != nil && m.StrNick != nil {
		return *m.StrNick
	}
	return ""
}

func (m *CS_Tecent_Request_Login) GetISex() int32 {
	if m != nil && m.ISex != nil {
		return *m.ISex
	}
	return 0
}

// TECENT_LOGIN_RESULT_SUB_CMD                          = 15;   // 腾讯账号登录结果
type SC_Tecent_Lgin_Result struct {
	Retcode              *EnErrorCode `protobuf:"varint,1,req,name=retcode,enum=LoginSubCmd.EnErrorCode" json:"retcode,omitempty"`
	Account              *string      `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Token                *string      `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SC_Tecent_Lgin_Result) Reset()         { *m = SC_Tecent_Lgin_Result{} }
func (m *SC_Tecent_Lgin_Result) String() string { return proto.CompactTextString(m) }
func (*SC_Tecent_Lgin_Result) ProtoMessage()    {}
func (*SC_Tecent_Lgin_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{12}
}
func (m *SC_Tecent_Lgin_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Tecent_Lgin_Result.Unmarshal(m, b)
}
func (m *SC_Tecent_Lgin_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Tecent_Lgin_Result.Marshal(b, m, deterministic)
}
func (dst *SC_Tecent_Lgin_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Tecent_Lgin_Result.Merge(dst, src)
}
func (m *SC_Tecent_Lgin_Result) XXX_Size() int {
	return xxx_messageInfo_SC_Tecent_Lgin_Result.Size(m)
}
func (m *SC_Tecent_Lgin_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Tecent_Lgin_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Tecent_Lgin_Result proto.InternalMessageInfo

func (m *SC_Tecent_Lgin_Result) GetRetcode() EnErrorCode {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return EnErrorCode_ERROR_CODE_UNKNOWN
}

func (m *SC_Tecent_Lgin_Result) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *SC_Tecent_Lgin_Result) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// 更换设备登录 获取验证码
// REQUEST_CHANGE_DEVICE_TOKEN                          = 16;   // 设备变化 请求验证码
type CS_Request_Change_Device_Token struct {
	Account              *string  `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	PhoneNumber          *string  `protobuf:"bytes,2,req,name=phoneNumber" json:"phoneNumber,omitempty"`
	Packageflag          *string  `protobuf:"bytes,3,req,name=packageflag" json:"packageflag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Request_Change_Device_Token) Reset()         { *m = CS_Request_Change_Device_Token{} }
func (m *CS_Request_Change_Device_Token) String() string { return proto.CompactTextString(m) }
func (*CS_Request_Change_Device_Token) ProtoMessage()    {}
func (*CS_Request_Change_Device_Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{13}
}
func (m *CS_Request_Change_Device_Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Request_Change_Device_Token.Unmarshal(m, b)
}
func (m *CS_Request_Change_Device_Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Request_Change_Device_Token.Marshal(b, m, deterministic)
}
func (dst *CS_Request_Change_Device_Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Request_Change_Device_Token.Merge(dst, src)
}
func (m *CS_Request_Change_Device_Token) XXX_Size() int {
	return xxx_messageInfo_CS_Request_Change_Device_Token.Size(m)
}
func (m *CS_Request_Change_Device_Token) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Request_Change_Device_Token.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Request_Change_Device_Token proto.InternalMessageInfo

func (m *CS_Request_Change_Device_Token) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *CS_Request_Change_Device_Token) GetPhoneNumber() string {
	if m != nil && m.PhoneNumber != nil {
		return *m.PhoneNumber
	}
	return ""
}

func (m *CS_Request_Change_Device_Token) GetPackageflag() string {
	if m != nil && m.Packageflag != nil {
		return *m.Packageflag
	}
	return ""
}

// RETURN_CHANGE_DEVICE_TOKEN                           = 17;   // 设备变化 请求验结果
type SC_Return_Change_Device_Token struct {
	Retcode              *int32   `protobuf:"varint,1,req,name=retcode" json:"retcode,omitempty"`
	PhoneNumber          *string  `protobuf:"bytes,2,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Return_Change_Device_Token) Reset()         { *m = SC_Return_Change_Device_Token{} }
func (m *SC_Return_Change_Device_Token) String() string { return proto.CompactTextString(m) }
func (*SC_Return_Change_Device_Token) ProtoMessage()    {}
func (*SC_Return_Change_Device_Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_LoginSubCmd_c4600421c1ef001a, []int{14}
}
func (m *SC_Return_Change_Device_Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Return_Change_Device_Token.Unmarshal(m, b)
}
func (m *SC_Return_Change_Device_Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Return_Change_Device_Token.Marshal(b, m, deterministic)
}
func (dst *SC_Return_Change_Device_Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Return_Change_Device_Token.Merge(dst, src)
}
func (m *SC_Return_Change_Device_Token) XXX_Size() int {
	return xxx_messageInfo_SC_Return_Change_Device_Token.Size(m)
}
func (m *SC_Return_Change_Device_Token) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Return_Change_Device_Token.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Return_Change_Device_Token proto.InternalMessageInfo

func (m *SC_Return_Change_Device_Token) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func (m *SC_Return_Change_Device_Token) GetPhoneNumber() string {
	if m != nil && m.PhoneNumber != nil {
		return *m.PhoneNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequestInfo)(nil), "LoginSubCmd.LoginRequestInfo")
	proto.RegisterType((*LoginReturnInfo)(nil), "LoginSubCmd.LoginReturnInfo")
	proto.RegisterType((*LoginErrorCode)(nil), "LoginSubCmd.LoginErrorCode")
	proto.RegisterType((*CS_Visitor_Request_Login)(nil), "LoginSubCmd.CS_Visitor_Request_Login")
	proto.RegisterType((*CS_Request_Mobile_Account)(nil), "LoginSubCmd.CS_Request_Mobile_Account")
	proto.RegisterType((*SC_Create_Account_Result)(nil), "LoginSubCmd.SC_Create_Account_Result")
	proto.RegisterType((*SC_Request_Mobile_Token_Result)(nil), "LoginSubCmd.SC_Request_Mobile_Token_Result")
	proto.RegisterType((*CS_Request_Reset_Passwd_Token)(nil), "LoginSubCmd.CS_Request_Reset_Passwd_Token")
	proto.RegisterType((*CS_Request_Reset_Passwd)(nil), "LoginSubCmd.CS_Request_Reset_Passwd")
	proto.RegisterType((*SC_Return_Reset_Passwd_Token_Result)(nil), "LoginSubCmd.SC_Return_Reset_Passwd_Token_Result")
	proto.RegisterType((*SC_Return_Reset_New_Passwd_Result)(nil), "LoginSubCmd.SC_Return_Reset_New_Passwd_Result")
	proto.RegisterType((*CS_Tecent_Request_Login)(nil), "LoginSubCmd.CS_Tecent_Request_Login")
	proto.RegisterType((*SC_Tecent_Lgin_Result)(nil), "LoginSubCmd.SC_Tecent_Lgin_Result")
	proto.RegisterType((*CS_Request_Change_Device_Token)(nil), "LoginSubCmd.CS_Request_Change_Device_Token")
	proto.RegisterType((*SC_Return_Change_Device_Token)(nil), "LoginSubCmd.SC_Return_Change_Device_Token")
	proto.RegisterEnum("LoginSubCmd.EnSubCmdID", EnSubCmdID_name, EnSubCmdID_value)
	proto.RegisterEnum("LoginSubCmd.EnErrorCode", EnErrorCode_name, EnErrorCode_value)
}

func init() { proto.RegisterFile("LoginSubCmd.proto", fileDescriptor_LoginSubCmd_c4600421c1ef001a) }

var fileDescriptor_LoginSubCmd_c4600421c1ef001a = []byte{
	// 1034 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdb, 0x6e, 0xe2, 0x56,
	0x14, 0xad, 0x01, 0x43, 0xd8, 0x10, 0x70, 0xce, 0xdc, 0xce, 0x5c, 0x92, 0x32, 0x6e, 0x3b, 0x65,
	0x32, 0xd2, 0x48, 0xad, 0xaa, 0xbe, 0xf4, 0x89, 0xd8, 0x27, 0x53, 0x6b, 0xc0, 0xa6, 0xb6, 0x49,
	0x7a, 0x91, 0x6a, 0x19, 0x38, 0x21, 0x56, 0x88, 0x4d, 0x6d, 0xd3, 0xe9, 0x3c, 0xf5, 0x17, 0xaa,
	0xfe, 0x48, 0x7f, 0xa8, 0xfd, 0x97, 0xca, 0xc7, 0x97, 0x1c, 0x0c, 0xa8, 0x23, 0xf5, 0x05, 0x89,
	0xbd, 0xd7, 0xbe, 0xac, 0xb5, 0x97, 0x0f, 0x1c, 0x0d, 0x83, 0x85, 0xe7, 0x5b, 0xeb, 0xa9, 0x72,
	0x3b, 0x7f, 0xbd, 0x0a, 0x83, 0x38, 0x40, 0x2d, 0x2e, 0x24, 0xff, 0x2d, 0x80, 0xc4, 0xfe, 0x9b,
	0xf4, 0x97, 0x35, 0x8d, 0x62, 0xcd, 0xbf, 0x0a, 0x50, 0x17, 0x1a, 0xee, 0x6c, 0x16, 0xac, 0xfd,
	0x18, 0x0b, 0xbd, 0x4a, 0xbf, 0x89, 0x3a, 0x50, 0x5f, 0xb9, 0x51, 0xf4, 0x6e, 0x8e, 0x2b, 0xec,
	0x7f, 0x17, 0x1a, 0x9e, 0x4a, 0x7f, 0xf5, 0x66, 0x14, 0x57, 0x7b, 0x42, 0x5f, 0x44, 0x47, 0xd0,
	0xf4, 0xc6, 0x4b, 0x37, 0xbe, 0x0a, 0xc2, 0x5b, 0x5c, 0x63, 0x21, 0x09, 0x0e, 0xbc, 0x0b, 0x1a,
	0x46, 0x5e, 0xe0, 0x63, 0xb1, 0x27, 0xf4, 0x9b, 0x49, 0x64, 0xed, 0x59, 0xab, 0x90, 0xba, 0x73,
	0x5c, 0xef, 0x09, 0xfd, 0x43, 0x74, 0x0f, 0x5a, 0x2b, 0x77, 0x76, 0xe3, 0x2e, 0xe8, 0xd5, 0xd2,
	0x5d, 0xe0, 0x06, 0x83, 0xdd, 0x87, 0xf6, 0x9c, 0xf5, 0xb6, 0xe2, 0xd0, 0xf3, 0x17, 0xf8, 0x20,
	0x2f, 0x9e, 0x2d, 0x3d, 0xea, 0xc7, 0xda, 0x0a, 0xb7, 0x58, 0x24, 0x29, 0xbe, 0x0e, 0x7c, 0xaa,
	0xaf, 0x6f, 0xa7, 0x34, 0xc4, 0x6d, 0x16, 0x3c, 0x04, 0x31, 0x0e, 0x6e, 0xa8, 0x8f, 0x0f, 0x93,
	0xbf, 0xf2, 0xef, 0xd0, 0xcd, 0xd8, 0xc5, 0xeb, 0xd0, 0x67, 0xe4, 0x3a, 0x50, 0x5f, 0x47, 0x34,
	0xf4, 0x52, 0x2e, 0x62, 0x32, 0x6e, 0x19, 0x4c, 0xa7, 0xef, 0x07, 0xf3, 0x79, 0x48, 0xa3, 0x08,
	0x57, 0x19, 0xc3, 0x23, 0x68, 0xb2, 0xe8, 0x38, 0x08, 0x63, 0x5c, 0x63, 0xc0, 0xa2, 0xb5, 0x98,
	0x6b, 0x90, 0x8b, 0x54, 0x67, 0x81, 0x7b, 0xd0, 0xca, 0x02, 0xf6, 0xfb, 0x15, 0xc5, 0x8d, 0xa4,
	0x48, 0xfe, 0x06, 0x3a, 0x6c, 0x01, 0x12, 0x86, 0x41, 0xa8, 0x04, 0x73, 0x8a, 0x5e, 0x42, 0x23,
	0xa4, 0xf1, 0x2c, 0x98, 0x53, 0x26, 0x6e, 0xe7, 0x4b, 0xfc, 0x9a, 0xbf, 0x11, 0xbd, 0x83, 0xca,
	0xd7, 0x80, 0x15, 0xcb, 0xb9, 0xf0, 0x22, 0x2f, 0x0e, 0x42, 0x27, 0xbb, 0x90, 0xc3, 0xd0, 0x5b,
	0x2a, 0x09, 0xe5, 0xc3, 0xa4, 0xec, 0x4a, 0x0a, 0xa7, 0xe4, 0x78, 0x2d, 0x6b, 0x4c, 0xa7, 0xbf,
	0x04, 0x78, 0xac, 0x58, 0xc5, 0x88, 0x51, 0x30, 0xf5, 0x96, 0xd4, 0x19, 0xa4, 0x74, 0xca, 0x4a,
	0xef, 0xf6, 0x44, 0x21, 0x4f, 0x31, 0xa3, 0x38, 0x76, 0x8d, 0x1d, 0xbb, 0xd8, 0x38, 0x4a, 0x37,
	0x16, 0x8b, 0x2b, 0x72, 0x0b, 0xd6, 0x59, 0x90, 0xa3, 0xc1, 0x64, 0xdc, 0xd8, 0x98, 0xf9, 0x41,
	0x7e, 0x05, 0xd8, 0x52, 0x1c, 0x25, 0xa4, 0x6e, 0x5c, 0x2c, 0xea, 0x98, 0x34, 0x5a, 0x2f, 0xe3,
	0xa4, 0x3c, 0xa4, 0xb1, 0x92, 0x4b, 0x2c, 0xca, 0x5f, 0xc0, 0x89, 0xa5, 0x94, 0xd9, 0xd9, 0xc9,
	0xb6, 0x7b, 0x4b, 0x7e, 0x84, 0x63, 0x4e, 0x10, 0x93, 0x46, 0x34, 0x76, 0xc6, 0x8c, 0x6f, 0x5a,
	0xb8, 0xfd, 0x91, 0x94, 0x54, 0xaa, 0x14, 0xc1, 0x0d, 0xfd, 0x93, 0xdd, 0x7f, 0x86, 0x47, 0x7b,
	0x7a, 0x7f, 0x60, 0xd7, 0x3b, 0xed, 0xab, 0x9b, 0xda, 0x27, 0x4e, 0x6d, 0xca, 0x5f, 0xc3, 0x27,
	0x8c, 0x6e, 0xe2, 0xf9, 0x1d, 0xab, 0xef, 0xe5, 0xfc, 0x15, 0x3c, 0x2f, 0xd7, 0xe9, 0xf4, 0x5d,
	0x5e, 0xbb, 0xaf, 0xea, 0x1f, 0x81, 0xd1, 0xb1, 0xe9, 0x8c, 0xb2, 0x13, 0xf0, 0x2e, 0x45, 0x00,
	0x31, 0x8b, 0xb3, 0x4f, 0x82, 0xe1, 0x93, 0xe5, 0x83, 0x15, 0xf5, 0xbd, 0x3d, 0xc6, 0x29, 0x1b,
	0xbb, 0x56, 0x36, 0xb6, 0xb8, 0xcb, 0xd8, 0xf5, 0x2d, 0x63, 0xa7, 0x8f, 0x09, 0xfb, 0x8e, 0x17,
	0x9e, 0xcf, 0xe6, 0x1f, 0xb0, 0x87, 0xa9, 0x0b, 0x8d, 0x28, 0x0e, 0xcf, 0xdd, 0x19, 0xc5, 0xcd,
	0xdc, 0x6d, 0x51, 0x1c, 0xea, 0xde, 0xec, 0x06, 0x03, 0x0b, 0xb4, 0xa1, 0xe6, 0x59, 0xf4, 0x37,
	0xf6, 0xce, 0x88, 0xf2, 0x14, 0x1e, 0x58, 0x4a, 0x4e, 0x6f, 0xb8, 0xf0, 0x0a, 0xfd, 0x3e, 0xfc,
	0x4b, 0xe6, 0xcf, 0x5a, 0xd9, 0x7c, 0xa7, 0x52, 0x47, 0xfc, 0x04, 0x27, 0x9c, 0x23, 0x94, 0x6b,
	0xd7, 0x5f, 0x50, 0x27, 0xe5, 0xfb, 0xff, 0xec, 0x96, 0xd8, 0x81, 0xc0, 0xf1, 0xdd, 0x59, 0xf7,
	0xf4, 0xe6, 0x89, 0x88, 0xdb, 0xbd, 0x85, 0x7e, 0xf3, 0xf4, 0x8f, 0x1a, 0x00, 0xcd, 0xc8, 0x69,
	0x2a, 0x7a, 0x0c, 0x0f, 0x4c, 0xf2, 0xdd, 0x84, 0x58, 0xb6, 0x33, 0x34, 0xde, 0x68, 0xba, 0x63,
	0x4d, 0xce, 0x1c, 0x65, 0xa4, 0x4a, 0x15, 0xf4, 0x0c, 0xb0, 0x49, 0xec, 0x89, 0xa9, 0xa7, 0x19,
	0x4d, 0x3f, 0x37, 0x8a, 0x6c, 0x35, 0xc9, 0xa6, 0x05, 0xc4, 0x34, 0x0d, 0xd3, 0x51, 0x0c, 0x95,
	0x14, 0xd9, 0x1a, 0x7a, 0x0e, 0xc7, 0x17, 0x9a, 0xa5, 0xd9, 0x86, 0xe9, 0xec, 0x6e, 0x2f, 0xa2,
	0x97, 0xf0, 0x59, 0x9e, 0x52, 0x4c, 0x32, 0xb0, 0x89, 0x33, 0x32, 0xce, 0xb4, 0x21, 0x71, 0x06,
	0x8a, 0x62, 0x4c, 0x74, 0xbb, 0x80, 0x36, 0x50, 0x1f, 0x3e, 0xcd, 0x36, 0xc9, 0x90, 0x39, 0xc4,
	0x24, 0xd6, 0x64, 0x78, 0x87, 0x3c, 0x40, 0x2f, 0x40, 0xce, 0x90, 0x59, 0x33, 0xdb, 0x78, 0x4b,
	0xf4, 0x32, 0xae, 0x89, 0x4e, 0xe0, 0x49, 0x3e, 0xdc, 0x24, 0x16, 0xb1, 0x9d, 0xf1, 0xc0, 0xb2,
	0x2e, 0xd5, 0x14, 0x2e, 0x41, 0xca, 0x3d, 0x89, 0xeb, 0xe4, 0x32, 0xcf, 0xe5, 0xd5, 0x2d, 0x74,
	0x0c, 0x8f, 0xb3, 0x29, 0x3b, 0x8a, 0xdb, 0xe8, 0x14, 0x5e, 0x6c, 0xa4, 0xb9, 0x1e, 0xa5, 0x45,
	0x0e, 0x51, 0x0f, 0x9e, 0xd9, 0x44, 0x21, 0x8c, 0xcb, 0x2e, 0x9d, 0x3a, 0xe8, 0x63, 0x78, 0x9a,
	0x21, 0xd2, 0x4c, 0xa9, 0x45, 0x37, 0x01, 0x14, 0x42, 0x7e, 0x3b, 0xd0, 0xdf, 0x10, 0x47, 0x25,
	0x17, 0x9a, 0x92, 0x71, 0x97, 0xa4, 0x94, 0x6c, 0x2a, 0xdf, 0x8e, 0xfc, 0xd1, 0xe9, 0x9f, 0x55,
	0x68, 0xf1, 0x36, 0x7f, 0x08, 0x88, 0x3b, 0xea, 0x44, 0x7f, 0xab, 0x1b, 0x97, 0xba, 0xf4, 0x51,
	0x29, 0x9e, 0xdd, 0x40, 0x12, 0x10, 0x86, 0xfb, 0x5c, 0x5c, 0x37, 0x2c, 0x62, 0x26, 0xfd, 0xa5,
	0x4a, 0x29, 0x73, 0x6e, 0x98, 0x67, 0x9a, 0x3a, 0xb1, 0x88, 0x54, 0x2d, 0xf5, 0xd2, 0x0d, 0xf2,
	0xbd, 0x66, 0xd9, 0x52, 0x0d, 0x3d, 0x85, 0x47, 0xfc, 0x8c, 0xa1, 0x49, 0x06, 0xea, 0x0f, 0x69,
	0x52, 0x4c, 0xcc, 0xca, 0x25, 0x33, 0x2f, 0x10, 0xd3, 0x94, 0xea, 0xe8, 0x09, 0x3c, 0xe4, 0x8d,
	0x38, 0x26, 0xa6, 0xaa, 0xa9, 0x2c, 0xd7, 0x40, 0x32, 0x9c, 0x6c, 0xef, 0xed, 0xa4, 0xbf, 0x43,
	0x6d, 0xa4, 0xd9, 0xd2, 0x41, 0xa9, 0x3e, 0x13, 0xfc, 0x7c, 0xa0, 0x0d, 0xa5, 0x66, 0x62, 0x06,
	0x7e, 0x2c, 0xaf, 0xa1, 0x04, 0xe8, 0x15, 0x7c, 0xbe, 0x2f, 0x9b, 0xb9, 0xcf, 0xd6, 0x46, 0xc4,
	0x31, 0x26, 0xb6, 0xd4, 0x4a, 0x9c, 0xfc, 0x1f, 0x60, 0x96, 0x96, 0xda, 0xff, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x52, 0xb1, 0x12, 0xdd, 0xf3, 0x09, 0x00, 0x00,
}
