// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GateSubCmd.proto

package GateSubCmd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnSubCmdID int32

const (
	EnSubCmdID_LOGIN_GATE_SUB_CMD                EnSubCmdID = 1
	EnSubCmdID_LOGIN_GATE_RESULT_SUB_CMD         EnSubCmdID = 2
	EnSubCmdID_SERVER_SEND_TIME_SUB_CMD          EnSubCmdID = 3
	EnSubCmdID_REQUEST_USER_TIME_SUB_CMD         EnSubCmdID = 4
	EnSubCmdID_USER_TIME_TOSERVER_SUB_CMD        EnSubCmdID = 5
	EnSubCmdID_REQUEST_BIND_MOBILE_TOKEN         EnSubCmdID = 6
	EnSubCmdID_REQUEST_BIND_MOBILE               EnSubCmdID = 7
	EnSubCmdID_RETURN_BIND_MOBILE_TOKEN_RESULT   EnSubCmdID = 8
	EnSubCmdID_RETURN_BIND_MOBILE_RESULT         EnSubCmdID = 9
	EnSubCmdID_REQUEST_UPGRADE_ACCOUNT           EnSubCmdID = 10
	EnSubCmdID_RETURN_UPGRADE_RESULT             EnSubCmdID = 11
	EnSubCmdID_REQUEST_UNBIND_MOBILE_TOKEN       EnSubCmdID = 12
	EnSubCmdID_RETURN_UNBIND_MOBILE_TOKEN_RESULT EnSubCmdID = 13
	EnSubCmdID_REQUEST_UNBIND_MOBILE             EnSubCmdID = 14
	EnSubCmdID_RETURN_UNBIND_MOBILE_RESULT       EnSubCmdID = 15
	EnSubCmdID_VERIFY_ANDROIDANDPC               EnSubCmdID = 16
	EnSubCmdID_REQUEST_WXSERVER_SIGNATURE        EnSubCmdID = 17
	EnSubCmdID_RETURN_WXSERVER_SIGNATURE_RESULT  EnSubCmdID = 18
	EnSubCmdID_RETURN_LEAVE_GAME                 EnSubCmdID = 19
)

var EnSubCmdID_name = map[int32]string{
	1:  "LOGIN_GATE_SUB_CMD",
	2:  "LOGIN_GATE_RESULT_SUB_CMD",
	3:  "SERVER_SEND_TIME_SUB_CMD",
	4:  "REQUEST_USER_TIME_SUB_CMD",
	5:  "USER_TIME_TOSERVER_SUB_CMD",
	6:  "REQUEST_BIND_MOBILE_TOKEN",
	7:  "REQUEST_BIND_MOBILE",
	8:  "RETURN_BIND_MOBILE_TOKEN_RESULT",
	9:  "RETURN_BIND_MOBILE_RESULT",
	10: "REQUEST_UPGRADE_ACCOUNT",
	11: "RETURN_UPGRADE_RESULT",
	12: "REQUEST_UNBIND_MOBILE_TOKEN",
	13: "RETURN_UNBIND_MOBILE_TOKEN_RESULT",
	14: "REQUEST_UNBIND_MOBILE",
	15: "RETURN_UNBIND_MOBILE_RESULT",
	16: "VERIFY_ANDROIDANDPC",
	17: "REQUEST_WXSERVER_SIGNATURE",
	18: "RETURN_WXSERVER_SIGNATURE_RESULT",
	19: "RETURN_LEAVE_GAME",
}
var EnSubCmdID_value = map[string]int32{
	"LOGIN_GATE_SUB_CMD":                1,
	"LOGIN_GATE_RESULT_SUB_CMD":         2,
	"SERVER_SEND_TIME_SUB_CMD":          3,
	"REQUEST_USER_TIME_SUB_CMD":         4,
	"USER_TIME_TOSERVER_SUB_CMD":        5,
	"REQUEST_BIND_MOBILE_TOKEN":         6,
	"REQUEST_BIND_MOBILE":               7,
	"RETURN_BIND_MOBILE_TOKEN_RESULT":   8,
	"RETURN_BIND_MOBILE_RESULT":         9,
	"REQUEST_UPGRADE_ACCOUNT":           10,
	"RETURN_UPGRADE_RESULT":             11,
	"REQUEST_UNBIND_MOBILE_TOKEN":       12,
	"RETURN_UNBIND_MOBILE_TOKEN_RESULT": 13,
	"REQUEST_UNBIND_MOBILE":             14,
	"RETURN_UNBIND_MOBILE_RESULT":       15,
	"VERIFY_ANDROIDANDPC":               16,
	"REQUEST_WXSERVER_SIGNATURE":        17,
	"RETURN_WXSERVER_SIGNATURE_RESULT":  18,
	"RETURN_LEAVE_GAME":                 19,
}

func (x EnSubCmdID) Enum() *EnSubCmdID {
	p := new(EnSubCmdID)
	*p = x
	return p
}
func (x EnSubCmdID) String() string {
	return proto.EnumName(EnSubCmdID_name, int32(x))
}
func (x *EnSubCmdID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EnSubCmdID_value, data, "EnSubCmdID")
	if err != nil {
		return err
	}
	*x = EnSubCmdID(value)
	return nil
}
func (EnSubCmdID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{0}
}

// 登录错误代码枚举
type EnLoginGameCode int32

const (
	EnLoginGameCode_LG_Code_ok        EnLoginGameCode = 0
	EnLoginGameCode_LG_Code_Token     EnLoginGameCode = 1
	EnLoginGameCode_LG_Code_InGame    EnLoginGameCode = 2
	EnLoginGameCode_LG_Code_NoService EnLoginGameCode = 3
)

var EnLoginGameCode_name = map[int32]string{
	0: "LG_Code_ok",
	1: "LG_Code_Token",
	2: "LG_Code_InGame",
	3: "LG_Code_NoService",
}
var EnLoginGameCode_value = map[string]int32{
	"LG_Code_ok":        0,
	"LG_Code_Token":     1,
	"LG_Code_InGame":    2,
	"LG_Code_NoService": 3,
}

func (x EnLoginGameCode) Enum() *EnLoginGameCode {
	p := new(EnLoginGameCode)
	*p = x
	return p
}
func (x EnLoginGameCode) String() string {
	return proto.EnumName(EnLoginGameCode_name, int32(x))
}
func (x *EnLoginGameCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EnLoginGameCode_value, data, "EnLoginGameCode")
	if err != nil {
		return err
	}
	*x = EnLoginGameCode(value)
	return nil
}
func (EnLoginGameCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{1}
}

// LOGIN_GATE_SUB_CMD
type LoginGateInfo struct {
	Userid               *uint32  `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	Token                *string  `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
	IDevice              *int32   `protobuf:"varint,3,req,name=iDevice,def=1" json:"iDevice,omitempty"`
	IPlatform            *int32   `protobuf:"varint,4,req,name=iPlatform,def=1" json:"iPlatform,omitempty"`
	IVersion             *string  `protobuf:"bytes,5,req,name=iVersion,def=1.0.0.0" json:"iVersion,omitempty"`
	UiSpread             *uint32  `protobuf:"varint,6,opt,name=uiSpread" json:"uiSpread,omitempty"`
	Packageflag          *string  `protobuf:"bytes,7,opt,name=packageflag" json:"packageflag,omitempty"`
	Devicestring         *string  `protobuf:"bytes,8,opt,name=devicestring" json:"devicestring,omitempty"`
	UserName             *string  `protobuf:"bytes,9,opt,name=userName" json:"userName,omitempty"`
	Packmark             *string  `protobuf:"bytes,10,opt,name=packmark" json:"packmark,omitempty"`
	IpAddress            *string  `protobuf:"bytes,11,opt,name=ip_address" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginGateInfo) Reset()         { *m = LoginGateInfo{} }
func (m *LoginGateInfo) String() string { return proto.CompactTextString(m) }
func (*LoginGateInfo) ProtoMessage()    {}
func (*LoginGateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{0}
}
func (m *LoginGateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginGateInfo.Unmarshal(m, b)
}
func (m *LoginGateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginGateInfo.Marshal(b, m, deterministic)
}
func (dst *LoginGateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginGateInfo.Merge(dst, src)
}
func (m *LoginGateInfo) XXX_Size() int {
	return xxx_messageInfo_LoginGateInfo.Size(m)
}
func (m *LoginGateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginGateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginGateInfo proto.InternalMessageInfo

const Default_LoginGateInfo_IDevice int32 = 1
const Default_LoginGateInfo_IPlatform int32 = 1
const Default_LoginGateInfo_IVersion string = "1.0.0.0"

func (m *LoginGateInfo) GetUserid() uint32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *LoginGateInfo) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *LoginGateInfo) GetIDevice() int32 {
	if m != nil && m.IDevice != nil {
		return *m.IDevice
	}
	return Default_LoginGateInfo_IDevice
}

func (m *LoginGateInfo) GetIPlatform() int32 {
	if m != nil && m.IPlatform != nil {
		return *m.IPlatform
	}
	return Default_LoginGateInfo_IPlatform
}

func (m *LoginGateInfo) GetIVersion() string {
	if m != nil && m.IVersion != nil {
		return *m.IVersion
	}
	return Default_LoginGateInfo_IVersion
}

func (m *LoginGateInfo) GetUiSpread() uint32 {
	if m != nil && m.UiSpread != nil {
		return *m.UiSpread
	}
	return 0
}

func (m *LoginGateInfo) GetPackageflag() string {
	if m != nil && m.Packageflag != nil {
		return *m.Packageflag
	}
	return ""
}

func (m *LoginGateInfo) GetDevicestring() string {
	if m != nil && m.Devicestring != nil {
		return *m.Devicestring
	}
	return ""
}

func (m *LoginGateInfo) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *LoginGateInfo) GetPackmark() string {
	if m != nil && m.Packmark != nil {
		return *m.Packmark
	}
	return ""
}

func (m *LoginGateInfo) GetIpAddress() string {
	if m != nil && m.IpAddress != nil {
		return *m.IpAddress
	}
	return ""
}

// LOGIN_GATE_RESULT_SUB_CMD
type LoginGateResultInfo struct {
	Retcode              *int32   `protobuf:"varint,1,req,name=retcode,def=0" json:"retcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginGateResultInfo) Reset()         { *m = LoginGateResultInfo{} }
func (m *LoginGateResultInfo) String() string { return proto.CompactTextString(m) }
func (*LoginGateResultInfo) ProtoMessage()    {}
func (*LoginGateResultInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{1}
}
func (m *LoginGateResultInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginGateResultInfo.Unmarshal(m, b)
}
func (m *LoginGateResultInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginGateResultInfo.Marshal(b, m, deterministic)
}
func (dst *LoginGateResultInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginGateResultInfo.Merge(dst, src)
}
func (m *LoginGateResultInfo) XXX_Size() int {
	return xxx_messageInfo_LoginGateResultInfo.Size(m)
}
func (m *LoginGateResultInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginGateResultInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoginGateResultInfo proto.InternalMessageInfo

const Default_LoginGateResultInfo_Retcode int32 = 0

func (m *LoginGateResultInfo) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return Default_LoginGateResultInfo_Retcode
}

// SERVER_SEND_TIME_SUB_CMD
type ServerTimeSendClient struct {
	GameTime             *int64   `protobuf:"varint,1,req,name=gameTime" json:"gameTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerTimeSendClient) Reset()         { *m = ServerTimeSendClient{} }
func (m *ServerTimeSendClient) String() string { return proto.CompactTextString(m) }
func (*ServerTimeSendClient) ProtoMessage()    {}
func (*ServerTimeSendClient) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{2}
}
func (m *ServerTimeSendClient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerTimeSendClient.Unmarshal(m, b)
}
func (m *ServerTimeSendClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerTimeSendClient.Marshal(b, m, deterministic)
}
func (dst *ServerTimeSendClient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerTimeSendClient.Merge(dst, src)
}
func (m *ServerTimeSendClient) XXX_Size() int {
	return xxx_messageInfo_ServerTimeSendClient.Size(m)
}
func (m *ServerTimeSendClient) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerTimeSendClient.DiscardUnknown(m)
}

var xxx_messageInfo_ServerTimeSendClient proto.InternalMessageInfo

func (m *ServerTimeSendClient) GetGameTime() int64 {
	if m != nil && m.GameTime != nil {
		return *m.GameTime
	}
	return 0
}

// USER_TIME_TOSERVER_SUB_CMD
type UserTimeSendServer struct {
	GameTime             *int64   `protobuf:"varint,1,req,name=gameTime" json:"gameTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTimeSendServer) Reset()         { *m = UserTimeSendServer{} }
func (m *UserTimeSendServer) String() string { return proto.CompactTextString(m) }
func (*UserTimeSendServer) ProtoMessage()    {}
func (*UserTimeSendServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{3}
}
func (m *UserTimeSendServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTimeSendServer.Unmarshal(m, b)
}
func (m *UserTimeSendServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTimeSendServer.Marshal(b, m, deterministic)
}
func (dst *UserTimeSendServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTimeSendServer.Merge(dst, src)
}
func (m *UserTimeSendServer) XXX_Size() int {
	return xxx_messageInfo_UserTimeSendServer.Size(m)
}
func (m *UserTimeSendServer) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTimeSendServer.DiscardUnknown(m)
}

var xxx_messageInfo_UserTimeSendServer proto.InternalMessageInfo

func (m *UserTimeSendServer) GetGameTime() int64 {
	if m != nil && m.GameTime != nil {
		return *m.GameTime
	}
	return 0
}

// REQUEST_BIND_MOBILE_TOKEN                            = 6;       //请求绑定手机时候的验证码
type CS_Request_Mobile_Token struct {
	Account              *string  `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	PhoneNumber          *string  `protobuf:"bytes,2,req,name=phoneNumber" json:"phoneNumber,omitempty"`
	Packageflag          *string  `protobuf:"bytes,3,opt,name=packageflag" json:"packageflag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Request_Mobile_Token) Reset()         { *m = CS_Request_Mobile_Token{} }
func (m *CS_Request_Mobile_Token) String() string { return proto.CompactTextString(m) }
func (*CS_Request_Mobile_Token) ProtoMessage()    {}
func (*CS_Request_Mobile_Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{4}
}
func (m *CS_Request_Mobile_Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Request_Mobile_Token.Unmarshal(m, b)
}
func (m *CS_Request_Mobile_Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Request_Mobile_Token.Marshal(b, m, deterministic)
}
func (dst *CS_Request_Mobile_Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Request_Mobile_Token.Merge(dst, src)
}
func (m *CS_Request_Mobile_Token) XXX_Size() int {
	return xxx_messageInfo_CS_Request_Mobile_Token.Size(m)
}
func (m *CS_Request_Mobile_Token) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Request_Mobile_Token.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Request_Mobile_Token proto.InternalMessageInfo

func (m *CS_Request_Mobile_Token) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *CS_Request_Mobile_Token) GetPhoneNumber() string {
	if m != nil && m.PhoneNumber != nil {
		return *m.PhoneNumber
	}
	return ""
}

func (m *CS_Request_Mobile_Token) GetPackageflag() string {
	if m != nil && m.Packageflag != nil {
		return *m.Packageflag
	}
	return ""
}

// REQUEST_BIND_MOBILE                                  = 7;       //请求绑定手机
type CS_Request_Bind_Mobile struct {
	Account              *string  `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Phonenumber          *string  `protobuf:"bytes,2,req,name=phonenumber" json:"phonenumber,omitempty"`
	Token                *string  `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Request_Bind_Mobile) Reset()         { *m = CS_Request_Bind_Mobile{} }
func (m *CS_Request_Bind_Mobile) String() string { return proto.CompactTextString(m) }
func (*CS_Request_Bind_Mobile) ProtoMessage()    {}
func (*CS_Request_Bind_Mobile) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{5}
}
func (m *CS_Request_Bind_Mobile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Request_Bind_Mobile.Unmarshal(m, b)
}
func (m *CS_Request_Bind_Mobile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Request_Bind_Mobile.Marshal(b, m, deterministic)
}
func (dst *CS_Request_Bind_Mobile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Request_Bind_Mobile.Merge(dst, src)
}
func (m *CS_Request_Bind_Mobile) XXX_Size() int {
	return xxx_messageInfo_CS_Request_Bind_Mobile.Size(m)
}
func (m *CS_Request_Bind_Mobile) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Request_Bind_Mobile.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Request_Bind_Mobile proto.InternalMessageInfo

func (m *CS_Request_Bind_Mobile) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *CS_Request_Bind_Mobile) GetPhonenumber() string {
	if m != nil && m.Phonenumber != nil {
		return *m.Phonenumber
	}
	return ""
}

func (m *CS_Request_Bind_Mobile) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// 	RETURN_BIND_MOBILE_TOKEN_RESULT                      = 8;       //请求绑定手机验证码结果
type SC_Return_Bind_Mobile_Token_Result struct {
	RetCode              *int32   `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Return_Bind_Mobile_Token_Result) Reset()         { *m = SC_Return_Bind_Mobile_Token_Result{} }
func (m *SC_Return_Bind_Mobile_Token_Result) String() string { return proto.CompactTextString(m) }
func (*SC_Return_Bind_Mobile_Token_Result) ProtoMessage()    {}
func (*SC_Return_Bind_Mobile_Token_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{6}
}
func (m *SC_Return_Bind_Mobile_Token_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Return_Bind_Mobile_Token_Result.Unmarshal(m, b)
}
func (m *SC_Return_Bind_Mobile_Token_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Return_Bind_Mobile_Token_Result.Marshal(b, m, deterministic)
}
func (dst *SC_Return_Bind_Mobile_Token_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Return_Bind_Mobile_Token_Result.Merge(dst, src)
}
func (m *SC_Return_Bind_Mobile_Token_Result) XXX_Size() int {
	return xxx_messageInfo_SC_Return_Bind_Mobile_Token_Result.Size(m)
}
func (m *SC_Return_Bind_Mobile_Token_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Return_Bind_Mobile_Token_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Return_Bind_Mobile_Token_Result proto.InternalMessageInfo

func (m *SC_Return_Bind_Mobile_Token_Result) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// 	RETURN_BIND_MOBILE_RESULT                            = 9;       //绑定结果
type SC_Return_Bind_Mobile_Result struct {
	RetCode              *int32   `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Return_Bind_Mobile_Result) Reset()         { *m = SC_Return_Bind_Mobile_Result{} }
func (m *SC_Return_Bind_Mobile_Result) String() string { return proto.CompactTextString(m) }
func (*SC_Return_Bind_Mobile_Result) ProtoMessage()    {}
func (*SC_Return_Bind_Mobile_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{7}
}
func (m *SC_Return_Bind_Mobile_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Return_Bind_Mobile_Result.Unmarshal(m, b)
}
func (m *SC_Return_Bind_Mobile_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Return_Bind_Mobile_Result.Marshal(b, m, deterministic)
}
func (dst *SC_Return_Bind_Mobile_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Return_Bind_Mobile_Result.Merge(dst, src)
}
func (m *SC_Return_Bind_Mobile_Result) XXX_Size() int {
	return xxx_messageInfo_SC_Return_Bind_Mobile_Result.Size(m)
}
func (m *SC_Return_Bind_Mobile_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Return_Bind_Mobile_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Return_Bind_Mobile_Result proto.InternalMessageInfo

func (m *SC_Return_Bind_Mobile_Result) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// REQUEST_UPGRADE_ACCOUNT                              = 10;       //客户端请求账号升级
type CS_Request_Upgrade_Account struct {
	Oldaccount           *string  `protobuf:"bytes,1,req,name=oldaccount" json:"oldaccount,omitempty"`
	Newaccount           *string  `protobuf:"bytes,2,req,name=newaccount" json:"newaccount,omitempty"`
	Passwd               *string  `protobuf:"bytes,3,req,name=passwd" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Request_Upgrade_Account) Reset()         { *m = CS_Request_Upgrade_Account{} }
func (m *CS_Request_Upgrade_Account) String() string { return proto.CompactTextString(m) }
func (*CS_Request_Upgrade_Account) ProtoMessage()    {}
func (*CS_Request_Upgrade_Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{8}
}
func (m *CS_Request_Upgrade_Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Request_Upgrade_Account.Unmarshal(m, b)
}
func (m *CS_Request_Upgrade_Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Request_Upgrade_Account.Marshal(b, m, deterministic)
}
func (dst *CS_Request_Upgrade_Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Request_Upgrade_Account.Merge(dst, src)
}
func (m *CS_Request_Upgrade_Account) XXX_Size() int {
	return xxx_messageInfo_CS_Request_Upgrade_Account.Size(m)
}
func (m *CS_Request_Upgrade_Account) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Request_Upgrade_Account.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Request_Upgrade_Account proto.InternalMessageInfo

func (m *CS_Request_Upgrade_Account) GetOldaccount() string {
	if m != nil && m.Oldaccount != nil {
		return *m.Oldaccount
	}
	return ""
}

func (m *CS_Request_Upgrade_Account) GetNewaccount() string {
	if m != nil && m.Newaccount != nil {
		return *m.Newaccount
	}
	return ""
}

func (m *CS_Request_Upgrade_Account) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

// 	RETURN_UPGRADE_RESULT                                = 11;       //客户端请求账号升级结果
type SC_Return_Upgrade_Account_Result struct {
	RetCode              *int32   `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Return_Upgrade_Account_Result) Reset()         { *m = SC_Return_Upgrade_Account_Result{} }
func (m *SC_Return_Upgrade_Account_Result) String() string { return proto.CompactTextString(m) }
func (*SC_Return_Upgrade_Account_Result) ProtoMessage()    {}
func (*SC_Return_Upgrade_Account_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{9}
}
func (m *SC_Return_Upgrade_Account_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Return_Upgrade_Account_Result.Unmarshal(m, b)
}
func (m *SC_Return_Upgrade_Account_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Return_Upgrade_Account_Result.Marshal(b, m, deterministic)
}
func (dst *SC_Return_Upgrade_Account_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Return_Upgrade_Account_Result.Merge(dst, src)
}
func (m *SC_Return_Upgrade_Account_Result) XXX_Size() int {
	return xxx_messageInfo_SC_Return_Upgrade_Account_Result.Size(m)
}
func (m *SC_Return_Upgrade_Account_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Return_Upgrade_Account_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Return_Upgrade_Account_Result proto.InternalMessageInfo

func (m *SC_Return_Upgrade_Account_Result) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// REQUEST_UNBIND_MOBILE_TOKEN                          = 12;       //请求解绑定手机时候的验证码
type CS_Request_UnBind_Mobile_Token struct {
	Account              *string  `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	PhoneNumber          *string  `protobuf:"bytes,2,req,name=phoneNumber" json:"phoneNumber,omitempty"`
	Packageflag          *string  `protobuf:"bytes,3,opt,name=packageflag" json:"packageflag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Request_UnBind_Mobile_Token) Reset()         { *m = CS_Request_UnBind_Mobile_Token{} }
func (m *CS_Request_UnBind_Mobile_Token) String() string { return proto.CompactTextString(m) }
func (*CS_Request_UnBind_Mobile_Token) ProtoMessage()    {}
func (*CS_Request_UnBind_Mobile_Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{10}
}
func (m *CS_Request_UnBind_Mobile_Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Request_UnBind_Mobile_Token.Unmarshal(m, b)
}
func (m *CS_Request_UnBind_Mobile_Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Request_UnBind_Mobile_Token.Marshal(b, m, deterministic)
}
func (dst *CS_Request_UnBind_Mobile_Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Request_UnBind_Mobile_Token.Merge(dst, src)
}
func (m *CS_Request_UnBind_Mobile_Token) XXX_Size() int {
	return xxx_messageInfo_CS_Request_UnBind_Mobile_Token.Size(m)
}
func (m *CS_Request_UnBind_Mobile_Token) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Request_UnBind_Mobile_Token.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Request_UnBind_Mobile_Token proto.InternalMessageInfo

func (m *CS_Request_UnBind_Mobile_Token) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *CS_Request_UnBind_Mobile_Token) GetPhoneNumber() string {
	if m != nil && m.PhoneNumber != nil {
		return *m.PhoneNumber
	}
	return ""
}

func (m *CS_Request_UnBind_Mobile_Token) GetPackageflag() string {
	if m != nil && m.Packageflag != nil {
		return *m.Packageflag
	}
	return ""
}

// RETURN_UNBIND_MOBILE_TOKEN_RESULT                    = 13;       //请求解绑手机验证码结果
type SC_Return_UnBind_Mobile_Token_Result struct {
	RetCode              *int32   `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Return_UnBind_Mobile_Token_Result) Reset()         { *m = SC_Return_UnBind_Mobile_Token_Result{} }
func (m *SC_Return_UnBind_Mobile_Token_Result) String() string { return proto.CompactTextString(m) }
func (*SC_Return_UnBind_Mobile_Token_Result) ProtoMessage()    {}
func (*SC_Return_UnBind_Mobile_Token_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{11}
}
func (m *SC_Return_UnBind_Mobile_Token_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Return_UnBind_Mobile_Token_Result.Unmarshal(m, b)
}
func (m *SC_Return_UnBind_Mobile_Token_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Return_UnBind_Mobile_Token_Result.Marshal(b, m, deterministic)
}
func (dst *SC_Return_UnBind_Mobile_Token_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Return_UnBind_Mobile_Token_Result.Merge(dst, src)
}
func (m *SC_Return_UnBind_Mobile_Token_Result) XXX_Size() int {
	return xxx_messageInfo_SC_Return_UnBind_Mobile_Token_Result.Size(m)
}
func (m *SC_Return_UnBind_Mobile_Token_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Return_UnBind_Mobile_Token_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Return_UnBind_Mobile_Token_Result proto.InternalMessageInfo

func (m *SC_Return_UnBind_Mobile_Token_Result) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// REQUEST_UNBIND_MOBILE                                = 14;       //请求解绑定手机
type CS_Request_UnBind_Mobile struct {
	Account              *string  `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Phonenumber          *string  `protobuf:"bytes,2,req,name=phonenumber" json:"phonenumber,omitempty"`
	Token                *string  `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Request_UnBind_Mobile) Reset()         { *m = CS_Request_UnBind_Mobile{} }
func (m *CS_Request_UnBind_Mobile) String() string { return proto.CompactTextString(m) }
func (*CS_Request_UnBind_Mobile) ProtoMessage()    {}
func (*CS_Request_UnBind_Mobile) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{12}
}
func (m *CS_Request_UnBind_Mobile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Request_UnBind_Mobile.Unmarshal(m, b)
}
func (m *CS_Request_UnBind_Mobile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Request_UnBind_Mobile.Marshal(b, m, deterministic)
}
func (dst *CS_Request_UnBind_Mobile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Request_UnBind_Mobile.Merge(dst, src)
}
func (m *CS_Request_UnBind_Mobile) XXX_Size() int {
	return xxx_messageInfo_CS_Request_UnBind_Mobile.Size(m)
}
func (m *CS_Request_UnBind_Mobile) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Request_UnBind_Mobile.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Request_UnBind_Mobile proto.InternalMessageInfo

func (m *CS_Request_UnBind_Mobile) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *CS_Request_UnBind_Mobile) GetPhonenumber() string {
	if m != nil && m.Phonenumber != nil {
		return *m.Phonenumber
	}
	return ""
}

func (m *CS_Request_UnBind_Mobile) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// RETURN_UNBIND_MOBILE_RESULT
type SC_Return_UnBind_Mobile_Result struct {
	RetCode              *int32   `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Return_UnBind_Mobile_Result) Reset()         { *m = SC_Return_UnBind_Mobile_Result{} }
func (m *SC_Return_UnBind_Mobile_Result) String() string { return proto.CompactTextString(m) }
func (*SC_Return_UnBind_Mobile_Result) ProtoMessage()    {}
func (*SC_Return_UnBind_Mobile_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{13}
}
func (m *SC_Return_UnBind_Mobile_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Return_UnBind_Mobile_Result.Unmarshal(m, b)
}
func (m *SC_Return_UnBind_Mobile_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Return_UnBind_Mobile_Result.Marshal(b, m, deterministic)
}
func (dst *SC_Return_UnBind_Mobile_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Return_UnBind_Mobile_Result.Merge(dst, src)
}
func (m *SC_Return_UnBind_Mobile_Result) XXX_Size() int {
	return xxx_messageInfo_SC_Return_UnBind_Mobile_Result.Size(m)
}
func (m *SC_Return_UnBind_Mobile_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Return_UnBind_Mobile_Result.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Return_UnBind_Mobile_Result proto.InternalMessageInfo

func (m *SC_Return_UnBind_Mobile_Result) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

// VERIFY_ANDROIDANDPC                                  = 16;      //安卓和PC验证
type Verify_AndroidAndPC struct {
	Platform             *string  `protobuf:"bytes,1,req,name=platform" json:"platform,omitempty"`
	Verifycode           *string  `protobuf:"bytes,2,req,name=verifycode" json:"verifycode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Verify_AndroidAndPC) Reset()         { *m = Verify_AndroidAndPC{} }
func (m *Verify_AndroidAndPC) String() string { return proto.CompactTextString(m) }
func (*Verify_AndroidAndPC) ProtoMessage()    {}
func (*Verify_AndroidAndPC) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{14}
}
func (m *Verify_AndroidAndPC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Verify_AndroidAndPC.Unmarshal(m, b)
}
func (m *Verify_AndroidAndPC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Verify_AndroidAndPC.Marshal(b, m, deterministic)
}
func (dst *Verify_AndroidAndPC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verify_AndroidAndPC.Merge(dst, src)
}
func (m *Verify_AndroidAndPC) XXX_Size() int {
	return xxx_messageInfo_Verify_AndroidAndPC.Size(m)
}
func (m *Verify_AndroidAndPC) XXX_DiscardUnknown() {
	xxx_messageInfo_Verify_AndroidAndPC.DiscardUnknown(m)
}

var xxx_messageInfo_Verify_AndroidAndPC proto.InternalMessageInfo

func (m *Verify_AndroidAndPC) GetPlatform() string {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return ""
}

func (m *Verify_AndroidAndPC) GetVerifycode() string {
	if m != nil && m.Verifycode != nil {
		return *m.Verifycode
	}
	return ""
}

// REQUEST_WXSERVER_SIGNATURE                           = 17;       //请求威信服务签名
type RequestWxServerSignature struct {
	Uri                  *string  `protobuf:"bytes,1,req,name=uri" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestWxServerSignature) Reset()         { *m = RequestWxServerSignature{} }
func (m *RequestWxServerSignature) String() string { return proto.CompactTextString(m) }
func (*RequestWxServerSignature) ProtoMessage()    {}
func (*RequestWxServerSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{15}
}
func (m *RequestWxServerSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestWxServerSignature.Unmarshal(m, b)
}
func (m *RequestWxServerSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestWxServerSignature.Marshal(b, m, deterministic)
}
func (dst *RequestWxServerSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestWxServerSignature.Merge(dst, src)
}
func (m *RequestWxServerSignature) XXX_Size() int {
	return xxx_messageInfo_RequestWxServerSignature.Size(m)
}
func (m *RequestWxServerSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestWxServerSignature.DiscardUnknown(m)
}

var xxx_messageInfo_RequestWxServerSignature proto.InternalMessageInfo

func (m *RequestWxServerSignature) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

// RETURN_WXSERVER_SIGNATURE_RESULT                     = 18;       //请求威信服务签名
type ReturnWxServerSignatureResult struct {
	RetCode              *int32   `protobuf:"varint,1,req,name=retCode" json:"retCode,omitempty"`
	Noncestr             *string  `protobuf:"bytes,2,opt,name=noncestr" json:"noncestr,omitempty"`
	Timestamp            *int64   `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Signature            *string  `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnWxServerSignatureResult) Reset()         { *m = ReturnWxServerSignatureResult{} }
func (m *ReturnWxServerSignatureResult) String() string { return proto.CompactTextString(m) }
func (*ReturnWxServerSignatureResult) ProtoMessage()    {}
func (*ReturnWxServerSignatureResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{16}
}
func (m *ReturnWxServerSignatureResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnWxServerSignatureResult.Unmarshal(m, b)
}
func (m *ReturnWxServerSignatureResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnWxServerSignatureResult.Marshal(b, m, deterministic)
}
func (dst *ReturnWxServerSignatureResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnWxServerSignatureResult.Merge(dst, src)
}
func (m *ReturnWxServerSignatureResult) XXX_Size() int {
	return xxx_messageInfo_ReturnWxServerSignatureResult.Size(m)
}
func (m *ReturnWxServerSignatureResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnWxServerSignatureResult.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnWxServerSignatureResult proto.InternalMessageInfo

func (m *ReturnWxServerSignatureResult) GetRetCode() int32 {
	if m != nil && m.RetCode != nil {
		return *m.RetCode
	}
	return 0
}

func (m *ReturnWxServerSignatureResult) GetNoncestr() string {
	if m != nil && m.Noncestr != nil {
		return *m.Noncestr
	}
	return ""
}

func (m *ReturnWxServerSignatureResult) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ReturnWxServerSignatureResult) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

// RETURN_LEAVE_GAME 									= 19;      //离开游戏，不再重新连接，进入登录界面
type ReturnLeaveGame struct {
	Retcode              *int32   `protobuf:"varint,1,req,name=retcode" json:"retcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnLeaveGame) Reset()         { *m = ReturnLeaveGame{} }
func (m *ReturnLeaveGame) String() string { return proto.CompactTextString(m) }
func (*ReturnLeaveGame) ProtoMessage()    {}
func (*ReturnLeaveGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_GateSubCmd_5c61652e2d8213e6, []int{17}
}
func (m *ReturnLeaveGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnLeaveGame.Unmarshal(m, b)
}
func (m *ReturnLeaveGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnLeaveGame.Marshal(b, m, deterministic)
}
func (dst *ReturnLeaveGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnLeaveGame.Merge(dst, src)
}
func (m *ReturnLeaveGame) XXX_Size() int {
	return xxx_messageInfo_ReturnLeaveGame.Size(m)
}
func (m *ReturnLeaveGame) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnLeaveGame.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnLeaveGame proto.InternalMessageInfo

func (m *ReturnLeaveGame) GetRetcode() int32 {
	if m != nil && m.Retcode != nil {
		return *m.Retcode
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginGateInfo)(nil), "GateSubCmd.LoginGateInfo")
	proto.RegisterType((*LoginGateResultInfo)(nil), "GateSubCmd.LoginGateResultInfo")
	proto.RegisterType((*ServerTimeSendClient)(nil), "GateSubCmd.ServerTimeSendClient")
	proto.RegisterType((*UserTimeSendServer)(nil), "GateSubCmd.UserTimeSendServer")
	proto.RegisterType((*CS_Request_Mobile_Token)(nil), "GateSubCmd.CS_Request_Mobile_Token")
	proto.RegisterType((*CS_Request_Bind_Mobile)(nil), "GateSubCmd.CS_Request_Bind_Mobile")
	proto.RegisterType((*SC_Return_Bind_Mobile_Token_Result)(nil), "GateSubCmd.SC_Return_Bind_Mobile_Token_Result")
	proto.RegisterType((*SC_Return_Bind_Mobile_Result)(nil), "GateSubCmd.SC_Return_Bind_Mobile_Result")
	proto.RegisterType((*CS_Request_Upgrade_Account)(nil), "GateSubCmd.CS_Request_Upgrade_Account")
	proto.RegisterType((*SC_Return_Upgrade_Account_Result)(nil), "GateSubCmd.SC_Return_Upgrade_Account_Result")
	proto.RegisterType((*CS_Request_UnBind_Mobile_Token)(nil), "GateSubCmd.CS_Request_UnBind_Mobile_Token")
	proto.RegisterType((*SC_Return_UnBind_Mobile_Token_Result)(nil), "GateSubCmd.SC_Return_UnBind_Mobile_Token_Result")
	proto.RegisterType((*CS_Request_UnBind_Mobile)(nil), "GateSubCmd.CS_Request_UnBind_Mobile")
	proto.RegisterType((*SC_Return_UnBind_Mobile_Result)(nil), "GateSubCmd.SC_Return_UnBind_Mobile_Result")
	proto.RegisterType((*Verify_AndroidAndPC)(nil), "GateSubCmd.Verify_AndroidAndPC")
	proto.RegisterType((*RequestWxServerSignature)(nil), "GateSubCmd.RequestWxServerSignature")
	proto.RegisterType((*ReturnWxServerSignatureResult)(nil), "GateSubCmd.ReturnWxServerSignatureResult")
	proto.RegisterType((*ReturnLeaveGame)(nil), "GateSubCmd.ReturnLeaveGame")
	proto.RegisterEnum("GateSubCmd.EnSubCmdID", EnSubCmdID_name, EnSubCmdID_value)
	proto.RegisterEnum("GateSubCmd.EnLoginGameCode", EnLoginGameCode_name, EnLoginGameCode_value)
}

func init() { proto.RegisterFile("GateSubCmd.proto", fileDescriptor_GateSubCmd_5c61652e2d8213e6) }

var fileDescriptor_GateSubCmd_5c61652e2d8213e6 = []byte{
	// 907 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5f, 0x6f, 0xe2, 0xd6,
	0x13, 0xfd, 0x01, 0x49, 0x08, 0x93, 0x85, 0x38, 0x97, 0xec, 0xc6, 0xd9, 0x3f, 0x59, 0x7e, 0xee,
	0xb6, 0xa5, 0xfb, 0xb0, 0xdd, 0xa8, 0xaa, 0x2a, 0xa5, 0x4f, 0x8e, 0x71, 0x91, 0x55, 0x30, 0xa9,
	0x6d, 0xd8, 0x56, 0x7d, 0xb8, 0x72, 0xf0, 0x84, 0xbd, 0x0a, 0xbe, 0xa6, 0xd7, 0x76, 0xb6, 0xfd,
	0x92, 0xfd, 0x1c, 0xfd, 0x18, 0xd5, 0xf5, 0x1f, 0x60, 0x17, 0x90, 0xaa, 0x56, 0x79, 0x09, 0x67,
	0xe6, 0x9c, 0x39, 0x33, 0xc3, 0x5c, 0x40, 0xe9, 0xfb, 0x09, 0xba, 0xe9, 0xad, 0x11, 0x06, 0x6f,
	0x16, 0x22, 0x4a, 0x22, 0x02, 0x2b, 0x44, 0xfb, 0xab, 0x02, 0xcd, 0x41, 0x34, 0x63, 0x5c, 0x62,
	0x16, 0xbf, 0x8b, 0x48, 0x0b, 0x0e, 0xd2, 0x18, 0x05, 0x0b, 0xd4, 0x4a, 0xa7, 0xda, 0x6d, 0x92,
	0x26, 0xec, 0x27, 0xd1, 0x3d, 0x72, 0xb5, 0xda, 0xa9, 0x76, 0x1b, 0x84, 0x40, 0x9d, 0xf5, 0xf0,
	0x81, 0x4d, 0x51, 0xad, 0x75, 0xaa, 0xdd, 0xfd, 0xab, 0xca, 0x25, 0x39, 0x85, 0x06, 0xbb, 0x99,
	0xfb, 0xc9, 0x5d, 0x24, 0x42, 0x75, 0xaf, 0x44, 0xcf, 0xe1, 0x90, 0x4d, 0x50, 0xc4, 0x2c, 0xe2,
	0xea, 0xbe, 0xe4, 0x5e, 0xd5, 0x2f, 0xdf, 0xbc, 0x95, 0x7f, 0x44, 0x81, 0xc3, 0x94, 0xb9, 0x0b,
	0x81, 0x7e, 0xa0, 0x1e, 0x74, 0x2a, 0xdd, 0x26, 0x69, 0xc3, 0xd1, 0xc2, 0x9f, 0xde, 0xfb, 0x33,
	0xbc, 0x9b, 0xfb, 0x33, 0xb5, 0xde, 0xa9, 0x74, 0x1b, 0xe4, 0x14, 0x1e, 0x05, 0x59, 0xa9, 0x38,
	0x11, 0x8c, 0xcf, 0xd4, 0xc3, 0x0c, 0x95, 0xe4, 0x18, 0x85, 0xed, 0x87, 0xa8, 0x36, 0x4a, 0x44,
	0x92, 0x43, 0x5f, 0xdc, 0xab, 0x90, 0x21, 0x04, 0x80, 0x2d, 0xa8, 0x1f, 0x04, 0x02, 0xe3, 0x58,
	0x3d, 0x92, 0x98, 0xf6, 0x15, 0xb4, 0x97, 0x9d, 0x3a, 0x18, 0xa7, 0xf3, 0x24, 0xeb, 0x97, 0x40,
	0x5d, 0x60, 0x32, 0x8d, 0x02, 0xcc, 0x1a, 0xde, 0xbf, 0xaa, 0xbc, 0xd5, 0xba, 0x70, 0xea, 0xa2,
	0x78, 0x40, 0xe1, 0xb1, 0x10, 0x5d, 0xe4, 0x81, 0x31, 0x67, 0xc8, 0x13, 0x59, 0x68, 0xe6, 0x87,
	0x28, 0xd1, 0x2c, 0xb9, 0xa6, 0x7d, 0x01, 0x64, 0x1c, 0xaf, 0xf2, 0x72, 0xd6, 0x96, 0x3c, 0x0f,
	0xce, 0x0c, 0x97, 0x3a, 0xf8, 0x5b, 0x8a, 0x71, 0x42, 0x87, 0xd1, 0x2d, 0x9b, 0x23, 0xf5, 0xe4,
	0x5c, 0xc9, 0x31, 0xd4, 0xfd, 0xe9, 0x34, 0x4a, 0x79, 0x92, 0xe5, 0x36, 0xb2, 0x59, 0xbc, 0x8f,
	0x38, 0xda, 0x69, 0x78, 0x8b, 0xa2, 0x98, 0xfb, 0x27, 0x03, 0xaa, 0x65, 0x2d, 0x0d, 0xe1, 0xc9,
	0x9a, 0xea, 0x35, 0xe3, 0x41, 0x21, 0xbd, 0x5b, 0x94, 0xaf, 0x8b, 0x2e, 0x77, 0x2b, 0x57, 0xd9,
	0xd0, 0xbe, 0x05, 0xcd, 0x35, 0xa8, 0x83, 0x49, 0x2a, 0xf8, 0xba, 0x5a, 0x6e, 0x94, 0xe6, 0x43,
	0x93, 0xd2, 0x02, 0x13, 0x63, 0x39, 0x30, 0xed, 0x6b, 0x78, 0xbe, 0x9d, 0xb6, 0x8b, 0xe0, 0xc1,
	0xd3, 0x35, 0xdb, 0xe3, 0xc5, 0x4c, 0xf8, 0x01, 0x52, 0x3d, 0xf7, 0x2b, 0x77, 0x17, 0xcd, 0x83,
	0x8f, 0xdd, 0x13, 0x00, 0x8e, 0x1f, 0x4a, 0x2c, 0x37, 0xdf, 0x82, 0x83, 0x85, 0x1f, 0xc7, 0x1f,
	0x82, 0xc2, 0xfd, 0x37, 0xd0, 0x59, 0xd9, 0xf8, 0x44, 0x74, 0xa7, 0x95, 0x5f, 0xe1, 0x62, 0xdd,
	0x0a, 0xdf, 0xe8, 0xfa, 0xbf, 0xac, 0xe7, 0x3b, 0x78, 0xb5, 0xe6, 0x88, 0xff, 0xf3, 0x89, 0x8e,
	0x40, 0xdd, 0xe5, 0xea, 0xdf, 0x6d, 0xf6, 0x12, 0x2e, 0x76, 0x39, 0xd9, 0xe5, 0xe1, 0x7b, 0x68,
	0x4f, 0x50, 0xb0, 0xbb, 0x3f, 0xa8, 0xce, 0x03, 0x11, 0xb1, 0x40, 0xe7, 0xc1, 0x8d, 0x91, 0xdd,
	0x5a, 0x79, 0xea, 0xcb, 0xdd, 0x3c, 0x64, 0x89, 0xd9, 0x0d, 0x65, 0xe5, 0xb5, 0x2f, 0x41, 0x2d,
	0xdc, 0xbf, 0xfb, 0x3d, 0xbf, 0x09, 0x97, 0xcd, 0xb8, 0x9f, 0xa4, 0x02, 0xc9, 0x11, 0xd4, 0x52,
	0xc1, 0x72, 0xb2, 0xf6, 0x1e, 0x5e, 0xe4, 0xae, 0x36, 0xf2, 0x76, 0xf8, 0x92, 0x06, 0x78, 0xc4,
	0xb3, 0x37, 0x41, 0xad, 0x66, 0xc7, 0x7e, 0x02, 0x8d, 0x84, 0x85, 0x18, 0x27, 0x7e, 0xb8, 0xc8,
	0x26, 0x5f, 0x93, 0x50, 0x5c, 0x0a, 0xa9, 0x7b, 0xd9, 0x32, 0x34, 0x38, 0xce, 0x2b, 0x0d, 0xd0,
	0x7f, 0xc0, 0xbe, 0x1f, 0x62, 0xa1, 0xbd, 0x3a, 0xfd, 0xd7, 0x7f, 0xee, 0x01, 0x20, 0xcf, 0x9f,
	0x46, 0xab, 0x47, 0x9e, 0x00, 0x19, 0x8c, 0xfa, 0x96, 0x4d, 0xfb, 0xba, 0x67, 0x52, 0x77, 0x7c,
	0x4d, 0x8d, 0x61, 0x4f, 0xa9, 0x90, 0x17, 0x70, 0xbe, 0x86, 0x3b, 0xa6, 0x3b, 0x1e, 0x78, 0xcb,
	0x70, 0x95, 0x3c, 0x07, 0xd5, 0x35, 0x9d, 0x89, 0xe9, 0x50, 0xd7, 0xb4, 0x7b, 0xd4, 0xb3, 0x86,
	0x2b, 0x72, 0x4d, 0x92, 0x1d, 0xf3, 0xa7, 0xb1, 0xe9, 0x7a, 0x74, 0xec, 0x9a, 0xce, 0xc7, 0xe1,
	0x3d, 0x72, 0x01, 0x4f, 0x57, 0xb0, 0x37, 0x2a, 0x85, 0x8a, 0xf8, 0xfe, 0x3a, 0xfd, 0xda, 0xb2,
	0x7b, 0x74, 0x38, 0xba, 0xb6, 0x06, 0x32, 0xf3, 0x47, 0xd3, 0x56, 0x0e, 0xc8, 0x19, 0xb4, 0xb7,
	0x84, 0x95, 0x3a, 0xf9, 0x0c, 0x5e, 0x3a, 0xa6, 0x37, 0x76, 0xec, 0x4d, 0x5a, 0xd1, 0x81, 0x72,
	0x98, 0x8b, 0x6f, 0x24, 0x15, 0xe1, 0x06, 0x79, 0x06, 0x67, 0x4b, 0xeb, 0x37, 0x7d, 0x47, 0xef,
	0x99, 0x54, 0x37, 0x8c, 0xd1, 0xd8, 0xf6, 0x14, 0x20, 0xe7, 0xf0, 0xb8, 0xe0, 0x96, 0xb1, 0x82,
	0x77, 0x44, 0x5e, 0xc2, 0xb3, 0x25, 0xcf, 0xde, 0x74, 0xfd, 0x88, 0x7c, 0x0e, 0xff, 0x2f, 0xb9,
	0xf6, 0x4e, 0x7b, 0xcd, 0xbc, 0xc4, 0x16, 0x1d, 0xa5, 0x95, 0x97, 0xd8, 0xa2, 0x50, 0x70, 0x8f,
	0xe5, 0x60, 0x26, 0xa6, 0x63, 0xfd, 0xf0, 0x0b, 0xd5, 0xed, 0x9e, 0x33, 0xb2, 0x7a, 0xba, 0xdd,
	0xbb, 0x31, 0x14, 0x45, 0x0e, 0xbc, 0x14, 0x7d, 0xf7, 0x73, 0x39, 0x6e, 0xab, 0x6f, 0xeb, 0xde,
	0xd8, 0x31, 0x95, 0x13, 0xf2, 0x0a, 0x3a, 0x85, 0xf2, 0x66, 0xb8, 0x94, 0x27, 0xe4, 0x31, 0x9c,
	0x14, 0x59, 0x03, 0x53, 0x9f, 0x98, 0xb4, 0xaf, 0x0f, 0x4d, 0xa5, 0xfd, 0x9a, 0xc2, 0x31, 0xf2,
	0xe2, 0x57, 0x27, 0x44, 0xf9, 0x2d, 0x26, 0x2d, 0x80, 0x41, 0x9f, 0xca, 0x7f, 0x69, 0x74, 0xaf,
	0xfc, 0x8f, 0x9c, 0x40, 0xb3, 0xfc, 0x9c, 0x3d, 0x0a, 0x4a, 0x85, 0x10, 0x68, 0x95, 0x90, 0x95,
	0x11, 0x95, 0xaa, 0x2c, 0x50, 0x62, 0x76, 0x24, 0x4f, 0x85, 0x4d, 0x51, 0xa9, 0xfd, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0xb0, 0x16, 0x20, 0x09, 0xde, 0x07, 0x00, 0x00,
}
