// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MainCmd.proto

package Main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnMainCmdID int32

const (
	EnMainCmdID_LOGIN_MAIN_CMD             EnMainCmdID = 1
	EnMainCmdID_GATE_MAIN_CMD              EnMainCmdID = 2
	EnMainCmdID_USER_INFO_MAIN_CMD         EnMainCmdID = 3
	EnMainCmdID_LOBBY_MAIN_CMD             EnMainCmdID = 4
	EnMainCmdID_GAME_MAIN_USER             EnMainCmdID = 6
	EnMainCmdID_GAME_MAIN_GAME             EnMainCmdID = 8
	EnMainCmdID_LOBBY_MAIN_SIGN            EnMainCmdID = 12
	EnMainCmdID_LOBBY_MAIN_INVENTORY       EnMainCmdID = 13
	EnMainCmdID_LOBBY_MAIN_SHOPPINGMALL    EnMainCmdID = 14
	EnMainCmdID_LOBBY_MAIN_BANK            EnMainCmdID = 15
	EnMainCmdID_LOBBY_MAIN_FRIEND          EnMainCmdID = 16
	EnMainCmdID_LOBBY_MAIN_CHAT            EnMainCmdID = 17
	EnMainCmdID_LOBBY_MAIN_MAIL            EnMainCmdID = 18
	EnMainCmdID_LOBBY_MAIN_RANK            EnMainCmdID = 20
	EnMainCmdID_LOBBY_MAIN_PERSON_SET      EnMainCmdID = 21
	EnMainCmdID_LOBBY_MAIN_PURCHASE_REWARD EnMainCmdID = 22
	EnMainCmdID_CLUB_MAIN_CMD              EnMainCmdID = 23
)

var EnMainCmdID_name = map[int32]string{
	1:  "LOGIN_MAIN_CMD",
	2:  "GATE_MAIN_CMD",
	3:  "USER_INFO_MAIN_CMD",
	4:  "LOBBY_MAIN_CMD",
	6:  "GAME_MAIN_USER",
	8:  "GAME_MAIN_GAME",
	12: "LOBBY_MAIN_SIGN",
	13: "LOBBY_MAIN_INVENTORY",
	14: "LOBBY_MAIN_SHOPPINGMALL",
	15: "LOBBY_MAIN_BANK",
	16: "LOBBY_MAIN_FRIEND",
	17: "LOBBY_MAIN_CHAT",
	18: "LOBBY_MAIN_MAIL",
	20: "LOBBY_MAIN_RANK",
	21: "LOBBY_MAIN_PERSON_SET",
	22: "LOBBY_MAIN_PURCHASE_REWARD",
	23: "CLUB_MAIN_CMD",
}
var EnMainCmdID_value = map[string]int32{
	"LOGIN_MAIN_CMD":             1,
	"GATE_MAIN_CMD":              2,
	"USER_INFO_MAIN_CMD":         3,
	"LOBBY_MAIN_CMD":             4,
	"GAME_MAIN_USER":             6,
	"GAME_MAIN_GAME":             8,
	"LOBBY_MAIN_SIGN":            12,
	"LOBBY_MAIN_INVENTORY":       13,
	"LOBBY_MAIN_SHOPPINGMALL":    14,
	"LOBBY_MAIN_BANK":            15,
	"LOBBY_MAIN_FRIEND":          16,
	"LOBBY_MAIN_CHAT":            17,
	"LOBBY_MAIN_MAIL":            18,
	"LOBBY_MAIN_RANK":            20,
	"LOBBY_MAIN_PERSON_SET":      21,
	"LOBBY_MAIN_PURCHASE_REWARD": 22,
	"CLUB_MAIN_CMD":              23,
}

func (x EnMainCmdID) Enum() *EnMainCmdID {
	p := new(EnMainCmdID)
	*p = x
	return p
}
func (x EnMainCmdID) String() string {
	return proto.EnumName(EnMainCmdID_name, int32(x))
}
func (x *EnMainCmdID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EnMainCmdID_value, data, "EnMainCmdID")
	if err != nil {
		return err
	}
	*x = EnMainCmdID(value)
	return nil
}
func (EnMainCmdID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_MainCmd_1085879bf39f0a91, []int{0}
}

func init() {
	proto.RegisterEnum("Main.EnMainCmdID", EnMainCmdID_name, EnMainCmdID_value)
}

func init() { proto.RegisterFile("MainCmd.proto", fileDescriptor_MainCmd_1085879bf39f0a91) }

var fileDescriptor_MainCmd_1085879bf39f0a91 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd0, 0x4f, 0x4e, 0xeb, 0x30,
	0x10, 0x06, 0x70, 0xbd, 0xd7, 0x0a, 0xa1, 0x81, 0xb4, 0x93, 0xa1, 0x69, 0xf9, 0x23, 0x71, 0x00,
	0x16, 0xdc, 0xc1, 0x49, 0xdc, 0xc4, 0xc2, 0x1e, 0x47, 0x76, 0x02, 0xea, 0xca, 0x42, 0x82, 0x05,
	0x0b, 0x5a, 0x84, 0xb8, 0x06, 0x77, 0x46, 0x16, 0x95, 0x62, 0xb2, 0xb3, 0x7f, 0x33, 0xdf, 0x2c,
	0x3e, 0xc8, 0xcc, 0xf3, 0xdb, 0xbe, 0x7a, 0x7f, 0xb9, 0xff, 0xf8, 0x3c, 0x7c, 0x1d, 0x68, 0x1e,
	0xbf, 0x77, 0xdf, 0x33, 0x38, 0x7b, 0xdd, 0x1f, 0x27, 0xaa, 0x26, 0x82, 0x85, 0xb6, 0x8d, 0xe2,
	0x60, 0x84, 0xe2, 0x50, 0x99, 0x1a, 0xff, 0x51, 0x0e, 0x59, 0x23, 0x7a, 0x39, 0xd2, 0x7f, 0x5a,
	0x03, 0x0d, 0x5e, 0xba, 0xa0, 0x78, 0x6b, 0x47, 0x9f, 0xfd, 0xc6, 0xcb, 0x72, 0x37, 0xda, 0x3c,
	0x5a, 0x23, 0xcc, 0x31, 0x1e, 0x53, 0x78, 0xf2, 0xd7, 0xe2, 0x0b, 0x4f, 0xe9, 0x02, 0x96, 0x49,
	0xd6, 0xab, 0x86, 0xf1, 0x9c, 0x2e, 0x61, 0x95, 0xa0, 0xe2, 0x47, 0xc9, 0xbd, 0x75, 0x3b, 0xcc,
	0xe8, 0x06, 0x36, 0xe9, 0x7a, 0x6b, 0xbb, 0x4e, 0x71, 0x63, 0x84, 0xd6, 0xb8, 0x98, 0xdc, 0x2a,
	0x05, 0x3f, 0xe0, 0x92, 0x0a, 0xc8, 0x13, 0xdc, 0x3a, 0x25, 0xb9, 0x46, 0x9c, 0xec, 0x56, 0xad,
	0xe8, 0x31, 0x9f, 0xa0, 0x11, 0x4a, 0x23, 0x4d, 0xd0, 0xc5, 0xab, 0x2b, 0xba, 0x82, 0x22, 0xc1,
	0x4e, 0x3a, 0x6f, 0x39, 0x78, 0xd9, 0x63, 0x41, 0xb7, 0x70, 0x9d, 0x8e, 0x06, 0x57, 0xb5, 0xc2,
	0xcb, 0xe0, 0xe4, 0x93, 0x70, 0x35, 0xae, 0x63, 0xb1, 0x95, 0x1e, 0xca, 0xb1, 0xac, 0xcd, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x07, 0xf7, 0xbe, 0xa5, 0x01, 0x00, 0x00,
}
