// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GameConfig.proto

package redenvelopegame

import (
	context "context"
	fmt "fmt"
	tars "github.com/TarsCloud/TarsGo/tars"
	model "github.com/TarsCloud/TarsGo/tars/model"
	requestf "github.com/TarsCloud/TarsGo/tars/protocol/res/requestf"
	current "github.com/TarsCloud/TarsGo/tars/util/current"
	tools "github.com/TarsCloud/TarsGo/tars/util/tools"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetGameConfigRsp struct {
	Code                 Code     `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGameConfigRsp) Reset()         { *m = SetGameConfigRsp{} }
func (m *SetGameConfigRsp) String() string { return proto.CompactTextString(m) }
func (*SetGameConfigRsp) ProtoMessage()    {}
func (*SetGameConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{0}
}

func (m *SetGameConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGameConfigRsp.Unmarshal(m, b)
}
func (m *SetGameConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGameConfigRsp.Marshal(b, m, deterministic)
}
func (m *SetGameConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGameConfigRsp.Merge(m, src)
}
func (m *SetGameConfigRsp) XXX_Size() int {
	return xxx_messageInfo_SetGameConfigRsp.Size(m)
}
func (m *SetGameConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGameConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SetGameConfigRsp proto.InternalMessageInfo

func (m *SetGameConfigRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

type SetGameConfigReq struct {
	List                 []*PBGameConfig `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SetGameConfigReq) Reset()         { *m = SetGameConfigReq{} }
func (m *SetGameConfigReq) String() string { return proto.CompactTextString(m) }
func (*SetGameConfigReq) ProtoMessage()    {}
func (*SetGameConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{1}
}

func (m *SetGameConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGameConfigReq.Unmarshal(m, b)
}
func (m *SetGameConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGameConfigReq.Marshal(b, m, deterministic)
}
func (m *SetGameConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGameConfigReq.Merge(m, src)
}
func (m *SetGameConfigReq) XXX_Size() int {
	return xxx_messageInfo_SetGameConfigReq.Size(m)
}
func (m *SetGameConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGameConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetGameConfigReq proto.InternalMessageInfo

func (m *SetGameConfigReq) GetList() []*PBGameConfig {
	if m != nil {
		return m.List
	}
	return nil
}

type PBGameConfig struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ActivityId           int64    `protobuf:"varint,2,opt,name=ActivityId,proto3" json:"ActivityId,omitempty"`
	ProductId            int64    `protobuf:"varint,3,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	ConfigKey            string   `protobuf:"bytes,4,opt,name=ConfigKey,proto3" json:"ConfigKey,omitempty"`
	ConfigValue          string   `protobuf:"bytes,5,opt,name=ConfigValue,proto3" json:"ConfigValue,omitempty"`
	ConfigType           int32    `protobuf:"varint,6,opt,name=ConfigType,proto3" json:"ConfigType,omitempty"`
	IsShowConfig         bool     `protobuf:"varint,7,opt,name=IsShowConfig,proto3" json:"IsShowConfig,omitempty"`
	InitData             string   `protobuf:"bytes,8,opt,name=InitData,proto3" json:"InitData,omitempty"`
	IsBase               bool     `protobuf:"varint,9,opt,name=IsBase,proto3" json:"IsBase,omitempty"`
	SortNum              int32    `protobuf:"varint,10,opt,name=SortNum,proto3" json:"SortNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBGameConfig) Reset()         { *m = PBGameConfig{} }
func (m *PBGameConfig) String() string { return proto.CompactTextString(m) }
func (*PBGameConfig) ProtoMessage()    {}
func (*PBGameConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{2}
}

func (m *PBGameConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBGameConfig.Unmarshal(m, b)
}
func (m *PBGameConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBGameConfig.Marshal(b, m, deterministic)
}
func (m *PBGameConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBGameConfig.Merge(m, src)
}
func (m *PBGameConfig) XXX_Size() int {
	return xxx_messageInfo_PBGameConfig.Size(m)
}
func (m *PBGameConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PBGameConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PBGameConfig proto.InternalMessageInfo

func (m *PBGameConfig) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PBGameConfig) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *PBGameConfig) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *PBGameConfig) GetConfigKey() string {
	if m != nil {
		return m.ConfigKey
	}
	return ""
}

func (m *PBGameConfig) GetConfigValue() string {
	if m != nil {
		return m.ConfigValue
	}
	return ""
}

func (m *PBGameConfig) GetConfigType() int32 {
	if m != nil {
		return m.ConfigType
	}
	return 0
}

func (m *PBGameConfig) GetIsShowConfig() bool {
	if m != nil {
		return m.IsShowConfig
	}
	return false
}

func (m *PBGameConfig) GetInitData() string {
	if m != nil {
		return m.InitData
	}
	return ""
}

func (m *PBGameConfig) GetIsBase() bool {
	if m != nil {
		return m.IsBase
	}
	return false
}

func (m *PBGameConfig) GetSortNum() int32 {
	if m != nil {
		return m.SortNum
	}
	return 0
}

type GetGameConfigReq struct {
	ActivityId           int64    `protobuf:"varint,1,opt,name=ActivityId,proto3" json:"ActivityId,omitempty"`
	ProductId            int64    `protobuf:"varint,2,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	IsAllConfig          bool     `protobuf:"varint,3,opt,name=IsAllConfig,proto3" json:"IsAllConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGameConfigReq) Reset()         { *m = GetGameConfigReq{} }
func (m *GetGameConfigReq) String() string { return proto.CompactTextString(m) }
func (*GetGameConfigReq) ProtoMessage()    {}
func (*GetGameConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{3}
}

func (m *GetGameConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameConfigReq.Unmarshal(m, b)
}
func (m *GetGameConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameConfigReq.Marshal(b, m, deterministic)
}
func (m *GetGameConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameConfigReq.Merge(m, src)
}
func (m *GetGameConfigReq) XXX_Size() int {
	return xxx_messageInfo_GetGameConfigReq.Size(m)
}
func (m *GetGameConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameConfigReq proto.InternalMessageInfo

func (m *GetGameConfigReq) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *GetGameConfigReq) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *GetGameConfigReq) GetIsAllConfig() bool {
	if m != nil {
		return m.IsAllConfig
	}
	return false
}

type GetGameConfigRsp struct {
	Code                 Code            `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	List                 []*PBGameConfig `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetGameConfigRsp) Reset()         { *m = GetGameConfigRsp{} }
func (m *GetGameConfigRsp) String() string { return proto.CompactTextString(m) }
func (*GetGameConfigRsp) ProtoMessage()    {}
func (*GetGameConfigRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{4}
}

func (m *GetGameConfigRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameConfigRsp.Unmarshal(m, b)
}
func (m *GetGameConfigRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameConfigRsp.Marshal(b, m, deterministic)
}
func (m *GetGameConfigRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameConfigRsp.Merge(m, src)
}
func (m *GetGameConfigRsp) XXX_Size() int {
	return xxx_messageInfo_GetGameConfigRsp.Size(m)
}
func (m *GetGameConfigRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameConfigRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameConfigRsp proto.InternalMessageInfo

func (m *GetGameConfigRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

func (m *GetGameConfigRsp) GetList() []*PBGameConfig {
	if m != nil {
		return m.List
	}
	return nil
}

//config type = 1 字符串类型 时初始化结构
type ConfigStringFieldInitData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	DefaultValue         string   `protobuf:"bytes,3,opt,name=DefaultValue,proto3" json:"DefaultValue,omitempty"`
	MaxLength            int32    `protobuf:"varint,4,opt,name=MaxLength,proto3" json:"MaxLength,omitempty"`
	IsEmpty              bool     `protobuf:"varint,5,opt,name=IsEmpty,proto3" json:"IsEmpty,omitempty"`
	Placeholder          string   `protobuf:"bytes,6,opt,name=Placeholder,proto3" json:"Placeholder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigStringFieldInitData) Reset()         { *m = ConfigStringFieldInitData{} }
func (m *ConfigStringFieldInitData) String() string { return proto.CompactTextString(m) }
func (*ConfigStringFieldInitData) ProtoMessage()    {}
func (*ConfigStringFieldInitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{5}
}

func (m *ConfigStringFieldInitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigStringFieldInitData.Unmarshal(m, b)
}
func (m *ConfigStringFieldInitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigStringFieldInitData.Marshal(b, m, deterministic)
}
func (m *ConfigStringFieldInitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigStringFieldInitData.Merge(m, src)
}
func (m *ConfigStringFieldInitData) XXX_Size() int {
	return xxx_messageInfo_ConfigStringFieldInitData.Size(m)
}
func (m *ConfigStringFieldInitData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigStringFieldInitData.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigStringFieldInitData proto.InternalMessageInfo

func (m *ConfigStringFieldInitData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigStringFieldInitData) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ConfigStringFieldInitData) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

func (m *ConfigStringFieldInitData) GetMaxLength() int32 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

func (m *ConfigStringFieldInitData) GetIsEmpty() bool {
	if m != nil {
		return m.IsEmpty
	}
	return false
}

func (m *ConfigStringFieldInitData) GetPlaceholder() string {
	if m != nil {
		return m.Placeholder
	}
	return ""
}

//config type = 2 数字类型 初始化结构
type ConfigIntFieldInitData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	DefaultValue         string   `protobuf:"bytes,3,opt,name=DefaultValue,proto3" json:"DefaultValue,omitempty"`
	MinValue             int64    `protobuf:"varint,4,opt,name=MinValue,proto3" json:"MinValue,omitempty"`
	MaxValue             int64    `protobuf:"varint,5,opt,name=MaxValue,proto3" json:"MaxValue,omitempty"`
	Unit                 string   `protobuf:"bytes,6,opt,name=Unit,proto3" json:"Unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigIntFieldInitData) Reset()         { *m = ConfigIntFieldInitData{} }
func (m *ConfigIntFieldInitData) String() string { return proto.CompactTextString(m) }
func (*ConfigIntFieldInitData) ProtoMessage()    {}
func (*ConfigIntFieldInitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{6}
}

func (m *ConfigIntFieldInitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigIntFieldInitData.Unmarshal(m, b)
}
func (m *ConfigIntFieldInitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigIntFieldInitData.Marshal(b, m, deterministic)
}
func (m *ConfigIntFieldInitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigIntFieldInitData.Merge(m, src)
}
func (m *ConfigIntFieldInitData) XXX_Size() int {
	return xxx_messageInfo_ConfigIntFieldInitData.Size(m)
}
func (m *ConfigIntFieldInitData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigIntFieldInitData.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigIntFieldInitData proto.InternalMessageInfo

func (m *ConfigIntFieldInitData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigIntFieldInitData) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ConfigIntFieldInitData) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

func (m *ConfigIntFieldInitData) GetMinValue() int64 {
	if m != nil {
		return m.MinValue
	}
	return 0
}

func (m *ConfigIntFieldInitData) GetMaxValue() int64 {
	if m != nil {
		return m.MaxValue
	}
	return 0
}

func (m *ConfigIntFieldInitData) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

//config type =3 票种选择 初始化结构
type ConfigTicketSelectFieldInitData struct {
	Name                 string                        `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 string                        `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	DefaultValue         *ConfigTicketSelectFieldValue `protobuf:"bytes,3,opt,name=DefaultValue,proto3" json:"DefaultValue,omitempty"`
	DefaultTickets       []*TicketStruct               `protobuf:"bytes,4,rep,name=DefaultTickets,proto3" json:"DefaultTickets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ConfigTicketSelectFieldInitData) Reset()         { *m = ConfigTicketSelectFieldInitData{} }
func (m *ConfigTicketSelectFieldInitData) String() string { return proto.CompactTextString(m) }
func (*ConfigTicketSelectFieldInitData) ProtoMessage()    {}
func (*ConfigTicketSelectFieldInitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{7}
}

func (m *ConfigTicketSelectFieldInitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigTicketSelectFieldInitData.Unmarshal(m, b)
}
func (m *ConfigTicketSelectFieldInitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigTicketSelectFieldInitData.Marshal(b, m, deterministic)
}
func (m *ConfigTicketSelectFieldInitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigTicketSelectFieldInitData.Merge(m, src)
}
func (m *ConfigTicketSelectFieldInitData) XXX_Size() int {
	return xxx_messageInfo_ConfigTicketSelectFieldInitData.Size(m)
}
func (m *ConfigTicketSelectFieldInitData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigTicketSelectFieldInitData.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigTicketSelectFieldInitData proto.InternalMessageInfo

func (m *ConfigTicketSelectFieldInitData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigTicketSelectFieldInitData) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ConfigTicketSelectFieldInitData) GetDefaultValue() *ConfigTicketSelectFieldValue {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

func (m *ConfigTicketSelectFieldInitData) GetDefaultTickets() []*TicketStruct {
	if m != nil {
		return m.DefaultTickets
	}
	return nil
}

//config type =3 票种选择 Value 格式
type ConfigTicketSelectFieldValue struct {
	TicketIds            []int64  `protobuf:"varint,1,rep,packed,name=TicketIds,proto3" json:"TicketIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigTicketSelectFieldValue) Reset()         { *m = ConfigTicketSelectFieldValue{} }
func (m *ConfigTicketSelectFieldValue) String() string { return proto.CompactTextString(m) }
func (*ConfigTicketSelectFieldValue) ProtoMessage()    {}
func (*ConfigTicketSelectFieldValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{8}
}

func (m *ConfigTicketSelectFieldValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigTicketSelectFieldValue.Unmarshal(m, b)
}
func (m *ConfigTicketSelectFieldValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigTicketSelectFieldValue.Marshal(b, m, deterministic)
}
func (m *ConfigTicketSelectFieldValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigTicketSelectFieldValue.Merge(m, src)
}
func (m *ConfigTicketSelectFieldValue) XXX_Size() int {
	return xxx_messageInfo_ConfigTicketSelectFieldValue.Size(m)
}
func (m *ConfigTicketSelectFieldValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigTicketSelectFieldValue.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigTicketSelectFieldValue proto.InternalMessageInfo

func (m *ConfigTicketSelectFieldValue) GetTicketIds() []int64 {
	if m != nil {
		return m.TicketIds
	}
	return nil
}

type TicketStruct struct {
	TicketId             int64    `protobuf:"varint,1,opt,name=TicketId,proto3" json:"TicketId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TicketStruct) Reset()         { *m = TicketStruct{} }
func (m *TicketStruct) String() string { return proto.CompactTextString(m) }
func (*TicketStruct) ProtoMessage()    {}
func (*TicketStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{9}
}

func (m *TicketStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketStruct.Unmarshal(m, b)
}
func (m *TicketStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketStruct.Marshal(b, m, deterministic)
}
func (m *TicketStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketStruct.Merge(m, src)
}
func (m *TicketStruct) XXX_Size() int {
	return xxx_messageInfo_TicketStruct.Size(m)
}
func (m *TicketStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketStruct.DiscardUnknown(m)
}

var xxx_messageInfo_TicketStruct proto.InternalMessageInfo

func (m *TicketStruct) GetTicketId() int64 {
	if m != nil {
		return m.TicketId
	}
	return 0
}

func (m *TicketStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//config type = 4 单选类型 初始化结构
type ConfigRadioFieldInitData struct {
	Name                 string         `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 string         `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	DefaultValue         string         `protobuf:"bytes,3,opt,name=DefaultValue,proto3" json:"DefaultValue,omitempty"`
	DefaultData          []*RadioStruct `protobuf:"bytes,4,rep,name=DefaultData,proto3" json:"DefaultData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConfigRadioFieldInitData) Reset()         { *m = ConfigRadioFieldInitData{} }
func (m *ConfigRadioFieldInitData) String() string { return proto.CompactTextString(m) }
func (*ConfigRadioFieldInitData) ProtoMessage()    {}
func (*ConfigRadioFieldInitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{10}
}

func (m *ConfigRadioFieldInitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRadioFieldInitData.Unmarshal(m, b)
}
func (m *ConfigRadioFieldInitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRadioFieldInitData.Marshal(b, m, deterministic)
}
func (m *ConfigRadioFieldInitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRadioFieldInitData.Merge(m, src)
}
func (m *ConfigRadioFieldInitData) XXX_Size() int {
	return xxx_messageInfo_ConfigRadioFieldInitData.Size(m)
}
func (m *ConfigRadioFieldInitData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRadioFieldInitData.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRadioFieldInitData proto.InternalMessageInfo

func (m *ConfigRadioFieldInitData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigRadioFieldInitData) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ConfigRadioFieldInitData) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

func (m *ConfigRadioFieldInitData) GetDefaultData() []*RadioStruct {
	if m != nil {
		return m.DefaultData
	}
	return nil
}

//config type = 4 单选赋值
type RadioStruct struct {
	DefaultVaue          string   `protobuf:"bytes,1,opt,name=DefaultVaue,proto3" json:"DefaultVaue,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RadioStruct) Reset()         { *m = RadioStruct{} }
func (m *RadioStruct) String() string { return proto.CompactTextString(m) }
func (*RadioStruct) ProtoMessage()    {}
func (*RadioStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{11}
}

func (m *RadioStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RadioStruct.Unmarshal(m, b)
}
func (m *RadioStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RadioStruct.Marshal(b, m, deterministic)
}
func (m *RadioStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RadioStruct.Merge(m, src)
}
func (m *RadioStruct) XXX_Size() int {
	return xxx_messageInfo_RadioStruct.Size(m)
}
func (m *RadioStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_RadioStruct.DiscardUnknown(m)
}

var xxx_messageInfo_RadioStruct proto.InternalMessageInfo

func (m *RadioStruct) GetDefaultVaue() string {
	if m != nil {
		return m.DefaultVaue
	}
	return ""
}

func (m *RadioStruct) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

//config type = 5 布尔赋值 初始化结构
type ConfigBooleanFieldInitData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	DefaultValue         string   `protobuf:"bytes,3,opt,name=DefaultValue,proto3" json:"DefaultValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigBooleanFieldInitData) Reset()         { *m = ConfigBooleanFieldInitData{} }
func (m *ConfigBooleanFieldInitData) String() string { return proto.CompactTextString(m) }
func (*ConfigBooleanFieldInitData) ProtoMessage()    {}
func (*ConfigBooleanFieldInitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{12}
}

func (m *ConfigBooleanFieldInitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigBooleanFieldInitData.Unmarshal(m, b)
}
func (m *ConfigBooleanFieldInitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigBooleanFieldInitData.Marshal(b, m, deterministic)
}
func (m *ConfigBooleanFieldInitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigBooleanFieldInitData.Merge(m, src)
}
func (m *ConfigBooleanFieldInitData) XXX_Size() int {
	return xxx_messageInfo_ConfigBooleanFieldInitData.Size(m)
}
func (m *ConfigBooleanFieldInitData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigBooleanFieldInitData.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigBooleanFieldInitData proto.InternalMessageInfo

func (m *ConfigBooleanFieldInitData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigBooleanFieldInitData) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ConfigBooleanFieldInitData) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

//config type = 6 字符串列表赋值 初始化结构
type ConfigStringListFieldInitData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	MaxLength            int32    `protobuf:"varint,3,opt,name=MaxLength,proto3" json:"MaxLength,omitempty"`
	IsEmpty              bool     `protobuf:"varint,4,opt,name=IsEmpty,proto3" json:"IsEmpty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigStringListFieldInitData) Reset()         { *m = ConfigStringListFieldInitData{} }
func (m *ConfigStringListFieldInitData) String() string { return proto.CompactTextString(m) }
func (*ConfigStringListFieldInitData) ProtoMessage()    {}
func (*ConfigStringListFieldInitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{13}
}

func (m *ConfigStringListFieldInitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigStringListFieldInitData.Unmarshal(m, b)
}
func (m *ConfigStringListFieldInitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigStringListFieldInitData.Marshal(b, m, deterministic)
}
func (m *ConfigStringListFieldInitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigStringListFieldInitData.Merge(m, src)
}
func (m *ConfigStringListFieldInitData) XXX_Size() int {
	return xxx_messageInfo_ConfigStringListFieldInitData.Size(m)
}
func (m *ConfigStringListFieldInitData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigStringListFieldInitData.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigStringListFieldInitData proto.InternalMessageInfo

func (m *ConfigStringListFieldInitData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigStringListFieldInitData) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ConfigStringListFieldInitData) GetMaxLength() int32 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

func (m *ConfigStringListFieldInitData) GetIsEmpty() bool {
	if m != nil {
		return m.IsEmpty
	}
	return false
}

//config type =6 字符串列表 Value 格式
type ConfigStringListFieldValue struct {
	StrList              []string `protobuf:"bytes,1,rep,name=StrList,proto3" json:"StrList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigStringListFieldValue) Reset()         { *m = ConfigStringListFieldValue{} }
func (m *ConfigStringListFieldValue) String() string { return proto.CompactTextString(m) }
func (*ConfigStringListFieldValue) ProtoMessage()    {}
func (*ConfigStringListFieldValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{14}
}

func (m *ConfigStringListFieldValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigStringListFieldValue.Unmarshal(m, b)
}
func (m *ConfigStringListFieldValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigStringListFieldValue.Marshal(b, m, deterministic)
}
func (m *ConfigStringListFieldValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigStringListFieldValue.Merge(m, src)
}
func (m *ConfigStringListFieldValue) XXX_Size() int {
	return xxx_messageInfo_ConfigStringListFieldValue.Size(m)
}
func (m *ConfigStringListFieldValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigStringListFieldValue.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigStringListFieldValue proto.InternalMessageInfo

func (m *ConfigStringListFieldValue) GetStrList() []string {
	if m != nil {
		return m.StrList
	}
	return nil
}

//config type =7 多图片上传选择 初始化结构
type ConfigImgListFieldInitData struct {
	Name                 string       `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 string       `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	InitData             []*ImgStruct `protobuf:"bytes,3,rep,name=InitData,proto3" json:"InitData,omitempty"`
	DemoImgUrl           string       `protobuf:"bytes,4,opt,name=DemoImgUrl,proto3" json:"DemoImgUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfigImgListFieldInitData) Reset()         { *m = ConfigImgListFieldInitData{} }
func (m *ConfigImgListFieldInitData) String() string { return proto.CompactTextString(m) }
func (*ConfigImgListFieldInitData) ProtoMessage()    {}
func (*ConfigImgListFieldInitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{15}
}

func (m *ConfigImgListFieldInitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigImgListFieldInitData.Unmarshal(m, b)
}
func (m *ConfigImgListFieldInitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigImgListFieldInitData.Marshal(b, m, deterministic)
}
func (m *ConfigImgListFieldInitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigImgListFieldInitData.Merge(m, src)
}
func (m *ConfigImgListFieldInitData) XXX_Size() int {
	return xxx_messageInfo_ConfigImgListFieldInitData.Size(m)
}
func (m *ConfigImgListFieldInitData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigImgListFieldInitData.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigImgListFieldInitData proto.InternalMessageInfo

func (m *ConfigImgListFieldInitData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigImgListFieldInitData) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ConfigImgListFieldInitData) GetInitData() []*ImgStruct {
	if m != nil {
		return m.InitData
	}
	return nil
}

func (m *ConfigImgListFieldInitData) GetDemoImgUrl() string {
	if m != nil {
		return m.DemoImgUrl
	}
	return ""
}

//config type =7 多图片上传选择 Value 格式
type ConfigImgListFieldValue struct {
	ImgList              []*ConfigImgValue `protobuf:"bytes,1,rep,name=ImgList,proto3" json:"ImgList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConfigImgListFieldValue) Reset()         { *m = ConfigImgListFieldValue{} }
func (m *ConfigImgListFieldValue) String() string { return proto.CompactTextString(m) }
func (*ConfigImgListFieldValue) ProtoMessage()    {}
func (*ConfigImgListFieldValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{16}
}

func (m *ConfigImgListFieldValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigImgListFieldValue.Unmarshal(m, b)
}
func (m *ConfigImgListFieldValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigImgListFieldValue.Marshal(b, m, deterministic)
}
func (m *ConfigImgListFieldValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigImgListFieldValue.Merge(m, src)
}
func (m *ConfigImgListFieldValue) XXX_Size() int {
	return xxx_messageInfo_ConfigImgListFieldValue.Size(m)
}
func (m *ConfigImgListFieldValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigImgListFieldValue.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigImgListFieldValue proto.InternalMessageInfo

func (m *ConfigImgListFieldValue) GetImgList() []*ConfigImgValue {
	if m != nil {
		return m.ImgList
	}
	return nil
}

//config type =7 图片Value 格式
type ConfigImgValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	ImgUrl               string   `protobuf:"bytes,2,opt,name=ImgUrl,proto3" json:"ImgUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigImgValue) Reset()         { *m = ConfigImgValue{} }
func (m *ConfigImgValue) String() string { return proto.CompactTextString(m) }
func (*ConfigImgValue) ProtoMessage()    {}
func (*ConfigImgValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{17}
}

func (m *ConfigImgValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigImgValue.Unmarshal(m, b)
}
func (m *ConfigImgValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigImgValue.Marshal(b, m, deterministic)
}
func (m *ConfigImgValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigImgValue.Merge(m, src)
}
func (m *ConfigImgValue) XXX_Size() int {
	return xxx_messageInfo_ConfigImgValue.Size(m)
}
func (m *ConfigImgValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigImgValue.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigImgValue proto.InternalMessageInfo

func (m *ConfigImgValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ConfigImgValue) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

//config type =7 图片初始 格式
type ImgStruct struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Width                int32    `protobuf:"varint,3,opt,name=Width,proto3" json:"Width,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	Size                 int32    `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	IsEmpty              bool     `protobuf:"varint,6,opt,name=IsEmpty,proto3" json:"IsEmpty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImgStruct) Reset()         { *m = ImgStruct{} }
func (m *ImgStruct) String() string { return proto.CompactTextString(m) }
func (*ImgStruct) ProtoMessage()    {}
func (*ImgStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{18}
}

func (m *ImgStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImgStruct.Unmarshal(m, b)
}
func (m *ImgStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImgStruct.Marshal(b, m, deterministic)
}
func (m *ImgStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImgStruct.Merge(m, src)
}
func (m *ImgStruct) XXX_Size() int {
	return xxx_messageInfo_ImgStruct.Size(m)
}
func (m *ImgStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_ImgStruct.DiscardUnknown(m)
}

var xxx_messageInfo_ImgStruct proto.InternalMessageInfo

func (m *ImgStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImgStruct) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ImgStruct) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ImgStruct) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ImgStruct) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ImgStruct) GetIsEmpty() bool {
	if m != nil {
		return m.IsEmpty
	}
	return false
}

//config type=8 霸屏金额 格式
type ConfigFullScreenSaleInitData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	MinTimes             int32    `protobuf:"varint,3,opt,name=MinTimes,proto3" json:"MinTimes,omitempty"`
	MaxTimes             int32    `protobuf:"varint,4,opt,name=MaxTimes,proto3" json:"MaxTimes,omitempty"`
	MinMoney             int32    `protobuf:"varint,5,opt,name=MinMoney,proto3" json:"MinMoney,omitempty"`
	MaxMoney             int32    `protobuf:"varint,6,opt,name=MaxMoney,proto3" json:"MaxMoney,omitempty"`
	MaxLength            int32    `protobuf:"varint,7,opt,name=MaxLength,proto3" json:"MaxLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigFullScreenSaleInitData) Reset()         { *m = ConfigFullScreenSaleInitData{} }
func (m *ConfigFullScreenSaleInitData) String() string { return proto.CompactTextString(m) }
func (*ConfigFullScreenSaleInitData) ProtoMessage()    {}
func (*ConfigFullScreenSaleInitData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{19}
}

func (m *ConfigFullScreenSaleInitData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFullScreenSaleInitData.Unmarshal(m, b)
}
func (m *ConfigFullScreenSaleInitData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFullScreenSaleInitData.Marshal(b, m, deterministic)
}
func (m *ConfigFullScreenSaleInitData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFullScreenSaleInitData.Merge(m, src)
}
func (m *ConfigFullScreenSaleInitData) XXX_Size() int {
	return xxx_messageInfo_ConfigFullScreenSaleInitData.Size(m)
}
func (m *ConfigFullScreenSaleInitData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFullScreenSaleInitData.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFullScreenSaleInitData proto.InternalMessageInfo

func (m *ConfigFullScreenSaleInitData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigFullScreenSaleInitData) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ConfigFullScreenSaleInitData) GetMinTimes() int32 {
	if m != nil {
		return m.MinTimes
	}
	return 0
}

func (m *ConfigFullScreenSaleInitData) GetMaxTimes() int32 {
	if m != nil {
		return m.MaxTimes
	}
	return 0
}

func (m *ConfigFullScreenSaleInitData) GetMinMoney() int32 {
	if m != nil {
		return m.MinMoney
	}
	return 0
}

func (m *ConfigFullScreenSaleInitData) GetMaxMoney() int32 {
	if m != nil {
		return m.MaxMoney
	}
	return 0
}

func (m *ConfigFullScreenSaleInitData) GetMaxLength() int32 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

//config type=8 霸屏金额值
type ConfigFullScreenSaleValue struct {
	Sale                 []*FullScreenSaleValue `protobuf:"bytes,1,rep,name=Sale,proto3" json:"Sale,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ConfigFullScreenSaleValue) Reset()         { *m = ConfigFullScreenSaleValue{} }
func (m *ConfigFullScreenSaleValue) String() string { return proto.CompactTextString(m) }
func (*ConfigFullScreenSaleValue) ProtoMessage()    {}
func (*ConfigFullScreenSaleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{20}
}

func (m *ConfigFullScreenSaleValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigFullScreenSaleValue.Unmarshal(m, b)
}
func (m *ConfigFullScreenSaleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigFullScreenSaleValue.Marshal(b, m, deterministic)
}
func (m *ConfigFullScreenSaleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigFullScreenSaleValue.Merge(m, src)
}
func (m *ConfigFullScreenSaleValue) XXX_Size() int {
	return xxx_messageInfo_ConfigFullScreenSaleValue.Size(m)
}
func (m *ConfigFullScreenSaleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigFullScreenSaleValue.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigFullScreenSaleValue proto.InternalMessageInfo

func (m *ConfigFullScreenSaleValue) GetSale() []*FullScreenSaleValue {
	if m != nil {
		return m.Sale
	}
	return nil
}

//config type=8 霸屏金额值格式
type FullScreenSaleValue struct {
	Money                int32    `protobuf:"varint,1,opt,name=Money,proto3" json:"Money,omitempty"`
	Times                int32    `protobuf:"varint,2,opt,name=Times,proto3" json:"Times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FullScreenSaleValue) Reset()         { *m = FullScreenSaleValue{} }
func (m *FullScreenSaleValue) String() string { return proto.CompactTextString(m) }
func (*FullScreenSaleValue) ProtoMessage()    {}
func (*FullScreenSaleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e41b502ecb72c2a, []int{21}
}

func (m *FullScreenSaleValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullScreenSaleValue.Unmarshal(m, b)
}
func (m *FullScreenSaleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullScreenSaleValue.Marshal(b, m, deterministic)
}
func (m *FullScreenSaleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullScreenSaleValue.Merge(m, src)
}
func (m *FullScreenSaleValue) XXX_Size() int {
	return xxx_messageInfo_FullScreenSaleValue.Size(m)
}
func (m *FullScreenSaleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FullScreenSaleValue.DiscardUnknown(m)
}

var xxx_messageInfo_FullScreenSaleValue proto.InternalMessageInfo

func (m *FullScreenSaleValue) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *FullScreenSaleValue) GetTimes() int32 {
	if m != nil {
		return m.Times
	}
	return 0
}

func init() {
	proto.RegisterType((*SetGameConfigRsp)(nil), "SetGameConfigRsp")
	proto.RegisterType((*SetGameConfigReq)(nil), "SetGameConfigReq")
	proto.RegisterType((*PBGameConfig)(nil), "PBGameConfig")
	proto.RegisterType((*GetGameConfigReq)(nil), "GetGameConfigReq")
	proto.RegisterType((*GetGameConfigRsp)(nil), "GetGameConfigRsp")
	proto.RegisterType((*ConfigStringFieldInitData)(nil), "ConfigStringFieldInitData")
	proto.RegisterType((*ConfigIntFieldInitData)(nil), "ConfigIntFieldInitData")
	proto.RegisterType((*ConfigTicketSelectFieldInitData)(nil), "ConfigTicketSelectFieldInitData")
	proto.RegisterType((*ConfigTicketSelectFieldValue)(nil), "ConfigTicketSelectFieldValue")
	proto.RegisterType((*TicketStruct)(nil), "TicketStruct")
	proto.RegisterType((*ConfigRadioFieldInitData)(nil), "ConfigRadioFieldInitData")
	proto.RegisterType((*RadioStruct)(nil), "RadioStruct")
	proto.RegisterType((*ConfigBooleanFieldInitData)(nil), "ConfigBooleanFieldInitData")
	proto.RegisterType((*ConfigStringListFieldInitData)(nil), "ConfigStringListFieldInitData")
	proto.RegisterType((*ConfigStringListFieldValue)(nil), "ConfigStringListFieldValue")
	proto.RegisterType((*ConfigImgListFieldInitData)(nil), "ConfigImgListFieldInitData")
	proto.RegisterType((*ConfigImgListFieldValue)(nil), "ConfigImgListFieldValue")
	proto.RegisterType((*ConfigImgValue)(nil), "ConfigImgValue")
	proto.RegisterType((*ImgStruct)(nil), "ImgStruct")
	proto.RegisterType((*ConfigFullScreenSaleInitData)(nil), "ConfigFullScreenSaleInitData")
	proto.RegisterType((*ConfigFullScreenSaleValue)(nil), "ConfigFullScreenSaleValue")
	proto.RegisterType((*FullScreenSaleValue)(nil), "FullScreenSaleValue")
}

func init() { proto.RegisterFile("GameConfig.proto", fileDescriptor_0e41b502ecb72c2a) }

var fileDescriptor_0e41b502ecb72c2a = []byte{
	// 941 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4d, 0x8f, 0xdb, 0x44,
	0x18, 0xc6, 0x1f, 0xc9, 0xc6, 0x6f, 0xd2, 0x65, 0x6b, 0x56, 0xc5, 0x8d, 0xda, 0x12, 0xe6, 0x80,
	0xc2, 0x01, 0x1f, 0x16, 0x15, 0x24, 0x84, 0x90, 0x76, 0x37, 0x6d, 0xb0, 0xe8, 0x56, 0x2b, 0xbb,
	0x05, 0x89, 0x9b, 0xb1, 0xa7, 0xc9, 0x08, 0x7f, 0x04, 0x7b, 0x52, 0x1a, 0x2e, 0x9c, 0xb8, 0xc1,
	0x95, 0x9f, 0x81, 0xf8, 0x0b, 0x88, 0xbf, 0xc0, 0x0f, 0x42, 0x33, 0xef, 0xf8, 0x73, 0xd3, 0x95,
	0x28, 0xda, 0x9b, 0x9f, 0xe7, 0x99, 0x77, 0xde, 0xaf, 0x99, 0x77, 0x0c, 0x47, 0xcb, 0x30, 0xa5,
	0xe7, 0x79, 0xf6, 0x82, 0xad, 0xdc, 0x4d, 0x91, 0xf3, 0x7c, 0x3a, 0x39, 0xcf, 0xd3, 0x34, 0xcf,
	0x10, 0x91, 0x8f, 0xe0, 0x28, 0xa0, 0xbc, 0x59, 0xe4, 0x97, 0x1b, 0xfb, 0x2e, 0x98, 0xe7, 0x79,
	0x4c, 0x1d, 0x6d, 0xa6, 0xcd, 0x0f, 0x4f, 0x06, 0xae, 0x00, 0xbe, 0xa4, 0xc8, 0xc3, 0xfe, 0x72,
	0xfa, 0x83, 0xfd, 0x3e, 0x98, 0x4f, 0x58, 0xc9, 0x1d, 0x6d, 0x66, 0xcc, 0xc7, 0x27, 0xb7, 0xdc,
	0xcb, 0xb3, 0x96, 0x2e, 0x25, 0xf2, 0x87, 0x0e, 0x93, 0x36, 0x6d, 0x1f, 0x82, 0xee, 0xc5, 0xd2,
	0x81, 0xe1, 0xeb, 0x5e, 0x6c, 0x3f, 0x00, 0x38, 0x8d, 0x38, 0x7b, 0xc9, 0xf8, 0xce, 0x8b, 0x1d,
	0x5d, 0xf2, 0x2d, 0xc6, 0xbe, 0x07, 0xd6, 0x65, 0x91, 0xc7, 0xdb, 0x88, 0x7b, 0xb1, 0x63, 0x48,
	0xb9, 0x21, 0x84, 0x8a, 0xfb, 0x7e, 0x45, 0x77, 0x8e, 0x39, 0xd3, 0xe6, 0x96, 0xdf, 0x10, 0xf6,
	0x0c, 0xc6, 0x08, 0xbe, 0x0e, 0x93, 0x2d, 0x75, 0x06, 0x52, 0x6f, 0x53, 0xc2, 0x3b, 0xc2, 0x67,
	0xbb, 0x0d, 0x75, 0x86, 0x33, 0x6d, 0x3e, 0xf0, 0x5b, 0x8c, 0x4d, 0x60, 0xe2, 0x95, 0xc1, 0x3a,
	0xff, 0x11, 0x39, 0xe7, 0x60, 0xa6, 0xcd, 0x47, 0x7e, 0x87, 0xb3, 0xa7, 0x30, 0xf2, 0x32, 0xc6,
	0x17, 0x21, 0x0f, 0x9d, 0x91, 0x74, 0x51, 0x63, 0xfb, 0x0e, 0x0c, 0xbd, 0xf2, 0x2c, 0x2c, 0xa9,
	0x63, 0x49, 0x4b, 0x85, 0x6c, 0x07, 0x0e, 0x82, 0xbc, 0xe0, 0x4f, 0xb7, 0xa9, 0x03, 0xd2, 0x69,
	0x05, 0x49, 0x01, 0x47, 0xcb, 0x7e, 0x9d, 0xbb, 0x35, 0xd2, 0xae, 0xaf, 0x91, 0xde, 0xaf, 0xd1,
	0x0c, 0xc6, 0x5e, 0x79, 0x9a, 0x24, 0x2a, 0x05, 0x43, 0x06, 0xd2, 0xa6, 0xc8, 0x65, 0xdf, 0xe7,
	0xb5, 0x47, 0xa1, 0x6e, 0xbb, 0xfe, 0xfa, 0xb6, 0xff, 0xa5, 0xc1, 0x5d, 0x24, 0x02, 0x5e, 0xb0,
	0x6c, 0xf5, 0x98, 0xd1, 0x24, 0xae, 0xab, 0x62, 0x83, 0xf9, 0x34, 0x4c, 0x71, 0x6f, 0xcb, 0x97,
	0xdf, 0x82, 0x5b, 0xd0, 0x32, 0x92, 0xe1, 0x5b, 0xbe, 0xfc, 0x16, 0xd5, 0x5f, 0xd0, 0x17, 0xe1,
	0x36, 0xe1, 0xd8, 0x40, 0x43, 0x6a, 0x1d, 0x4e, 0xe4, 0x7e, 0x11, 0xbe, 0x7a, 0x42, 0xb3, 0x15,
	0x5f, 0xcb, 0x13, 0x30, 0xf0, 0x1b, 0x42, 0xd4, 0xd9, 0x2b, 0x1f, 0xa5, 0x1b, 0xbe, 0x93, 0xdd,
	0x1f, 0xf9, 0x15, 0x14, 0x55, 0xb9, 0x4c, 0xc2, 0x88, 0xae, 0xf3, 0x24, 0xa6, 0x85, 0x6c, 0xbd,
	0xe5, 0xb7, 0x29, 0xf2, 0xa7, 0x06, 0x77, 0x30, 0x07, 0x2f, 0xe3, 0x37, 0x97, 0xc0, 0x14, 0x46,
	0x17, 0x2c, 0x43, 0xdd, 0x94, 0xbd, 0xab, 0xb1, 0xd4, 0xc2, 0x57, 0xcd, 0xe9, 0x15, 0x9a, 0xc2,
	0xc2, 0xdf, 0xf3, 0x8c, 0x71, 0x15, 0xb9, 0xfc, 0x26, 0x7f, 0x6b, 0xf0, 0x9e, 0x3a, 0xbd, 0x2c,
	0xfa, 0x9e, 0xf2, 0x80, 0x26, 0x34, 0x7a, 0xc3, 0xd8, 0x4f, 0xf7, 0xc4, 0x3e, 0x3e, 0xb9, 0xef,
	0xbe, 0x66, 0x7f, 0xb9, 0xa8, 0x97, 0xda, 0x43, 0x38, 0x54, 0x18, 0x97, 0x97, 0x8e, 0xa9, 0x8e,
	0x8c, 0x32, 0xe7, 0xc5, 0x36, 0xe2, 0x7e, 0x6f, 0x11, 0xf9, 0x1c, 0xee, 0x5d, 0xe7, 0x44, 0xb4,
	0x1c, 0x15, 0x2f, 0x2e, 0xe5, 0xec, 0x31, 0xfc, 0x86, 0x20, 0x5f, 0xc0, 0xa4, 0xbd, 0xbb, 0xa8,
	0x61, 0x25, 0xaa, 0xab, 0x53, 0xe3, 0xba, 0x16, 0x7a, 0x53, 0x0b, 0xf2, 0xbb, 0x06, 0x8e, 0x3a,
	0xcb, 0x61, 0xcc, 0xf2, 0x9b, 0x6b, 0xbc, 0x0b, 0x63, 0x85, 0xe5, 0xe8, 0xc0, 0xd2, 0x4c, 0x5c,
	0xe9, 0x55, 0x55, 0xa6, 0xbd, 0x80, 0x9c, 0xc3, 0xb8, 0xa5, 0x89, 0x03, 0x5c, 0x6f, 0xb7, 0xad,
	0x22, 0x6a, 0x53, 0xfb, 0x02, 0x23, 0x6b, 0x98, 0x62, 0x72, 0x67, 0x79, 0x9e, 0xd0, 0x30, 0xbb,
	0xb1, 0xf4, 0xc8, 0xcf, 0x70, 0xbf, 0x3d, 0x01, 0xc4, 0x58, 0x78, 0x33, 0x67, 0x9d, 0x1b, 0x6e,
	0x5c, 0x73, 0xc3, 0xcd, 0xce, 0x0d, 0x27, 0x9f, 0x54, 0xa9, 0xf6, 0x02, 0xc0, 0xea, 0x8b, 0x09,
	0xcc, 0x8b, 0xfa, 0xf9, 0xb2, 0xfc, 0x0a, 0x92, 0x5f, 0xb5, 0xca, 0xd0, 0x4b, 0xff, 0x47, 0xd8,
	0x1f, 0xb4, 0x9e, 0x05, 0x43, 0xf6, 0x16, 0x5c, 0x2f, 0x5d, 0xa9, 0xce, 0x36, 0x4f, 0xc4, 0x03,
	0x80, 0x05, 0x4d, 0x73, 0x2f, 0x5d, 0x3d, 0x2f, 0x12, 0xf5, 0x86, 0xb5, 0x18, 0xb2, 0x80, 0x77,
	0xaf, 0x46, 0x83, 0x39, 0x7c, 0x08, 0x07, 0x8a, 0x54, 0x4f, 0xf0, 0xdb, 0x6e, 0xbd, 0x14, 0xef,
	0x63, 0xa5, 0x93, 0xcf, 0xe0, 0xb0, 0x2b, 0xd9, 0x47, 0x60, 0x88, 0x47, 0x13, 0xd3, 0x10, 0x9f,
	0xf2, 0xb1, 0xc2, 0x28, 0x30, 0x0f, 0x85, 0xc8, 0x6f, 0x1a, 0x58, 0x75, 0xe4, 0x7b, 0xf3, 0x57,
	0x7b, 0xe9, 0xcd, 0x5e, 0xc7, 0x30, 0xf8, 0x86, 0xc5, 0x75, 0xc3, 0x10, 0x08, 0x0f, 0x5f, 0x52,
	0xb6, 0x5a, 0x73, 0x35, 0xa9, 0x15, 0x12, 0x7b, 0x06, 0xec, 0x27, 0x9c, 0x71, 0x03, 0x5f, 0x7e,
	0xb7, 0x1b, 0x3b, 0xec, 0x36, 0xf6, 0x1f, 0xad, 0x1a, 0x10, 0x8f, 0xb7, 0x49, 0x12, 0x44, 0x05,
	0xa5, 0x59, 0x10, 0x26, 0xf4, 0x3f, 0xb7, 0x08, 0x47, 0xef, 0x33, 0x96, 0xd2, 0x52, 0xc5, 0x59,
	0x63, 0x35, 0x7a, 0x51, 0x33, 0x95, 0xa6, 0xb0, 0xb2, 0xbb, 0xc8, 0x33, 0xba, 0x53, 0x21, 0xd7,
	0x58, 0xd9, 0xa1, 0x36, 0xac, 0xed, 0x50, 0xeb, 0x9c, 0xe4, 0x83, 0xde, 0x49, 0x26, 0x8f, 0xaa,
	0x27, 0xb3, 0x9b, 0x15, 0x76, 0x6b, 0x0e, 0xa6, 0x00, 0xaa, 0xcf, 0xc7, 0xee, 0x9e, 0x35, 0xbe,
	0x5c, 0x41, 0x4e, 0xe1, 0x9d, 0x7d, 0x1b, 0x1c, 0xc3, 0x00, 0x83, 0xd2, 0xb0, 0x21, 0x18, 0xd1,
	0x31, 0x0c, 0x30, 0x45, 0x1d, 0x59, 0x09, 0x4e, 0x7e, 0xd1, 0xe0, 0x76, 0xf3, 0xa4, 0x07, 0xb4,
	0x78, 0xc9, 0x22, 0x6a, 0x7f, 0x0a, 0xb7, 0x3a, 0x7f, 0x80, 0xf6, 0x6d, 0xb7, 0xff, 0x47, 0x38,
	0xed, 0x53, 0xe5, 0x86, 0xbc, 0x25, 0x0c, 0x97, 0x3d, 0xc3, 0xe5, 0x55, 0xc3, 0xe5, 0x15, 0xc3,
	0xb3, 0xc9, 0xb7, 0xb0, 0x0a, 0x53, 0x1a, 0x49, 0xea, 0xbb, 0xa1, 0xfc, 0x6f, 0xfd, 0xf8, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x89, 0x74, 0x1e, 0xd9, 0x0a, 0x00, 0x00,
}

// This following code was generated by tarsrpc
// Gernerated from GameConfig.proto
type GameConfigService struct {
	s model.Servant
}

//SetServant is required by the servant interface.
func (obj *GameConfigService) SetServant(s model.Servant) {
	obj.s = s
}

//AddServant is required by the servant interface
func (obj *GameConfigService) AddServant(imp impGameConfigService, objStr string) {
	tars.AddServant(obj, imp, objStr)
}

////AddServant adds servant  for the service with context
func (obj *GameConfigService) AddServantWithContext(imp impGameConfigServiceWithContext, objStr string) {
	tars.AddServantWithContext(obj, imp, objStr)
}

//TarsSetTimeout is required by the servant interface. t is the timeout in ms.
func (obj *GameConfigService) TarsSetTimeout(t int) {
	obj.s.TarsSetTimeout(t)
}

//TarsSetProtocol is required by the servant interface. t is the protocol.
func (obj *GameConfigService) TarsSetProtocol(p model.Protocol) {
	obj.s.TarsSetProtocol(p)
}

type impGameConfigService interface {
	SetGameConfig(input SetGameConfigReq) (output SetGameConfigRsp, err error)
	GetGameConfig(input GetGameConfigReq) (output GetGameConfigRsp, err error)
}

type impGameConfigServiceWithContext interface {
	SetGameConfig(ctx context.Context, input SetGameConfigReq) (output SetGameConfigRsp, err error)
	GetGameConfig(ctx context.Context, input GetGameConfigReq) (output GetGameConfigRsp, err error)
}

//Dispatch is used to call the user implement of the defined method.
func (obj *GameConfigService) Dispatch(ctx context.Context, val interface{}, req *requestf.RequestPacket, resp *requestf.ResponsePacket, withContext bool) (err error) {
	input := tools.Int8ToByte(req.SBuffer)
	var output []byte
	funcName := req.SFuncName
	switch funcName {

	case "SetGameConfig":
		inputDefine := SetGameConfigReq{}
		if err = proto.Unmarshal(input, &inputDefine); err != nil {
			return err
		}
		var res SetGameConfigRsp
		if withContext == false {
			imp := val.(impGameConfigService)
			res, err = imp.SetGameConfig(inputDefine)
			if err != nil {
				return err
			}
		} else {
			imp := val.(impGameConfigServiceWithContext)
			res, err = imp.SetGameConfig(ctx, inputDefine)
			if err != nil {
				return err
			}
		}
		output, err = proto.Marshal(&res)
		if err != nil {
			return err
		}

	case "GetGameConfig":
		inputDefine := GetGameConfigReq{}
		if err = proto.Unmarshal(input, &inputDefine); err != nil {
			return err
		}
		var res GetGameConfigRsp
		if withContext == false {
			imp := val.(impGameConfigService)
			res, err = imp.GetGameConfig(inputDefine)
			if err != nil {
				return err
			}
		} else {
			imp := val.(impGameConfigServiceWithContext)
			res, err = imp.GetGameConfig(ctx, inputDefine)
			if err != nil {
				return err
			}
		}
		output, err = proto.Marshal(&res)
		if err != nil {
			return err
		}

	default:
		return fmt.Errorf("func mismatch")
	}
	var _status map[string]string
	s, ok := current.GetResponseStatus(ctx)
	if ok && s != nil {
		_status = s
	}
	var _context map[string]string
	c, ok := current.GetResponseContext(ctx)
	if ok && c != nil {
		_context = c
	}
	*resp = requestf.ResponsePacket{
		IVersion:     1,
		CPacketType:  0,
		IRequestId:   req.IRequestId,
		IMessageType: 0,
		IRet:         0,
		SBuffer:      tools.ByteToInt8(output),
		Status:       _status,
		SResultDesc:  "",
		Context:      _context,
	}
	return nil
}

// SetGameConfig is client rpc method as defined
func (obj *GameConfigService) SetGameConfig(input SetGameConfigReq, _opt ...map[string]string) (output SetGameConfigRsp, err error) {
	ctx := context.Background()
	return obj.SetGameConfigWithContext(ctx, input, _opt...)
}

// SetGameConfigWithContext is client rpc method as defined
func (obj *GameConfigService) SetGameConfigWithContext(ctx context.Context, input SetGameConfigReq, _opt ...map[string]string) (output SetGameConfigRsp, err error) {
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}

	resp := new(requestf.ResponsePacket)

	err = obj.s.Tars_invoke(ctx, 0, "SetGameConfig", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range resp.Status {
			_status[k] = v
		}
	}

	return output, nil
}

// GetGameConfig is client rpc method as defined
func (obj *GameConfigService) GetGameConfig(input GetGameConfigReq, _opt ...map[string]string) (output GetGameConfigRsp, err error) {
	ctx := context.Background()
	return obj.GetGameConfigWithContext(ctx, input, _opt...)
}

// GetGameConfigWithContext is client rpc method as defined
func (obj *GameConfigService) GetGameConfigWithContext(ctx context.Context, input GetGameConfigReq, _opt ...map[string]string) (output GetGameConfigRsp, err error) {
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}

	resp := new(requestf.ResponsePacket)

	err = obj.s.Tars_invoke(ctx, 0, "GetGameConfig", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range resp.Status {
			_status[k] = v
		}
	}

	return output, nil
}
