// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GoldenEggGame.proto

package redenvelopegame

import (
	context "context"
	fmt "fmt"
	tars "github.com/TarsCloud/TarsGo/tars"
	model "github.com/TarsCloud/TarsGo/tars/model"
	requestf "github.com/TarsCloud/TarsGo/tars/protocol/res/requestf"
	current "github.com/TarsCloud/TarsGo/tars/util/current"
	tools "github.com/TarsCloud/TarsGo/tars/util/tools"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GoldenEggCMD int32

const (
	GoldenEggCMD_GOLDENEGG_LOGIN               GoldenEggCMD = 0
	GoldenEggCMD_GOLDENEGG_LOGOUT              GoldenEggCMD = 1
	GoldenEggCMD_GOLDENEGG_LIVE_SELECTBATCH    GoldenEggCMD = 2
	GoldenEggCMD_GOLDENEGG_CLIENT_SIGN         GoldenEggCMD = 3
	GoldenEggCMD_GOLDENEGG_LIVE_START          GoldenEggCMD = 4
	GoldenEggCMD_GOLDENEGG_CLIENT_OPEN         GoldenEggCMD = 5
	GoldenEggCMD_GOLDENEGG_OVER                GoldenEggCMD = 6
	GoldenEggCMD_GOLDENEGG_CLIENT_WINNER_QUERY GoldenEggCMD = 7
	GoldenEggCMD_GOLDENEGG_LIVE_ACTION         GoldenEggCMD = 8
	GoldenEggCMD_GOLDENEGG_LIVE_MUSIC          GoldenEggCMD = 9
)

var GoldenEggCMD_name = map[int32]string{
	0: "GOLDENEGG_LOGIN",
	1: "GOLDENEGG_LOGOUT",
	2: "GOLDENEGG_LIVE_SELECTBATCH",
	3: "GOLDENEGG_CLIENT_SIGN",
	4: "GOLDENEGG_LIVE_START",
	5: "GOLDENEGG_CLIENT_OPEN",
	6: "GOLDENEGG_OVER",
	7: "GOLDENEGG_CLIENT_WINNER_QUERY",
	8: "GOLDENEGG_LIVE_ACTION",
	9: "GOLDENEGG_LIVE_MUSIC",
}

var GoldenEggCMD_value = map[string]int32{
	"GOLDENEGG_LOGIN":               0,
	"GOLDENEGG_LOGOUT":              1,
	"GOLDENEGG_LIVE_SELECTBATCH":    2,
	"GOLDENEGG_CLIENT_SIGN":         3,
	"GOLDENEGG_LIVE_START":          4,
	"GOLDENEGG_CLIENT_OPEN":         5,
	"GOLDENEGG_OVER":                6,
	"GOLDENEGG_CLIENT_WINNER_QUERY": 7,
	"GOLDENEGG_LIVE_ACTION":         8,
	"GOLDENEGG_LIVE_MUSIC":          9,
}

func (x GoldenEggCMD) String() string {
	return proto.EnumName(GoldenEggCMD_name, int32(x))
}

func (GoldenEggCMD) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{0}
}

//大屏当前游戏状态
type LiveGoldenEggGameInfo struct {
	BatchId              int64                        `protobuf:"varint,1,opt,name=BatchId,proto3" json:"BatchId,omitempty"`
	State                RedEnvelopeBatchStatus       `protobuf:"varint,2,opt,name=State,proto3,enum=RedEnvelopeBatchStatus" json:"State,omitempty"`
	JoinUserCount        int64                        `protobuf:"varint,3,opt,name=JoinUserCount,proto3" json:"JoinUserCount,omitempty"`
	JoinUserList         []*GameUserInfo              `protobuf:"bytes,4,rep,name=JoinUserList,proto3" json:"JoinUserList,omitempty"`
	WinnerList           []*PBRedEnvelopeWinnerRecord `protobuf:"bytes,5,rep,name=WinnerList,proto3" json:"WinnerList,omitempty"`
	PrizeList            []*PBRedEnvelopeItem         `protobuf:"bytes,6,rep,name=PrizeList,proto3" json:"PrizeList,omitempty"`
	SystemTime           int64                        `protobuf:"varint,7,opt,name=SystemTime,proto3" json:"SystemTime,omitempty"`
	StartTime            int64                        `protobuf:"varint,8,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              int64                        `protobuf:"varint,9,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *LiveGoldenEggGameInfo) Reset()         { *m = LiveGoldenEggGameInfo{} }
func (m *LiveGoldenEggGameInfo) String() string { return proto.CompactTextString(m) }
func (*LiveGoldenEggGameInfo) ProtoMessage()    {}
func (*LiveGoldenEggGameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{0}
}

func (m *LiveGoldenEggGameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveGoldenEggGameInfo.Unmarshal(m, b)
}
func (m *LiveGoldenEggGameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveGoldenEggGameInfo.Marshal(b, m, deterministic)
}
func (m *LiveGoldenEggGameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveGoldenEggGameInfo.Merge(m, src)
}
func (m *LiveGoldenEggGameInfo) XXX_Size() int {
	return xxx_messageInfo_LiveGoldenEggGameInfo.Size(m)
}
func (m *LiveGoldenEggGameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveGoldenEggGameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LiveGoldenEggGameInfo proto.InternalMessageInfo

func (m *LiveGoldenEggGameInfo) GetBatchId() int64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

func (m *LiveGoldenEggGameInfo) GetState() RedEnvelopeBatchStatus {
	if m != nil {
		return m.State
	}
	return RedEnvelopeBatchStatus_ALL
}

func (m *LiveGoldenEggGameInfo) GetJoinUserCount() int64 {
	if m != nil {
		return m.JoinUserCount
	}
	return 0
}

func (m *LiveGoldenEggGameInfo) GetJoinUserList() []*GameUserInfo {
	if m != nil {
		return m.JoinUserList
	}
	return nil
}

func (m *LiveGoldenEggGameInfo) GetWinnerList() []*PBRedEnvelopeWinnerRecord {
	if m != nil {
		return m.WinnerList
	}
	return nil
}

func (m *LiveGoldenEggGameInfo) GetPrizeList() []*PBRedEnvelopeItem {
	if m != nil {
		return m.PrizeList
	}
	return nil
}

func (m *LiveGoldenEggGameInfo) GetSystemTime() int64 {
	if m != nil {
		return m.SystemTime
	}
	return 0
}

func (m *LiveGoldenEggGameInfo) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *LiveGoldenEggGameInfo) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

//手机游戏当前状态
type ClientGoldenEggGameInfo struct {
	BatchId              int64                  `protobuf:"varint,1,opt,name=BatchId,proto3" json:"BatchId,omitempty"`
	State                RedEnvelopeBatchStatus `protobuf:"varint,2,opt,name=State,proto3,enum=RedEnvelopeBatchStatus" json:"State,omitempty"`
	JoinCount            int64                  `protobuf:"varint,3,opt,name=JoinCount,proto3" json:"JoinCount,omitempty"`
	SystemTime           int64                  `protobuf:"varint,4,opt,name=SystemTime,proto3" json:"SystemTime,omitempty"`
	StartTime            int64                  `protobuf:"varint,5,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              int64                  `protobuf:"varint,6,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ClientGoldenEggGameInfo) Reset()         { *m = ClientGoldenEggGameInfo{} }
func (m *ClientGoldenEggGameInfo) String() string { return proto.CompactTextString(m) }
func (*ClientGoldenEggGameInfo) ProtoMessage()    {}
func (*ClientGoldenEggGameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{1}
}

func (m *ClientGoldenEggGameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGoldenEggGameInfo.Unmarshal(m, b)
}
func (m *ClientGoldenEggGameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGoldenEggGameInfo.Marshal(b, m, deterministic)
}
func (m *ClientGoldenEggGameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGoldenEggGameInfo.Merge(m, src)
}
func (m *ClientGoldenEggGameInfo) XXX_Size() int {
	return xxx_messageInfo_ClientGoldenEggGameInfo.Size(m)
}
func (m *ClientGoldenEggGameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGoldenEggGameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGoldenEggGameInfo proto.InternalMessageInfo

func (m *ClientGoldenEggGameInfo) GetBatchId() int64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

func (m *ClientGoldenEggGameInfo) GetState() RedEnvelopeBatchStatus {
	if m != nil {
		return m.State
	}
	return RedEnvelopeBatchStatus_ALL
}

func (m *ClientGoldenEggGameInfo) GetJoinCount() int64 {
	if m != nil {
		return m.JoinCount
	}
	return 0
}

func (m *ClientGoldenEggGameInfo) GetSystemTime() int64 {
	if m != nil {
		return m.SystemTime
	}
	return 0
}

func (m *ClientGoldenEggGameInfo) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *ClientGoldenEggGameInfo) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

//cmdid=0时大屏端获取游戏配置和当前游戏状态
type LiveGoldenEggLoginRsp struct {
	Code                 Code                   `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	ClientUrl            string                 `protobuf:"bytes,2,opt,name=ClientUrl,proto3" json:"ClientUrl,omitempty"`
	MusicState           bool                   `protobuf:"varint,3,opt,name=MusicState,proto3" json:"MusicState,omitempty"`
	CurrentGameInfo      *LiveGoldenEggGameInfo `protobuf:"bytes,4,opt,name=CurrentGameInfo,proto3" json:"CurrentGameInfo,omitempty"`
	ConfigList           []*PBGameConfig        `protobuf:"bytes,5,rep,name=ConfigList,proto3" json:"ConfigList,omitempty"`
	BatchList            []*PBRedEnvelopeBatch  `protobuf:"bytes,6,rep,name=BatchList,proto3" json:"BatchList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LiveGoldenEggLoginRsp) Reset()         { *m = LiveGoldenEggLoginRsp{} }
func (m *LiveGoldenEggLoginRsp) String() string { return proto.CompactTextString(m) }
func (*LiveGoldenEggLoginRsp) ProtoMessage()    {}
func (*LiveGoldenEggLoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{2}
}

func (m *LiveGoldenEggLoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveGoldenEggLoginRsp.Unmarshal(m, b)
}
func (m *LiveGoldenEggLoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveGoldenEggLoginRsp.Marshal(b, m, deterministic)
}
func (m *LiveGoldenEggLoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveGoldenEggLoginRsp.Merge(m, src)
}
func (m *LiveGoldenEggLoginRsp) XXX_Size() int {
	return xxx_messageInfo_LiveGoldenEggLoginRsp.Size(m)
}
func (m *LiveGoldenEggLoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveGoldenEggLoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LiveGoldenEggLoginRsp proto.InternalMessageInfo

func (m *LiveGoldenEggLoginRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

func (m *LiveGoldenEggLoginRsp) GetClientUrl() string {
	if m != nil {
		return m.ClientUrl
	}
	return ""
}

func (m *LiveGoldenEggLoginRsp) GetMusicState() bool {
	if m != nil {
		return m.MusicState
	}
	return false
}

func (m *LiveGoldenEggLoginRsp) GetCurrentGameInfo() *LiveGoldenEggGameInfo {
	if m != nil {
		return m.CurrentGameInfo
	}
	return nil
}

func (m *LiveGoldenEggLoginRsp) GetConfigList() []*PBGameConfig {
	if m != nil {
		return m.ConfigList
	}
	return nil
}

func (m *LiveGoldenEggLoginRsp) GetBatchList() []*PBRedEnvelopeBatch {
	if m != nil {
		return m.BatchList
	}
	return nil
}

//cmdid=0时手机端获取游戏配置和当前游戏状态
type ClientGoldenEggLoginRsp struct {
	Code                 Code                     `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	CurrentGameInfo      *ClientGoldenEggGameInfo `protobuf:"bytes,2,opt,name=CurrentGameInfo,proto3" json:"CurrentGameInfo,omitempty"`
	ConfigList           []*PBGameConfig          `protobuf:"bytes,3,rep,name=ConfigList,proto3" json:"ConfigList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ClientGoldenEggLoginRsp) Reset()         { *m = ClientGoldenEggLoginRsp{} }
func (m *ClientGoldenEggLoginRsp) String() string { return proto.CompactTextString(m) }
func (*ClientGoldenEggLoginRsp) ProtoMessage()    {}
func (*ClientGoldenEggLoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{3}
}

func (m *ClientGoldenEggLoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGoldenEggLoginRsp.Unmarshal(m, b)
}
func (m *ClientGoldenEggLoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGoldenEggLoginRsp.Marshal(b, m, deterministic)
}
func (m *ClientGoldenEggLoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGoldenEggLoginRsp.Merge(m, src)
}
func (m *ClientGoldenEggLoginRsp) XXX_Size() int {
	return xxx_messageInfo_ClientGoldenEggLoginRsp.Size(m)
}
func (m *ClientGoldenEggLoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGoldenEggLoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGoldenEggLoginRsp proto.InternalMessageInfo

func (m *ClientGoldenEggLoginRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

func (m *ClientGoldenEggLoginRsp) GetCurrentGameInfo() *ClientGoldenEggGameInfo {
	if m != nil {
		return m.CurrentGameInfo
	}
	return nil
}

func (m *ClientGoldenEggLoginRsp) GetConfigList() []*PBGameConfig {
	if m != nil {
		return m.ConfigList
	}
	return nil
}

//cmdid = 2 大屏批次选择请求
type LiveGoldenEggSelectBatchReq struct {
	BatchId              int64    `protobuf:"varint,1,opt,name=BatchId,proto3" json:"BatchId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiveGoldenEggSelectBatchReq) Reset()         { *m = LiveGoldenEggSelectBatchReq{} }
func (m *LiveGoldenEggSelectBatchReq) String() string { return proto.CompactTextString(m) }
func (*LiveGoldenEggSelectBatchReq) ProtoMessage()    {}
func (*LiveGoldenEggSelectBatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{4}
}

func (m *LiveGoldenEggSelectBatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveGoldenEggSelectBatchReq.Unmarshal(m, b)
}
func (m *LiveGoldenEggSelectBatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveGoldenEggSelectBatchReq.Marshal(b, m, deterministic)
}
func (m *LiveGoldenEggSelectBatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveGoldenEggSelectBatchReq.Merge(m, src)
}
func (m *LiveGoldenEggSelectBatchReq) XXX_Size() int {
	return xxx_messageInfo_LiveGoldenEggSelectBatchReq.Size(m)
}
func (m *LiveGoldenEggSelectBatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveGoldenEggSelectBatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_LiveGoldenEggSelectBatchReq proto.InternalMessageInfo

func (m *LiveGoldenEggSelectBatchReq) GetBatchId() int64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

//cmdid = 2 大屏批次选择请求
type LiveGoldenEggSelectBatchRsp struct {
	Code                 Code                   `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	GameInfo             *LiveGoldenEggGameInfo `protobuf:"bytes,2,opt,name=GameInfo,proto3" json:"GameInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LiveGoldenEggSelectBatchRsp) Reset()         { *m = LiveGoldenEggSelectBatchRsp{} }
func (m *LiveGoldenEggSelectBatchRsp) String() string { return proto.CompactTextString(m) }
func (*LiveGoldenEggSelectBatchRsp) ProtoMessage()    {}
func (*LiveGoldenEggSelectBatchRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{5}
}

func (m *LiveGoldenEggSelectBatchRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveGoldenEggSelectBatchRsp.Unmarshal(m, b)
}
func (m *LiveGoldenEggSelectBatchRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveGoldenEggSelectBatchRsp.Marshal(b, m, deterministic)
}
func (m *LiveGoldenEggSelectBatchRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveGoldenEggSelectBatchRsp.Merge(m, src)
}
func (m *LiveGoldenEggSelectBatchRsp) XXX_Size() int {
	return xxx_messageInfo_LiveGoldenEggSelectBatchRsp.Size(m)
}
func (m *LiveGoldenEggSelectBatchRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveGoldenEggSelectBatchRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LiveGoldenEggSelectBatchRsp proto.InternalMessageInfo

func (m *LiveGoldenEggSelectBatchRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

func (m *LiveGoldenEggSelectBatchRsp) GetGameInfo() *LiveGoldenEggGameInfo {
	if m != nil {
		return m.GameInfo
	}
	return nil
}

//cmdid=2时手机端获取大屏选择批次的信息
type ClientGoldenEggSelectBatchRsp struct {
	Code                 Code                     `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	CurrentGameInfo      *ClientGoldenEggGameInfo `protobuf:"bytes,2,opt,name=CurrentGameInfo,proto3" json:"CurrentGameInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ClientGoldenEggSelectBatchRsp) Reset()         { *m = ClientGoldenEggSelectBatchRsp{} }
func (m *ClientGoldenEggSelectBatchRsp) String() string { return proto.CompactTextString(m) }
func (*ClientGoldenEggSelectBatchRsp) ProtoMessage()    {}
func (*ClientGoldenEggSelectBatchRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{6}
}

func (m *ClientGoldenEggSelectBatchRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGoldenEggSelectBatchRsp.Unmarshal(m, b)
}
func (m *ClientGoldenEggSelectBatchRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGoldenEggSelectBatchRsp.Marshal(b, m, deterministic)
}
func (m *ClientGoldenEggSelectBatchRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGoldenEggSelectBatchRsp.Merge(m, src)
}
func (m *ClientGoldenEggSelectBatchRsp) XXX_Size() int {
	return xxx_messageInfo_ClientGoldenEggSelectBatchRsp.Size(m)
}
func (m *ClientGoldenEggSelectBatchRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGoldenEggSelectBatchRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGoldenEggSelectBatchRsp proto.InternalMessageInfo

func (m *ClientGoldenEggSelectBatchRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

func (m *ClientGoldenEggSelectBatchRsp) GetCurrentGameInfo() *ClientGoldenEggGameInfo {
	if m != nil {
		return m.CurrentGameInfo
	}
	return nil
}

//cmdid = 3 大屏端获取参与人数
type LiveGoldenEggSignRsp struct {
	Code                 Code     `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	JoinCount            int64    `protobuf:"varint,2,opt,name=JoinCount,proto3" json:"JoinCount,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiveGoldenEggSignRsp) Reset()         { *m = LiveGoldenEggSignRsp{} }
func (m *LiveGoldenEggSignRsp) String() string { return proto.CompactTextString(m) }
func (*LiveGoldenEggSignRsp) ProtoMessage()    {}
func (*LiveGoldenEggSignRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{7}
}

func (m *LiveGoldenEggSignRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveGoldenEggSignRsp.Unmarshal(m, b)
}
func (m *LiveGoldenEggSignRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveGoldenEggSignRsp.Marshal(b, m, deterministic)
}
func (m *LiveGoldenEggSignRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveGoldenEggSignRsp.Merge(m, src)
}
func (m *LiveGoldenEggSignRsp) XXX_Size() int {
	return xxx_messageInfo_LiveGoldenEggSignRsp.Size(m)
}
func (m *LiveGoldenEggSignRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveGoldenEggSignRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LiveGoldenEggSignRsp proto.InternalMessageInfo

func (m *LiveGoldenEggSignRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

func (m *LiveGoldenEggSignRsp) GetJoinCount() int64 {
	if m != nil {
		return m.JoinCount
	}
	return 0
}

func (m *LiveGoldenEggSignRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LiveGoldenEggSignRsp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LiveGoldenEggSignRsp) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

//cmdid = 3 手机端参与人数更新
type ClientGoldenEggSignRsp struct {
	Code                 Code     `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	JoinCount            int64    `protobuf:"varint,2,opt,name=JoinCount,proto3" json:"JoinCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientGoldenEggSignRsp) Reset()         { *m = ClientGoldenEggSignRsp{} }
func (m *ClientGoldenEggSignRsp) String() string { return proto.CompactTextString(m) }
func (*ClientGoldenEggSignRsp) ProtoMessage()    {}
func (*ClientGoldenEggSignRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{8}
}

func (m *ClientGoldenEggSignRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGoldenEggSignRsp.Unmarshal(m, b)
}
func (m *ClientGoldenEggSignRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGoldenEggSignRsp.Marshal(b, m, deterministic)
}
func (m *ClientGoldenEggSignRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGoldenEggSignRsp.Merge(m, src)
}
func (m *ClientGoldenEggSignRsp) XXX_Size() int {
	return xxx_messageInfo_ClientGoldenEggSignRsp.Size(m)
}
func (m *ClientGoldenEggSignRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGoldenEggSignRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGoldenEggSignRsp proto.InternalMessageInfo

func (m *ClientGoldenEggSignRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

func (m *ClientGoldenEggSignRsp) GetJoinCount() int64 {
	if m != nil {
		return m.JoinCount
	}
	return 0
}

//cmdid =4 大屏开始游戏
type LiveGoldenEggStartReq struct {
	BatchId              int64    `protobuf:"varint,1,opt,name=BatchId,proto3" json:"BatchId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiveGoldenEggStartReq) Reset()         { *m = LiveGoldenEggStartReq{} }
func (m *LiveGoldenEggStartReq) String() string { return proto.CompactTextString(m) }
func (*LiveGoldenEggStartReq) ProtoMessage()    {}
func (*LiveGoldenEggStartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{9}
}

func (m *LiveGoldenEggStartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveGoldenEggStartReq.Unmarshal(m, b)
}
func (m *LiveGoldenEggStartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveGoldenEggStartReq.Marshal(b, m, deterministic)
}
func (m *LiveGoldenEggStartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveGoldenEggStartReq.Merge(m, src)
}
func (m *LiveGoldenEggStartReq) XXX_Size() int {
	return xxx_messageInfo_LiveGoldenEggStartReq.Size(m)
}
func (m *LiveGoldenEggStartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveGoldenEggStartReq.DiscardUnknown(m)
}

var xxx_messageInfo_LiveGoldenEggStartReq proto.InternalMessageInfo

func (m *LiveGoldenEggStartReq) GetBatchId() int64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

//cmdid = 4时游戏开始的通知
//cmdid = 6时游戏结束的通知
type GoldenEggStateChangeRsp struct {
	Code                 Code                   `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	BatchId              int64                  `protobuf:"varint,2,opt,name=BatchId,proto3" json:"BatchId,omitempty"`
	State                RedEnvelopeBatchStatus `protobuf:"varint,3,opt,name=State,proto3,enum=RedEnvelopeBatchStatus" json:"State,omitempty"`
	SystemTime           int64                  `protobuf:"varint,4,opt,name=SystemTime,proto3" json:"SystemTime,omitempty"`
	StartTime            int64                  `protobuf:"varint,5,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              int64                  `protobuf:"varint,6,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GoldenEggStateChangeRsp) Reset()         { *m = GoldenEggStateChangeRsp{} }
func (m *GoldenEggStateChangeRsp) String() string { return proto.CompactTextString(m) }
func (*GoldenEggStateChangeRsp) ProtoMessage()    {}
func (*GoldenEggStateChangeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{10}
}

func (m *GoldenEggStateChangeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoldenEggStateChangeRsp.Unmarshal(m, b)
}
func (m *GoldenEggStateChangeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoldenEggStateChangeRsp.Marshal(b, m, deterministic)
}
func (m *GoldenEggStateChangeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoldenEggStateChangeRsp.Merge(m, src)
}
func (m *GoldenEggStateChangeRsp) XXX_Size() int {
	return xxx_messageInfo_GoldenEggStateChangeRsp.Size(m)
}
func (m *GoldenEggStateChangeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GoldenEggStateChangeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GoldenEggStateChangeRsp proto.InternalMessageInfo

func (m *GoldenEggStateChangeRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

func (m *GoldenEggStateChangeRsp) GetBatchId() int64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

func (m *GoldenEggStateChangeRsp) GetState() RedEnvelopeBatchStatus {
	if m != nil {
		return m.State
	}
	return RedEnvelopeBatchStatus_ALL
}

func (m *GoldenEggStateChangeRsp) GetSystemTime() int64 {
	if m != nil {
		return m.SystemTime
	}
	return 0
}

func (m *GoldenEggStateChangeRsp) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GoldenEggStateChangeRsp) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

//cmdid = 5手机端提交开奖申请
type ClientGoldenEggOpenReq struct {
	BatchId              int64    `protobuf:"varint,1,opt,name=BatchId,proto3" json:"BatchId,omitempty"`
	UserOpenId           string   `protobuf:"bytes,2,opt,name=UserOpenId,proto3" json:"UserOpenId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientGoldenEggOpenReq) Reset()         { *m = ClientGoldenEggOpenReq{} }
func (m *ClientGoldenEggOpenReq) String() string { return proto.CompactTextString(m) }
func (*ClientGoldenEggOpenReq) ProtoMessage()    {}
func (*ClientGoldenEggOpenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{11}
}

func (m *ClientGoldenEggOpenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGoldenEggOpenReq.Unmarshal(m, b)
}
func (m *ClientGoldenEggOpenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGoldenEggOpenReq.Marshal(b, m, deterministic)
}
func (m *ClientGoldenEggOpenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGoldenEggOpenReq.Merge(m, src)
}
func (m *ClientGoldenEggOpenReq) XXX_Size() int {
	return xxx_messageInfo_ClientGoldenEggOpenReq.Size(m)
}
func (m *ClientGoldenEggOpenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGoldenEggOpenReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGoldenEggOpenReq proto.InternalMessageInfo

func (m *ClientGoldenEggOpenReq) GetBatchId() int64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

func (m *ClientGoldenEggOpenReq) GetUserOpenId() string {
	if m != nil {
		return m.UserOpenId
	}
	return ""
}

//cmdid = 5手机端提交开奖结果
type ClientGoldenEggOpenRsp struct {
	Code                 Code                       `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	Prize                *PBRedEnvelopeWinnerRecord `protobuf:"bytes,2,opt,name=Prize,proto3" json:"Prize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClientGoldenEggOpenRsp) Reset()         { *m = ClientGoldenEggOpenRsp{} }
func (m *ClientGoldenEggOpenRsp) String() string { return proto.CompactTextString(m) }
func (*ClientGoldenEggOpenRsp) ProtoMessage()    {}
func (*ClientGoldenEggOpenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{12}
}

func (m *ClientGoldenEggOpenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGoldenEggOpenRsp.Unmarshal(m, b)
}
func (m *ClientGoldenEggOpenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGoldenEggOpenRsp.Marshal(b, m, deterministic)
}
func (m *ClientGoldenEggOpenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGoldenEggOpenRsp.Merge(m, src)
}
func (m *ClientGoldenEggOpenRsp) XXX_Size() int {
	return xxx_messageInfo_ClientGoldenEggOpenRsp.Size(m)
}
func (m *ClientGoldenEggOpenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGoldenEggOpenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGoldenEggOpenRsp proto.InternalMessageInfo

func (m *ClientGoldenEggOpenRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

func (m *ClientGoldenEggOpenRsp) GetPrize() *PBRedEnvelopeWinnerRecord {
	if m != nil {
		return m.Prize
	}
	return nil
}

//cmdid = 5大屏端中奖记录
type LiveGoldenEggOpenRsp struct {
	Code                 Code                       `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	UserId               int64                      `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string                     `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	Avatar               string                     `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Prize                *PBRedEnvelopeWinnerRecord `protobuf:"bytes,5,opt,name=Prize,proto3" json:"Prize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *LiveGoldenEggOpenRsp) Reset()         { *m = LiveGoldenEggOpenRsp{} }
func (m *LiveGoldenEggOpenRsp) String() string { return proto.CompactTextString(m) }
func (*LiveGoldenEggOpenRsp) ProtoMessage()    {}
func (*LiveGoldenEggOpenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{13}
}

func (m *LiveGoldenEggOpenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveGoldenEggOpenRsp.Unmarshal(m, b)
}
func (m *LiveGoldenEggOpenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveGoldenEggOpenRsp.Marshal(b, m, deterministic)
}
func (m *LiveGoldenEggOpenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveGoldenEggOpenRsp.Merge(m, src)
}
func (m *LiveGoldenEggOpenRsp) XXX_Size() int {
	return xxx_messageInfo_LiveGoldenEggOpenRsp.Size(m)
}
func (m *LiveGoldenEggOpenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveGoldenEggOpenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LiveGoldenEggOpenRsp proto.InternalMessageInfo

func (m *LiveGoldenEggOpenRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

func (m *LiveGoldenEggOpenRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LiveGoldenEggOpenRsp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LiveGoldenEggOpenRsp) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *LiveGoldenEggOpenRsp) GetPrize() *PBRedEnvelopeWinnerRecord {
	if m != nil {
		return m.Prize
	}
	return nil
}

//cmdid =6 大屏结束游戏
type LiveGoldenEggOverReq struct {
	BatchId              int64    `protobuf:"varint,1,opt,name=BatchId,proto3" json:"BatchId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiveGoldenEggOverReq) Reset()         { *m = LiveGoldenEggOverReq{} }
func (m *LiveGoldenEggOverReq) String() string { return proto.CompactTextString(m) }
func (*LiveGoldenEggOverReq) ProtoMessage()    {}
func (*LiveGoldenEggOverReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{14}
}

func (m *LiveGoldenEggOverReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveGoldenEggOverReq.Unmarshal(m, b)
}
func (m *LiveGoldenEggOverReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveGoldenEggOverReq.Marshal(b, m, deterministic)
}
func (m *LiveGoldenEggOverReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveGoldenEggOverReq.Merge(m, src)
}
func (m *LiveGoldenEggOverReq) XXX_Size() int {
	return xxx_messageInfo_LiveGoldenEggOverReq.Size(m)
}
func (m *LiveGoldenEggOverReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveGoldenEggOverReq.DiscardUnknown(m)
}

var xxx_messageInfo_LiveGoldenEggOverReq proto.InternalMessageInfo

func (m *LiveGoldenEggOverReq) GetBatchId() int64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

//cmdid = 7 手机端获取该轮中奖纪录申请
type ClientGoldenEggWinnerReq struct {
	BatchId              int64    `protobuf:"varint,1,opt,name=BatchId,proto3" json:"BatchId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientGoldenEggWinnerReq) Reset()         { *m = ClientGoldenEggWinnerReq{} }
func (m *ClientGoldenEggWinnerReq) String() string { return proto.CompactTextString(m) }
func (*ClientGoldenEggWinnerReq) ProtoMessage()    {}
func (*ClientGoldenEggWinnerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{15}
}

func (m *ClientGoldenEggWinnerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGoldenEggWinnerReq.Unmarshal(m, b)
}
func (m *ClientGoldenEggWinnerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGoldenEggWinnerReq.Marshal(b, m, deterministic)
}
func (m *ClientGoldenEggWinnerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGoldenEggWinnerReq.Merge(m, src)
}
func (m *ClientGoldenEggWinnerReq) XXX_Size() int {
	return xxx_messageInfo_ClientGoldenEggWinnerReq.Size(m)
}
func (m *ClientGoldenEggWinnerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGoldenEggWinnerReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGoldenEggWinnerReq proto.InternalMessageInfo

func (m *ClientGoldenEggWinnerReq) GetBatchId() int64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

//cmdid = 7 手机端获取该轮中奖纪录申请
type ClientGoldenEggWinnerRsp struct {
	Code                 Code                         `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	List                 []*PBRedEnvelopeWinnerRecord `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ClientGoldenEggWinnerRsp) Reset()         { *m = ClientGoldenEggWinnerRsp{} }
func (m *ClientGoldenEggWinnerRsp) String() string { return proto.CompactTextString(m) }
func (*ClientGoldenEggWinnerRsp) ProtoMessage()    {}
func (*ClientGoldenEggWinnerRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{16}
}

func (m *ClientGoldenEggWinnerRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGoldenEggWinnerRsp.Unmarshal(m, b)
}
func (m *ClientGoldenEggWinnerRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGoldenEggWinnerRsp.Marshal(b, m, deterministic)
}
func (m *ClientGoldenEggWinnerRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGoldenEggWinnerRsp.Merge(m, src)
}
func (m *ClientGoldenEggWinnerRsp) XXX_Size() int {
	return xxx_messageInfo_ClientGoldenEggWinnerRsp.Size(m)
}
func (m *ClientGoldenEggWinnerRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGoldenEggWinnerRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGoldenEggWinnerRsp proto.InternalMessageInfo

func (m *ClientGoldenEggWinnerRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

func (m *ClientGoldenEggWinnerRsp) GetList() []*PBRedEnvelopeWinnerRecord {
	if m != nil {
		return m.List
	}
	return nil
}

//cmdid = 8 大屏端操作命令
type LiveGoldenEggActionReq struct {
	ActionData           string   `protobuf:"bytes,1,opt,name=ActionData,proto3" json:"ActionData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiveGoldenEggActionReq) Reset()         { *m = LiveGoldenEggActionReq{} }
func (m *LiveGoldenEggActionReq) String() string { return proto.CompactTextString(m) }
func (*LiveGoldenEggActionReq) ProtoMessage()    {}
func (*LiveGoldenEggActionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{17}
}

func (m *LiveGoldenEggActionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveGoldenEggActionReq.Unmarshal(m, b)
}
func (m *LiveGoldenEggActionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveGoldenEggActionReq.Marshal(b, m, deterministic)
}
func (m *LiveGoldenEggActionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveGoldenEggActionReq.Merge(m, src)
}
func (m *LiveGoldenEggActionReq) XXX_Size() int {
	return xxx_messageInfo_LiveGoldenEggActionReq.Size(m)
}
func (m *LiveGoldenEggActionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveGoldenEggActionReq.DiscardUnknown(m)
}

var xxx_messageInfo_LiveGoldenEggActionReq proto.InternalMessageInfo

func (m *LiveGoldenEggActionReq) GetActionData() string {
	if m != nil {
		return m.ActionData
	}
	return ""
}

//cmdid = 8 大屏端返回命令
type LiveGoldenEggActionRsp struct {
	Code                 Code     `protobuf:"varint,1,opt,name=Code,proto3,enum=Code" json:"Code,omitempty"`
	ActionData           string   `protobuf:"bytes,2,opt,name=ActionData,proto3" json:"ActionData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiveGoldenEggActionRsp) Reset()         { *m = LiveGoldenEggActionRsp{} }
func (m *LiveGoldenEggActionRsp) String() string { return proto.CompactTextString(m) }
func (*LiveGoldenEggActionRsp) ProtoMessage()    {}
func (*LiveGoldenEggActionRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8c7afc5af7175a8, []int{18}
}

func (m *LiveGoldenEggActionRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiveGoldenEggActionRsp.Unmarshal(m, b)
}
func (m *LiveGoldenEggActionRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiveGoldenEggActionRsp.Marshal(b, m, deterministic)
}
func (m *LiveGoldenEggActionRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiveGoldenEggActionRsp.Merge(m, src)
}
func (m *LiveGoldenEggActionRsp) XXX_Size() int {
	return xxx_messageInfo_LiveGoldenEggActionRsp.Size(m)
}
func (m *LiveGoldenEggActionRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LiveGoldenEggActionRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LiveGoldenEggActionRsp proto.InternalMessageInfo

func (m *LiveGoldenEggActionRsp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_NOT_USE
}

func (m *LiveGoldenEggActionRsp) GetActionData() string {
	if m != nil {
		return m.ActionData
	}
	return ""
}

func init() {
	proto.RegisterEnum("goldenegggame.GoldenEggCMD", GoldenEggCMD_name, GoldenEggCMD_value)
	proto.RegisterType((*LiveGoldenEggGameInfo)(nil), "goldenegggame.LiveGoldenEggGameInfo")
	proto.RegisterType((*ClientGoldenEggGameInfo)(nil), "goldenegggame.ClientGoldenEggGameInfo")
	proto.RegisterType((*LiveGoldenEggLoginRsp)(nil), "goldenegggame.LiveGoldenEggLoginRsp")
	proto.RegisterType((*ClientGoldenEggLoginRsp)(nil), "goldenegggame.ClientGoldenEggLoginRsp")
	proto.RegisterType((*LiveGoldenEggSelectBatchReq)(nil), "goldenegggame.LiveGoldenEggSelectBatchReq")
	proto.RegisterType((*LiveGoldenEggSelectBatchRsp)(nil), "goldenegggame.LiveGoldenEggSelectBatchRsp")
	proto.RegisterType((*ClientGoldenEggSelectBatchRsp)(nil), "goldenegggame.ClientGoldenEggSelectBatchRsp")
	proto.RegisterType((*LiveGoldenEggSignRsp)(nil), "goldenegggame.LiveGoldenEggSignRsp")
	proto.RegisterType((*ClientGoldenEggSignRsp)(nil), "goldenegggame.ClientGoldenEggSignRsp")
	proto.RegisterType((*LiveGoldenEggStartReq)(nil), "goldenegggame.LiveGoldenEggStartReq")
	proto.RegisterType((*GoldenEggStateChangeRsp)(nil), "goldenegggame.GoldenEggStateChangeRsp")
	proto.RegisterType((*ClientGoldenEggOpenReq)(nil), "goldenegggame.ClientGoldenEggOpenReq")
	proto.RegisterType((*ClientGoldenEggOpenRsp)(nil), "goldenegggame.ClientGoldenEggOpenRsp")
	proto.RegisterType((*LiveGoldenEggOpenRsp)(nil), "goldenegggame.LiveGoldenEggOpenRsp")
	proto.RegisterType((*LiveGoldenEggOverReq)(nil), "goldenegggame.LiveGoldenEggOverReq")
	proto.RegisterType((*ClientGoldenEggWinnerReq)(nil), "goldenegggame.ClientGoldenEggWinnerReq")
	proto.RegisterType((*ClientGoldenEggWinnerRsp)(nil), "goldenegggame.ClientGoldenEggWinnerRsp")
	proto.RegisterType((*LiveGoldenEggActionReq)(nil), "goldenegggame.LiveGoldenEggActionReq")
	proto.RegisterType((*LiveGoldenEggActionRsp)(nil), "goldenegggame.LiveGoldenEggActionRsp")
}

func init() { proto.RegisterFile("GoldenEggGame.proto", fileDescriptor_c8c7afc5af7175a8) }

var fileDescriptor_c8c7afc5af7175a8 = []byte{
	// 966 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x2e, 0xa9, 0x1f, 0x8b, 0xe3, 0x3f, 0x62, 0xe5, 0xd8, 0x8a, 0x9a, 0x18, 0x2e, 0x11, 0x14,
	0x46, 0x81, 0x10, 0xb6, 0x52, 0xa0, 0x45, 0x7b, 0xa9, 0x45, 0x13, 0x2a, 0x0b, 0x99, 0x52, 0x96,
	0x52, 0x82, 0xf6, 0x62, 0xb0, 0xd2, 0x86, 0x21, 0x20, 0x91, 0x0e, 0xb5, 0x12, 0xd0, 0x3c, 0x41,
	0x0f, 0xbd, 0xf6, 0xd4, 0x5b, 0x5f, 0xa0, 0xa7, 0x3e, 0x4a, 0x81, 0xbe, 0x4d, 0x8b, 0x5d, 0x52,
	0x26, 0xb9, 0x92, 0x68, 0x01, 0x6d, 0x6e, 0x9a, 0x6f, 0x66, 0x76, 0xe7, 0xfb, 0x76, 0x66, 0xb9,
	0x82, 0x7a, 0x27, 0x9c, 0x8c, 0x49, 0x60, 0x7a, 0x5e, 0xc7, 0x9d, 0x12, 0xfd, 0x2e, 0x0a, 0x69,
	0x88, 0xf6, 0x3d, 0x0e, 0x12, 0xcf, 0xf3, 0xdc, 0x29, 0x69, 0xaa, 0xcc, 0x65, 0x84, 0xc1, 0x1b,
	0xdf, 0x8b, 0x03, 0x9a, 0x07, 0x0c, 0xb9, 0x76, 0xa9, 0x9b, 0xd8, 0xc7, 0x98, 0x8c, 0xcd, 0x60,
	0x41, 0x26, 0xe1, 0x1d, 0xe9, 0x47, 0xfe, 0xfb, 0x64, 0xa1, 0xe6, 0x9e, 0x11, 0x4e, 0xa7, 0x61,
	0x10, 0x5b, 0xda, 0x3f, 0x32, 0x3c, 0xea, 0xfa, 0x0b, 0x92, 0xdb, 0xd2, 0x0a, 0xde, 0x84, 0xa8,
	0x01, 0x3b, 0x6d, 0x97, 0x8e, 0xde, 0x5a, 0xe3, 0x86, 0x74, 0x26, 0x9d, 0x97, 0xf0, 0xd2, 0x44,
	0xcf, 0xa1, 0xe2, 0x50, 0x97, 0x92, 0x86, 0x7c, 0x26, 0x9d, 0x1f, 0xb4, 0x4e, 0xf4, 0xcc, 0x4e,
	0x3c, 0x86, 0x79, 0xe7, 0x33, 0x1c, 0x47, 0xa1, 0x67, 0xb0, 0xff, 0x5d, 0xe8, 0x07, 0xc3, 0x19,
	0x89, 0x8c, 0x70, 0x1e, 0xd0, 0x46, 0x89, 0x2f, 0x97, 0x07, 0xd1, 0x25, 0xec, 0x2d, 0x81, 0xae,
	0x3f, 0xa3, 0x8d, 0xf2, 0x59, 0xe9, 0x7c, 0xb7, 0xb5, 0xaf, 0xb3, 0x7a, 0x18, 0xc8, 0x6a, 0xc2,
	0xb9, 0x10, 0xf4, 0x15, 0xc0, 0x6b, 0x3f, 0x08, 0x92, 0x84, 0x0a, 0x4f, 0x68, 0xea, 0xfd, 0x76,
	0xa6, 0x9c, 0xd8, 0x8f, 0xc9, 0x28, 0x8c, 0xc6, 0x38, 0x13, 0x8d, 0x2e, 0x40, 0xe1, 0xa2, 0xf0,
	0xd4, 0x2a, 0x4f, 0x45, 0xf9, 0x54, 0x8b, 0x92, 0x29, 0x4e, 0x83, 0xd0, 0x29, 0x80, 0xf3, 0xd3,
	0x8c, 0x92, 0xe9, 0xc0, 0x9f, 0x92, 0xc6, 0x0e, 0xe7, 0x90, 0x41, 0xd0, 0x13, 0x50, 0x1c, 0xea,
	0x46, 0x94, 0xbb, 0x6b, 0xdc, 0x9d, 0x02, 0x4c, 0x4d, 0x33, 0x18, 0x73, 0x9f, 0x12, 0xab, 0x99,
	0x98, 0xda, 0xdf, 0x12, 0x9c, 0x18, 0x13, 0x9f, 0x04, 0xf4, 0x03, 0x9e, 0xc1, 0x13, 0x50, 0x98,
	0x74, 0x59, 0xfd, 0x53, 0x40, 0xa0, 0x56, 0x2e, 0xa6, 0x56, 0x29, 0xa0, 0x56, 0xcd, 0x53, 0xfb,
	0x5d, 0x6c, 0xae, 0x6e, 0xe8, 0xf9, 0x01, 0x9e, 0xdd, 0xa1, 0xc7, 0x50, 0x36, 0xc2, 0x31, 0xe1,
	0xac, 0x0e, 0x5a, 0x15, 0x9d, 0x19, 0x98, 0x43, 0x6c, 0xb3, 0x58, 0x8e, 0x61, 0x34, 0xe1, 0xec,
	0x14, 0x9c, 0x02, 0xac, 0xd4, 0x9b, 0xf9, 0xcc, 0x1f, 0xc5, 0xe4, 0x19, 0x93, 0x1a, 0xce, 0x20,
	0xc8, 0x86, 0x43, 0x63, 0x1e, 0x45, 0x4c, 0xcd, 0x44, 0x44, 0xce, 0x67, 0xb7, 0xf5, 0x4c, 0xcf,
	0x0d, 0x90, 0xbe, 0xb6, 0xe9, 0xb1, 0x98, 0x8c, 0x9e, 0x03, 0xc4, 0x53, 0x96, 0xe9, 0xb1, 0x7d,
	0xbd, 0xdf, 0x4e, 0xc7, 0x0f, 0x67, 0x02, 0xd0, 0x25, 0x28, 0x5c, 0xfd, 0x4c, 0x5b, 0xd5, 0xf3,
	0x6d, 0xc5, 0xdd, 0x38, 0x8d, 0xd2, 0xfe, 0x5c, 0x3d, 0xff, 0x6d, 0x64, 0xea, 0xaf, 0x12, 0x95,
	0x39, 0xd1, 0x4f, 0x05, 0xa2, 0x1b, 0x7a, 0xeb, 0x21, 0xaa, 0xa5, 0x07, 0xa8, 0x6a, 0x5f, 0xc0,
	0xc7, 0x39, 0x0d, 0x1d, 0x32, 0x21, 0x23, 0x1a, 0xd3, 0x23, 0xef, 0x36, 0xb7, 0xae, 0xf6, 0xbe,
	0x20, 0xb1, 0x98, 0xf3, 0x37, 0x50, 0x13, 0xc8, 0x6e, 0x77, 0xaa, 0xf7, 0x59, 0xda, 0x2f, 0x12,
	0x3c, 0x15, 0x04, 0xd9, 0x7e, 0xfb, 0xff, 0x5d, 0x72, 0xed, 0x37, 0x09, 0x8e, 0xf2, 0x5a, 0xf8,
	0xde, 0x16, 0xf3, 0x91, 0x8e, 0xb2, 0x2c, 0x8e, 0xf2, 0x31, 0x54, 0xe7, 0xec, 0xb6, 0x1c, 0x27,
	0x53, 0x9e, 0x58, 0xa8, 0x09, 0x35, 0xf6, 0xcb, 0x76, 0x93, 0x01, 0x57, 0xf0, 0xbd, 0xcd, 0x72,
	0xdc, 0x85, 0x4b, 0xdd, 0x88, 0xcf, 0xb6, 0x82, 0x13, 0x4b, 0x7b, 0x09, 0xc7, 0xa2, 0x56, 0xff,
	0xb1, 0x3c, 0xed, 0x52, 0xb8, 0x10, 0xf8, 0x2d, 0x52, 0xdc, 0x2e, 0x7f, 0x49, 0x70, 0x92, 0x8d,
	0xa7, 0xc4, 0x78, 0xeb, 0x06, 0x1e, 0x79, 0xa0, 0x8e, 0xcc, 0x82, 0xf2, 0x86, 0xab, 0xb3, 0xb4,
	0xd5, 0xd5, 0xf9, 0xa1, 0x2e, 0x47, 0xbc, 0xa2, 0x6e, 0xef, 0x8e, 0x04, 0x85, 0x5a, 0xb0, 0x5a,
	0xd8, 0xd7, 0x8f, 0x05, 0x26, 0xbc, 0x14, 0x9c, 0x41, 0x34, 0xb2, 0x7e, 0xcd, 0x62, 0xa5, 0x2e,
	0xa0, 0xc2, 0xbf, 0x72, 0x49, 0x33, 0x17, 0x7d, 0x41, 0xe3, 0x40, 0xed, 0x0f, 0xb1, 0x6d, 0xb7,
	0xd8, 0x25, 0x6d, 0x4c, 0x79, 0x63, 0x63, 0x96, 0x36, 0x36, 0x66, 0x39, 0xdb, 0x98, 0x69, 0xc5,
	0x95, 0x6d, 0x2b, 0xbe, 0x10, 0x0b, 0x5e, 0xb0, 0x88, 0xa2, 0xb6, 0xfb, 0x1c, 0x1a, 0x82, 0x94,
	0xcb, 0x75, 0x8b, 0xb2, 0xc8, 0xa6, 0xac, 0x62, 0x71, 0x74, 0x28, 0xf3, 0x4b, 0x57, 0x7e, 0xf0,
	0x0d, 0xc3, 0xe3, 0xb4, 0x2f, 0xe1, 0x38, 0x47, 0xe7, 0x6a, 0x44, 0xfd, 0x90, 0xf7, 0xce, 0x29,
	0x40, 0x6c, 0xb0, 0x97, 0x20, 0xdf, 0x4a, 0xc1, 0x19, 0x44, 0x73, 0xd6, 0x67, 0x16, 0x97, 0x97,
	0x5f, 0x54, 0x16, 0x17, 0xfd, 0xec, 0x57, 0x19, 0xf6, 0xee, 0x57, 0x34, 0x6e, 0xae, 0x51, 0x1d,
	0x0e, 0x3b, 0xbd, 0xee, 0xb5, 0x69, 0x9b, 0x9d, 0xce, 0x6d, 0xb7, 0xd7, 0xb1, 0x6c, 0xf5, 0x23,
	0x74, 0x04, 0x6a, 0x0e, 0xec, 0x0d, 0x07, 0xaa, 0x84, 0x4e, 0xa1, 0x99, 0x41, 0xad, 0x57, 0xe6,
	0xad, 0x63, 0x76, 0x4d, 0x63, 0xd0, 0xbe, 0x1a, 0x18, 0xdf, 0xaa, 0x32, 0x7a, 0x0c, 0x8f, 0x52,
	0xbf, 0xd1, 0xb5, 0x4c, 0x7b, 0x70, 0xeb, 0x58, 0x1d, 0x5b, 0x2d, 0xa1, 0x06, 0x1c, 0x89, 0xa9,
	0x83, 0x2b, 0x3c, 0x50, 0xcb, 0x6b, 0x93, 0x7a, 0x7d, 0xd3, 0x56, 0x2b, 0x08, 0xc1, 0x41, 0xea,
	0xea, 0xbd, 0x32, 0xb1, 0x5a, 0x45, 0x9f, 0xc0, 0xd3, 0x95, 0xf0, 0xd7, 0x96, 0x6d, 0x9b, 0xf8,
	0xf6, 0xe5, 0xd0, 0xc4, 0xdf, 0xab, 0x3b, 0xf9, 0x15, 0xf9, 0x5e, 0x57, 0xc6, 0xc0, 0xea, 0xd9,
	0x6a, 0x6d, 0x4d, 0x19, 0x37, 0x43, 0xc7, 0x32, 0x54, 0xa5, 0xf5, 0xb3, 0x04, 0x47, 0xb9, 0xaf,
	0x80, 0x43, 0xa2, 0x85, 0x3f, 0x22, 0xe8, 0x6b, 0xa8, 0x63, 0x32, 0x22, 0xfe, 0x82, 0x3f, 0x6d,
	0x97, 0x0f, 0x77, 0xc4, 0xae, 0xa2, 0x15, 0x14, 0x93, 0x77, 0xcd, 0xdd, 0xa5, 0x83, 0x1d, 0xd4,
	0x0b, 0x38, 0x4c, 0x2c, 0x76, 0x92, 0x3c, 0xb1, 0xae, 0x0b, 0x88, 0x98, 0xd4, 0x3e, 0xfc, 0x21,
	0xff, 0x07, 0xe2, 0xc7, 0x2a, 0x7f, 0xff, 0xbf, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x51,
	0x3a, 0x97, 0x6d, 0x0c, 0x00, 0x00,
}

// This following code was generated by tarsrpc
// Gernerated from GoldenEggGame.proto
type GoldenEggGameService struct {
	s model.Servant
}

//SetServant is required by the servant interface.
func (obj *GoldenEggGameService) SetServant(s model.Servant) {
	obj.s = s
}

//AddServant is required by the servant interface
func (obj *GoldenEggGameService) AddServant(imp impGoldenEggGameService, objStr string) {
	tars.AddServant(obj, imp, objStr)
}

////AddServant adds servant  for the service with context
func (obj *GoldenEggGameService) AddServantWithContext(imp impGoldenEggGameServiceWithContext, objStr string) {
	tars.AddServantWithContext(obj, imp, objStr)
}

//TarsSetTimeout is required by the servant interface. t is the timeout in ms.
func (obj *GoldenEggGameService) TarsSetTimeout(t int) {
	obj.s.TarsSetTimeout(t)
}

//TarsSetProtocol is required by the servant interface. t is the protocol.
func (obj *GoldenEggGameService) TarsSetProtocol(p model.Protocol) {
	obj.s.TarsSetProtocol(p)
}

type impGoldenEggGameService interface {
	ReceiveUserGameData(input ReceiveUserGameDataReq) (output ReceiveRsp, err error)
	ReceiveLiveData(input ReceiveLiveDataReq) (output ReceiveRsp, err error)
}

type impGoldenEggGameServiceWithContext interface {
	ReceiveUserGameData(ctx context.Context, input ReceiveUserGameDataReq) (output ReceiveRsp, err error)
	ReceiveLiveData(ctx context.Context, input ReceiveLiveDataReq) (output ReceiveRsp, err error)
}

//Dispatch is used to call the user implement of the defined method.
func (obj *GoldenEggGameService) Dispatch(ctx context.Context, val interface{}, req *requestf.RequestPacket, resp *requestf.ResponsePacket, withContext bool) (err error) {
	input := tools.Int8ToByte(req.SBuffer)
	var output []byte
	funcName := req.SFuncName
	switch funcName {

	case "ReceiveUserGameData":
		inputDefine := ReceiveUserGameDataReq{}
		if err = proto.Unmarshal(input, &inputDefine); err != nil {
			return err
		}
		var res ReceiveRsp
		if withContext == false {
			imp := val.(impGoldenEggGameService)
			res, err = imp.ReceiveUserGameData(inputDefine)
			if err != nil {
				return err
			}
		} else {
			imp := val.(impGoldenEggGameServiceWithContext)
			res, err = imp.ReceiveUserGameData(ctx, inputDefine)
			if err != nil {
				return err
			}
		}
		output, err = proto.Marshal(&res)
		if err != nil {
			return err
		}

	case "ReceiveLiveData":
		inputDefine := ReceiveLiveDataReq{}
		if err = proto.Unmarshal(input, &inputDefine); err != nil {
			return err
		}
		var res ReceiveRsp
		if withContext == false {
			imp := val.(impGoldenEggGameService)
			res, err = imp.ReceiveLiveData(inputDefine)
			if err != nil {
				return err
			}
		} else {
			imp := val.(impGoldenEggGameServiceWithContext)
			res, err = imp.ReceiveLiveData(ctx, inputDefine)
			if err != nil {
				return err
			}
		}
		output, err = proto.Marshal(&res)
		if err != nil {
			return err
		}

	default:
		return fmt.Errorf("func mismatch")
	}
	var _status map[string]string
	s, ok := current.GetResponseStatus(ctx)
	if ok && s != nil {
		_status = s
	}
	var _context map[string]string
	c, ok := current.GetResponseContext(ctx)
	if ok && c != nil {
		_context = c
	}
	*resp = requestf.ResponsePacket{
		IVersion:     1,
		CPacketType:  0,
		IRequestId:   req.IRequestId,
		IMessageType: 0,
		IRet:         0,
		SBuffer:      tools.ByteToInt8(output),
		Status:       _status,
		SResultDesc:  "",
		Context:      _context,
	}
	return nil
}

// ReceiveUserGameData is client rpc method as defined
func (obj *GoldenEggGameService) ReceiveUserGameData(input ReceiveUserGameDataReq, _opt ...map[string]string) (output ReceiveRsp, err error) {
	ctx := context.Background()
	return obj.ReceiveUserGameDataWithContext(ctx, input, _opt...)
}

// ReceiveUserGameDataWithContext is client rpc method as defined
func (obj *GoldenEggGameService) ReceiveUserGameDataWithContext(ctx context.Context, input ReceiveUserGameDataReq, _opt ...map[string]string) (output ReceiveRsp, err error) {
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}

	resp := new(requestf.ResponsePacket)

	err = obj.s.Tars_invoke(ctx, 0, "ReceiveUserGameData", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range resp.Status {
			_status[k] = v
		}
	}

	return output, nil
}

// ReceiveLiveData is client rpc method as defined
func (obj *GoldenEggGameService) ReceiveLiveData(input ReceiveLiveDataReq, _opt ...map[string]string) (output ReceiveRsp, err error) {
	ctx := context.Background()
	return obj.ReceiveLiveDataWithContext(ctx, input, _opt...)
}

// ReceiveLiveDataWithContext is client rpc method as defined
func (obj *GoldenEggGameService) ReceiveLiveDataWithContext(ctx context.Context, input ReceiveLiveDataReq, _opt ...map[string]string) (output ReceiveRsp, err error) {
	var inputMarshal []byte
	inputMarshal, err = proto.Marshal(&input)
	if err != nil {
		return output, err
	}

	var _status map[string]string
	var _context map[string]string
	if len(_opt) == 1 {
		_context = _opt[0]
	} else if len(_opt) == 2 {
		_context = _opt[0]
		_status = _opt[1]
	}

	resp := new(requestf.ResponsePacket)

	err = obj.s.Tars_invoke(ctx, 0, "ReceiveLiveData", inputMarshal, _status, _context, resp)
	if err != nil {
		return output, err
	}
	if err = proto.Unmarshal(tools.Int8ToByte(resp.SBuffer), &output); err != nil {
		return output, err
	}

	if len(_opt) == 1 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
	} else if len(_opt) == 2 {
		for k := range _context {
			delete(_context, k)
		}
		for k, v := range resp.Context {
			_context[k] = v
		}
		for k := range _status {
			delete(_status, k)
		}
		for k, v := range resp.Status {
			_status[k] = v
		}
	}

	return output, nil
}
